"""AVANCES

Revision ID: 1f37bffe989f
Revises: d90bb5c56a3b
Create Date: 2025-03-22 12:06:20.122213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f37bffe989f'
down_revision: Union[str, None] = 'd90bb5c56a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Productos', 'margen_porcentaje',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Productos', 'margen_porcentaje',
               existing_type=sa.String(length=5),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
