"""Agregando base de datos

Revision ID: 22e279fdf19a
Revises: 15ad2273189a
Create Date: 2025-03-21 15:55:16.235440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e279fdf19a'
down_revision: Union[str, None] = '15ad2273189a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Areas_negocios', ['id'])
    op.create_unique_constraint(None, 'Categorias_de_clientes', ['id'])
    op.create_unique_constraint(None, 'Categorias_productos', ['id'])
    op.alter_column('Categorias_proveedores', 'descripcion',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'Categorias_proveedores', ['id'])
    op.create_unique_constraint(None, 'Clientes', ['id'])
    op.create_unique_constraint(None, 'Compras', ['id'])
    op.create_unique_constraint(None, 'Detalles_compras', ['id'])
    op.create_unique_constraint(None, 'Metodos_pagos', ['id'])
    op.create_unique_constraint(None, 'Productos', ['id'])
    op.create_unique_constraint(None, 'Proveedores', ['id'])
    op.create_unique_constraint(None, 'Representantes_clientes_morales', ['id'])
    op.create_unique_constraint(None, 'Representantes_proveedores', ['id'])
    op.create_unique_constraint(None, 'Sucursales', ['id'])
    op.create_unique_constraint(None, 'Transacciones', ['id'])
    op.create_unique_constraint(None, 'Turnos', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Turnos', type_='unique')
    op.drop_constraint(None, 'Transacciones', type_='unique')
    op.drop_constraint(None, 'Sucursales', type_='unique')
    op.drop_constraint(None, 'Representantes_proveedores', type_='unique')
    op.drop_constraint(None, 'Representantes_clientes_morales', type_='unique')
    op.drop_constraint(None, 'Proveedores', type_='unique')
    op.drop_constraint(None, 'Productos', type_='unique')
    op.drop_constraint(None, 'Metodos_pagos', type_='unique')
    op.drop_constraint(None, 'Detalles_compras', type_='unique')
    op.drop_constraint(None, 'Compras', type_='unique')
    op.drop_constraint(None, 'Clientes', type_='unique')
    op.drop_constraint(None, 'Categorias_proveedores', type_='unique')
    op.alter_column('Categorias_proveedores', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.drop_constraint(None, 'Categorias_productos', type_='unique')
    op.drop_constraint(None, 'Categorias_de_clientes', type_='unique')
    op.drop_constraint(None, 'Areas_negocios', type_='unique')
    # ### end Alembic commands ###
