"""migracion

Revision ID: 72abcb875b37
Revises: 715dd3a29a9a
Create Date: 2025-04-25 17:30:59.333190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72abcb875b37'
down_revision: Union[str, None] = '715dd3a29a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Areas_negocios', ['id'])
    op.create_unique_constraint(None, 'Categorias_de_clientes', ['id'])
    op.create_unique_constraint(None, 'Categorias_productos', ['id'])
    op.create_unique_constraint(None, 'Categorias_proveedores', ['id'])
    op.create_unique_constraint(None, 'Clientes', ['id'])
    op.create_unique_constraint(None, 'Compras', ['id'])
    op.create_unique_constraint(None, 'Detalles_compras', ['id'])
    op.create_unique_constraint(None, 'Detalles_ventas', ['id'])
    op.create_unique_constraint(None, 'Metodos_pagos', ['id'])
    op.create_unique_constraint(None, 'Movimientos_inventario', ['id'])
    op.create_unique_constraint(None, 'Productos', ['id'])
    op.create_unique_constraint(None, 'Proveedores', ['id'])
    op.create_unique_constraint(None, 'Representantes_clientes_morales', ['id'])
    op.create_unique_constraint(None, 'Representantes_proveedores', ['id'])
    op.create_unique_constraint(None, 'Sucursales', ['id'])
    op.create_unique_constraint(None, 'Transacciones', ['id'])
    op.create_unique_constraint(None, 'Turnos', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Turnos', type_='unique')
    op.drop_constraint(None, 'Transacciones', type_='unique')
    op.drop_constraint(None, 'Sucursales', type_='unique')
    op.drop_constraint(None, 'Representantes_proveedores', type_='unique')
    op.drop_constraint(None, 'Representantes_clientes_morales', type_='unique')
    op.drop_constraint(None, 'Proveedores', type_='unique')
    op.drop_constraint(None, 'Productos', type_='unique')
    op.drop_constraint(None, 'Movimientos_inventario', type_='unique')
    op.drop_constraint(None, 'Metodos_pagos', type_='unique')
    op.drop_constraint(None, 'Detalles_ventas', type_='unique')
    op.drop_constraint(None, 'Detalles_compras', type_='unique')
    op.drop_constraint(None, 'Compras', type_='unique')
    op.drop_constraint(None, 'Clientes', type_='unique')
    op.drop_constraint(None, 'Categorias_proveedores', type_='unique')
    op.drop_constraint(None, 'Categorias_productos', type_='unique')
    op.drop_constraint(None, 'Categorias_de_clientes', type_='unique')
    op.drop_constraint(None, 'Areas_negocios', type_='unique')
    # ### end Alembic commands ###
