"""Agregando base de datos

Revision ID: 8dd0ce9cae7a
Revises: 22e279fdf19a
Create Date: 2025-03-21 16:31:11.967427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd0ce9cae7a'
down_revision: Union[str, None] = '22e279fdf19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Proveedores', sa.Column('clave_moneda', sa.String(length=5), nullable=True))
    op.add_column('Proveedores', sa.Column('tipo_moneda', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Proveedores', 'tipo_moneda')
    op.drop_column('Proveedores', 'clave_moneda')
    # ### end Alembic commands ###
