"""avance

Revision ID: 904f4c98d0f9
Revises: f020a738d26f
Create Date: 2025-03-28 13:28:37.576288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904f4c98d0f9'
down_revision: Union[str, None] = 'f020a738d26f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Areas_negocios', ['id'])
    op.create_unique_constraint(None, 'Categorias_de_clientes', ['id'])
    op.create_unique_constraint(None, 'Categorias_productos', ['id'])
    op.create_unique_constraint(None, 'Categorias_proveedores', ['id'])
    op.create_unique_constraint(None, 'Clientes', ['id'])
    op.create_unique_constraint(None, 'Compras', ['id'])
    op.create_unique_constraint(None, 'Detalles_compras', ['id'])
    op.create_unique_constraint(None, 'Detalles_ventas', ['id'])
    op.create_unique_constraint(None, 'Metodos_pagos', ['id'])
    op.add_column('Movimientos_inventario', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'Movimientos_inventario', ['id'])
    op.create_foreign_key(None, 'Movimientos_inventario', 'Usuarios', ['usuario_id'], ['id'])
    op.create_unique_constraint(None, 'Productos', ['id'])
    op.create_unique_constraint(None, 'Proveedores', ['id'])
    op.create_unique_constraint(None, 'Representantes_clientes_morales', ['id'])
    op.create_unique_constraint(None, 'Representantes_proveedores', ['id'])
    op.create_unique_constraint(None, 'Sucursales', ['id'])
    op.create_unique_constraint(None, 'Transacciones', ['id'])
    op.create_unique_constraint(None, 'Turnos', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Turnos', type_='unique')
    op.drop_constraint(None, 'Transacciones', type_='unique')
    op.drop_constraint(None, 'Sucursales', type_='unique')
    op.drop_constraint(None, 'Representantes_proveedores', type_='unique')
    op.drop_constraint(None, 'Representantes_clientes_morales', type_='unique')
    op.drop_constraint(None, 'Proveedores', type_='unique')
    op.drop_constraint(None, 'Productos', type_='unique')
    op.drop_constraint(None, 'Movimientos_inventario', type_='foreignkey')
    op.drop_constraint(None, 'Movimientos_inventario', type_='unique')
    op.drop_column('Movimientos_inventario', 'usuario_id')
    op.drop_constraint(None, 'Metodos_pagos', type_='unique')
    op.drop_constraint(None, 'Detalles_ventas', type_='unique')
    op.drop_constraint(None, 'Detalles_compras', type_='unique')
    op.drop_constraint(None, 'Compras', type_='unique')
    op.drop_constraint(None, 'Clientes', type_='unique')
    op.drop_constraint(None, 'Categorias_proveedores', type_='unique')
    op.drop_constraint(None, 'Categorias_productos', type_='unique')
    op.drop_constraint(None, 'Categorias_de_clientes', type_='unique')
    op.drop_constraint(None, 'Areas_negocios', type_='unique')
    # ### end Alembic commands ###
