"""correccion en la relacion entre proveedores y categoria

Revision ID: b7a8a4911773
Revises: 763def26605c
Create Date: 2025-03-17 22:20:12.239658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a8a4911773'
down_revision: Union[str, None] = '763def26605c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Proveedores', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.drop_constraint('Proveedores_categorias_id_fkey', 'Proveedores', type_='foreignkey')
    op.create_foreign_key(None, 'Proveedores', 'Categorias_proveedores', ['categoria_id'], ['id'])
    op.drop_column('Proveedores', 'categorias_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Proveedores', sa.Column('categorias_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Proveedores', type_='foreignkey')
    op.create_foreign_key('Proveedores_categorias_id_fkey', 'Proveedores', 'Categorias_proveedores', ['categorias_id'], ['id'])
    op.drop_column('Proveedores', 'categoria_id')
    # ### end Alembic commands ###
