"""avances

Revision ID: d4f59a9ef445
Revises: 
Create Date: 2025-03-24 13:16:13.302324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f59a9ef445'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Unidad_medida_productos', sa.Column('nombre', sa.String(length=25), nullable=True))
    op.drop_column('Unidad_medida_productos', 'unidad_medida')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Unidad_medida_productos', sa.Column('unidad_medida', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.drop_column('Unidad_medida_productos', 'nombre')
    # ### end Alembic commands ###
