"""AVANCES

Revision ID: d90bb5c56a3b
Revises: fcda8dd01dfe
Create Date: 2025-03-22 11:56:04.602883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90bb5c56a3b'
down_revision: Union[str, None] = 'fcda8dd01dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Productos', sa.Column('margen_porcentaje', sa.Float(), nullable=True))
    op.drop_column('Productos', 'margen')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Productos', sa.Column('margen', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('Productos', 'margen_porcentaje')
    # ### end Alembic commands ###
