"""migracion

Revision ID: e9cc564011fa
Revises: 954ffc9fc2bf
Create Date: 2025-04-18 12:33:40.194866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9cc564011fa'
down_revision: Union[str, None] = '954ffc9fc2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_categoriaProducto', 'Categorias_productos', ['id'], unique=False)
    op.create_index('idx_presentacionProducto', 'Presentacion_productos', ['id'], unique=False)
    op.create_index('idx_proveedorId', 'Proveedores', ['id'], unique=False)
    op.create_index('idx_unidadMedidaProducto', 'Unidad_medida_productos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unidadMedidaProducto', table_name='Unidad_medida_productos')
    op.drop_index('idx_proveedorId', table_name='Proveedores')
    op.drop_index('idx_presentacionProducto', table_name='Presentacion_productos')
    op.drop_index('idx_categoriaProducto', table_name='Categorias_productos')
    # ### end Alembic commands ###
