"""AVANCES

Revision ID: fcda8dd01dfe
Revises: 8dd0ce9cae7a
Create Date: 2025-03-22 11:20:07.780343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcda8dd01dfe'
down_revision: Union[str, None] = '8dd0ce9cae7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Productos', sa.Column('margen', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Productos', 'margen')
    # ### end Alembic commands ###
