# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\LUIS_ANGEL_VALLEJO\software-punto-de-venta\app\View\UserInterfaceUi\PRODUCTOS_PROVEEDORES.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contenedor_productos_proveedores(object):
    def setupUi(self, contenedor_productos_proveedores):
        contenedor_productos_proveedores.setObjectName("contenedor_productos_proveedores")
        contenedor_productos_proveedores.resize(834, 473)
        contenedor_productos_proveedores.setStyleSheet("[objectName*=\"contenedor\"]{\n"
"background: #fffefb;\n"
"}\n"
"[objectName*=\"etiqueta_\"]{\n"
"font-size:14px;\n"
"font-family: Arial;\n"
"font-weight:bold;\n"
"color: #1d1c1c;\n"
"}\n"
"[objectName*=\"txt_\"]{\n"
"background: #F5F5F5;\n"
"border:none;\n"
"border-radius: 5px;\n"
"color: #1d1c1c;\n"
"font-size: 14px;\n"
"border-bottom: 1px solid #787878;\n"
"}\n"
"[objectName*=\"txt_\"]:focus{\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"[objectName*=\"btn_btn\"]{\n"
"background: #00619a;\n"
"font-size: 14px;\n"
"font-family: Arial;\n"
"font-weight: bold;\n"
"min-height: 25px;\n"
"border: none;\n"
"border-radius: 5px;\n"
"color: #fffefb;\n"
"padding: 3px 10px;\n"
"}\n"
"[objectName*=\"btn_btn\"]:hover{\n"
"background: #2196F3;\n"
"}\n"
"[objectName*=\"btn_btn\"]:pressed{\n"
"background: #1B80D0;\n"
"}\n"
"[objectName*=\"btn_btn_eliminar\"]:hover{\n"
"background: #ee1d52;\n"
"}\n"
"[objectName*=\"btn_btn_eliminar\"]:pressed{\n"
"background: #B13636;\n"
"}\n"
"[objectName*=\"btn_btn_agregar\"]:hover{\n"
"background: #68a67d;\n"
"}\n"
"[objectName*=\"btn_btn_agregar\"]:pressed{\n"
"background: #578B69;\n"
"}\n"
"[objectName^=\"cajaopciones_\"]{\n"
"border: none;\n"
"border-bottom: 1px solid rgb(29, 28, 28);\n"
"borde-radius: 5px;\n"
"padding: 2px;\n"
"background-color: #f5f4f1;\n"
"borde-radius: 5px;\n"
"font-size: 14px;\n"
"min-width:120px;\n"
"}\n"
"[objectName^=\"cajaopciones_\"]::drop-down{\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: top right;\n"
"padding-right:5px;\n"
"width: 20%;\n"
"border-left-width: 1px;\n"
"borde-radius: 5px;\n"
"background-color: #f5f4f1;\n"
"}\n"
"[objectName^=\"cajaopciones_\"]::down-arrow{\n"
"image: url(:/Icons/Bootstrap/filter-left.svg);\n"
"width: 17%;\n"
"height: 17%;\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}\n"
"[objectName*=\"tabla_\"] {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"/* Encabezados de la tabla */\n"
"[objectName*=\"tabla_\"] QHeaderView::section {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"    font-family: \"Arial\";\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"/* Encabezado horizontal */\n"
"[objectName*=\"tabla_\"] QHeaderView::horizontal {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Encabezado vertical */\n"
"[objectName*=\"tabla_\"] QHeaderView::vertical {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(contenedor_productos_proveedores)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.contenedor_scrollarea = QtWidgets.QScrollArea(contenedor_productos_proveedores)
        self.contenedor_scrollarea.setWidgetResizable(True)
        self.contenedor_scrollarea.setObjectName("contenedor_scrollarea")
        self.contenedor_contenido_scrollarea = QtWidgets.QWidget()
        self.contenedor_contenido_scrollarea.setGeometry(QtCore.QRect(0, 0, 832, 471))
        self.contenedor_contenido_scrollarea.setObjectName("contenedor_contenido_scrollarea")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.contenedor_contenido_scrollarea)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.contenedor_tabs = QtWidgets.QTabWidget(self.contenedor_contenido_scrollarea)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.contenedor_tabs.setFont(font)
        self.contenedor_tabs.setObjectName("contenedor_tabs")
        self.contenedor_tab_productos_de_proveedor = QtWidgets.QWidget()
        self.contenedor_tab_productos_de_proveedor.setObjectName("contenedor_tab_productos_de_proveedor")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.contenedor_tab_productos_de_proveedor)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.contenedor_productos_proveedor = QtWidgets.QFrame(self.contenedor_tab_productos_de_proveedor)
        self.contenedor_productos_proveedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_productos_proveedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_productos_proveedor.setObjectName("contenedor_productos_proveedor")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.contenedor_productos_proveedor)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.contenedor_botones_superior = QtWidgets.QFrame(self.contenedor_productos_proveedor)
        self.contenedor_botones_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_botones_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_botones_superior.setObjectName("contenedor_botones_superior")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.contenedor_botones_superior)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_btn_editar_producto_del_proveedor = QtWidgets.QPushButton(self.contenedor_botones_superior)
        self.btn_btn_editar_producto_del_proveedor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/editar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_editar_producto_del_proveedor.setIcon(icon)
        self.btn_btn_editar_producto_del_proveedor.setObjectName("btn_btn_editar_producto_del_proveedor")
        self.gridLayout_4.addWidget(self.btn_btn_editar_producto_del_proveedor, 1, 3, 1, 1, QtCore.Qt.AlignRight)
        self.btn_btn_actualizar_tabla_productos_del_proveedor = QtWidgets.QPushButton(self.contenedor_botones_superior)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/actualizar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_actualizar_tabla_productos_del_proveedor.setIcon(icon1)
        self.btn_btn_actualizar_tabla_productos_del_proveedor.setObjectName("btn_btn_actualizar_tabla_productos_del_proveedor")
        self.gridLayout_4.addWidget(self.btn_btn_actualizar_tabla_productos_del_proveedor, 1, 1, 1, 1)
        self.btn_btn_eliminar_producto_del_proveedor = QtWidgets.QPushButton(self.contenedor_botones_superior)
        self.btn_btn_eliminar_producto_del_proveedor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/cerrar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_eliminar_producto_del_proveedor.setIcon(icon2)
        self.btn_btn_eliminar_producto_del_proveedor.setObjectName("btn_btn_eliminar_producto_del_proveedor")
        self.gridLayout_4.addWidget(self.btn_btn_eliminar_producto_del_proveedor, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.contenedor_botones_superior, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.etiqueta_nombre_producto = QtWidgets.QLabel(self.contenedor_productos_proveedor)
        self.etiqueta_nombre_producto.setObjectName("etiqueta_nombre_producto")
        self.horizontalLayout.addWidget(self.etiqueta_nombre_producto)
        self.cajaopciones_filtro_nombre = QtWidgets.QComboBox(self.contenedor_productos_proveedor)
        self.cajaopciones_filtro_nombre.setObjectName("cajaopciones_filtro_nombre")
        self.cajaopciones_filtro_nombre.addItem("")
        self.cajaopciones_filtro_nombre.addItem("")
        self.horizontalLayout.addWidget(self.cajaopciones_filtro_nombre)
        self.txt_nombre_producto = QtWidgets.QLineEdit(self.contenedor_productos_proveedor)
        self.txt_nombre_producto.setClearButtonEnabled(True)
        self.txt_nombre_producto.setObjectName("txt_nombre_producto")
        self.horizontalLayout.addWidget(self.txt_nombre_producto)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabla_productos_del_proveedor = QtWidgets.QTableView(self.contenedor_productos_proveedor)
        self.tabla_productos_del_proveedor.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_productos_del_proveedor.setObjectName("tabla_productos_del_proveedor")
        self.tabla_productos_del_proveedor.horizontalHeader().setDefaultSectionSize(200)
        self.tabla_productos_del_proveedor.horizontalHeader().setMinimumSectionSize(150)
        self.tabla_productos_del_proveedor.horizontalHeader().setStretchLastSection(False)
        self.tabla_productos_del_proveedor.verticalHeader().setVisible(False)
        self.tabla_productos_del_proveedor.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.tabla_productos_del_proveedor, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.contenedor_productos_proveedor, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/box-seam.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contenedor_tabs.addTab(self.contenedor_tab_productos_de_proveedor, icon3, "")
        self.contenedor_tab_productos_de_sistema = QtWidgets.QWidget()
        self.contenedor_tab_productos_de_sistema.setObjectName("contenedor_tab_productos_de_sistema")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.contenedor_tab_productos_de_sistema)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.contenedor_contenido_tab_productos_del_sistema = QtWidgets.QFrame(self.contenedor_tab_productos_de_sistema)
        self.contenedor_contenido_tab_productos_del_sistema.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_contenido_tab_productos_del_sistema.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_contenido_tab_productos_del_sistema.setObjectName("contenedor_contenido_tab_productos_del_sistema")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.contenedor_contenido_tab_productos_del_sistema)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.contenedor_botones_superior_productos_del_sistema = QtWidgets.QFrame(self.contenedor_contenido_tab_productos_del_sistema)
        self.contenedor_botones_superior_productos_del_sistema.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_botones_superior_productos_del_sistema.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_botones_superior_productos_del_sistema.setObjectName("contenedor_botones_superior_productos_del_sistema")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.contenedor_botones_superior_productos_del_sistema)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(577, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 0, 1, 1)
        self.btn_btn_agregar_producto_al_proveedor = QtWidgets.QPushButton(self.contenedor_botones_superior_productos_del_sistema)
        self.btn_btn_agregar_producto_al_proveedor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/vincular.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_agregar_producto_al_proveedor.setIcon(icon4)
        self.btn_btn_agregar_producto_al_proveedor.setObjectName("btn_btn_agregar_producto_al_proveedor")
        self.gridLayout_7.addWidget(self.btn_btn_agregar_producto_al_proveedor, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.contenedor_botones_superior_productos_del_sistema, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.etiqueta_nombreproducto_del_sistema = QtWidgets.QLabel(self.contenedor_contenido_tab_productos_del_sistema)
        self.etiqueta_nombreproducto_del_sistema.setObjectName("etiqueta_nombreproducto_del_sistema")
        self.horizontalLayout_2.addWidget(self.etiqueta_nombreproducto_del_sistema)
        self.cajaopciones_filtro_nombre_productos_del_sistema = QtWidgets.QComboBox(self.contenedor_contenido_tab_productos_del_sistema)
        self.cajaopciones_filtro_nombre_productos_del_sistema.setObjectName("cajaopciones_filtro_nombre_productos_del_sistema")
        self.cajaopciones_filtro_nombre_productos_del_sistema.addItem("")
        self.cajaopciones_filtro_nombre_productos_del_sistema.addItem("")
        self.horizontalLayout_2.addWidget(self.cajaopciones_filtro_nombre_productos_del_sistema)
        self.txt_nombre_productodelsistema = QtWidgets.QLineEdit(self.contenedor_contenido_tab_productos_del_sistema)
        self.txt_nombre_productodelsistema.setClearButtonEnabled(True)
        self.txt_nombre_productodelsistema.setObjectName("txt_nombre_productodelsistema")
        self.horizontalLayout_2.addWidget(self.txt_nombre_productodelsistema)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabla_productos_del_sistema = QtWidgets.QTableView(self.contenedor_contenido_tab_productos_del_sistema)
        self.tabla_productos_del_sistema.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_productos_del_sistema.setObjectName("tabla_productos_del_sistema")
        self.tabla_productos_del_sistema.horizontalHeader().setDefaultSectionSize(200)
        self.tabla_productos_del_sistema.horizontalHeader().setMinimumSectionSize(150)
        self.tabla_productos_del_sistema.verticalHeader().setVisible(False)
        self.gridLayout_8.addWidget(self.tabla_productos_del_sistema, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.contenedor_contenido_tab_productos_del_sistema, 0, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/boxes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contenedor_tabs.addTab(self.contenedor_tab_productos_de_sistema, icon5, "")
        self.gridLayout_2.addWidget(self.contenedor_tabs, 1, 0, 1, 1)
        self.etiqueta_nombre_del_proveedor = QtWidgets.QLabel(self.contenedor_contenido_scrollarea)
        self.etiqueta_nombre_del_proveedor.setText("")
        self.etiqueta_nombre_del_proveedor.setObjectName("etiqueta_nombre_del_proveedor")
        self.gridLayout_2.addWidget(self.etiqueta_nombre_del_proveedor, 0, 0, 1, 1)
        self.contenedor_scrollarea.setWidget(self.contenedor_contenido_scrollarea)
        self.gridLayout.addWidget(self.contenedor_scrollarea, 0, 0, 1, 1)

        self.retranslateUi(contenedor_productos_proveedores)
        self.contenedor_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(contenedor_productos_proveedores)

    def retranslateUi(self, contenedor_productos_proveedores):
        _translate = QtCore.QCoreApplication.translate
        contenedor_productos_proveedores.setWindowTitle(_translate("contenedor_productos_proveedores", "Form"))
        self.btn_btn_editar_producto_del_proveedor.setText(_translate("contenedor_productos_proveedores", "Editar"))
        self.btn_btn_actualizar_tabla_productos_del_proveedor.setText(_translate("contenedor_productos_proveedores", "Actualizar Tabla"))
        self.btn_btn_eliminar_producto_del_proveedor.setText(_translate("contenedor_productos_proveedores", "Quitar"))
        self.etiqueta_nombre_producto.setText(_translate("contenedor_productos_proveedores", "Buscar Producto"))
        self.cajaopciones_filtro_nombre.setItemText(0, _translate("contenedor_productos_proveedores", "Igual A"))
        self.cajaopciones_filtro_nombre.setItemText(1, _translate("contenedor_productos_proveedores", "Que Contenga"))
        self.txt_nombre_producto.setPlaceholderText(_translate("contenedor_productos_proveedores", "Nombre del Producto"))
        self.contenedor_tabs.setTabText(self.contenedor_tabs.indexOf(self.contenedor_tab_productos_de_proveedor), _translate("contenedor_productos_proveedores", "Productos del Proveedor"))
        self.btn_btn_agregar_producto_al_proveedor.setText(_translate("contenedor_productos_proveedores", "Vincular al proveedor"))
        self.etiqueta_nombreproducto_del_sistema.setText(_translate("contenedor_productos_proveedores", "Nombre del Producto:"))
        self.cajaopciones_filtro_nombre_productos_del_sistema.setItemText(0, _translate("contenedor_productos_proveedores", "Es Igual"))
        self.cajaopciones_filtro_nombre_productos_del_sistema.setItemText(1, _translate("contenedor_productos_proveedores", "Que Contenga"))
        self.txt_nombre_productodelsistema.setPlaceholderText(_translate("contenedor_productos_proveedores", "Nombre del Producto"))
        self.contenedor_tabs.setTabText(self.contenedor_tabs.indexOf(self.contenedor_tab_productos_de_sistema), _translate("contenedor_productos_proveedores", "Productos del Sistema"))
import ibootstrap_rc
import iconosSVG_rc
