# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hackl/Documentos/projects/software-punto-de-venta/app/View/UserInterfaceUi/UI_CONTROL_PROVEEDORES.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Control_Proveedores(object):
    def setupUi(self, Control_Proveedores):
        Control_Proveedores.setObjectName("Control_Proveedores")
        Control_Proveedores.resize(1012, 621)
        Control_Proveedores.setStyleSheet("#Control_Proveedores{\n"
"background: #fffefb;\n"
"}\n"
"[objectName*=\"contenedor\"]{\n"
"background: #fffefb;\n"
"}\n"
"#label_wp_titulo_proveedores{\n"
"background: #023375;\n"
"min-height: 40px;\n"
"max-height: 40px;\n"
"font-size:20px;\n"
"font-weight: bold;\n"
"color:#fffefb;\n"
"padding-left:5px;\n"
"}\n"
"*[objectName*=\"etiquetaTitulo_\"]{\n"
"font-size:18px;\n"
"font-family: Arial;\n"
"font-weight:bold;\n"
"color: #1d1c1c;\n"
"}\n"
"*[objectName*=\"etiqueta_\"]{\n"
"font-size:14px;\n"
"font-family: Arial;\n"
"font-weight:bold;\n"
"color: #1d1c1c;\n"
"}\n"
"[objectName*=\"txt_\"]{\n"
"background: #F5F5F5;\n"
"border:none;\n"
"border-radius: 5px;\n"
"color: #1d1c1c;\n"
"font-size: 14px;\n"
"border-bottom: 1px solid;\n"
"}\n"
"[objectName*=\"txtlargo_\"]{\n"
"background: #F5F5F5;\n"
"border:none;\n"
"border-radius: 5px;\n"
"color: #1d1c1c;\n"
"font-size: 14px;\n"
"border: 1px solid;\n"
"max-height: 100px;\n"
"}\n"
"[objectName*=\"btn_btn\"]{\n"
"background: #00619a;\n"
"font-size: 12px;\n"
"font-family: Arial;\n"
"font-weight: bold;\n"
"min-height: 25px;\n"
"border: none;\n"
"border-radius: 5px;\n"
"color: #fffefb;\n"
"margin-left: 5px;\n"
"margin-right: 5px;\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}\n"
"#btn_btn_agregarcategoria{\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}\n"
"#btn_btn_buscarproveedor{\n"
"width: 30px;\n"
"}\n"
"[objectName*=\"btnradio\"]{\n"
"font-size:14px;\n"
"font-family:Arial;\n"
"color: #1d1c1c;\n"
"font-weight: bold;\n"
"}\n"
"[objectName*=\"btn_btn\"]:hover{\n"
"background: #2196F3;\n"
"}\n"
"#btn_btn_cancelar:hover{\n"
"background: #EE1D52;\n"
"}\n"
"#btn_btn_guardar:hover{\n"
"background: #68a67d;\n"
"}\n"
"[objectName*=\"txt_\"]:focus{\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"[objectName*=\"txtlargo_\"]:focus{\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"\n"
"[objectName^=\"cajaopciones\"]{\n"
"border: none;\n"
"border-bottom: 1px solid #3b3c3d;\n"
"border-top-left-radius: 4px;\n"
"border-top-right-radius: 4px;\n"
"padding: 2px;\n"
"background-color: #F5F5F5;\n"
"font-size: 14px;\n"
"width:87px;\n"
"}\n"
"[objectName^=\"cajaopciones\"]::drop-down{\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: top right;\n"
"padding-right:5px;\n"
"width: 20%;\n"
"border-left-width: 1px;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"background-color: #F5F5F5;\n"
"}\n"
"[objectName^=\"cajaopciones_\"]::down-arrow{\n"
"image: url(:/Icons/Bootstrap/filter-left.svg);\n"
"width: 17%;\n"
"height: 17%;\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}\n"
"/*TABLA*/\n"
"\n"
"[objectName*=\"tabla_\"] {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Barra vertical */\n"
"/* Encabezados de la tabla */\n"
"[objectName*=\"tabla_\"] QHeaderView::section {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"    font-family: \"Arial\";\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"/* Encabezado horizontal */\n"
"[objectName*=\"tabla_\"] QHeaderView::horizontal {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Encabezado vertical */\n"
"[objectName*=\"tabla_\"] QHeaderView::vertical {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Control_Proveedores)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_wp_titulo_proveedores = QtWidgets.QLabel(Control_Proveedores)
        self.label_wp_titulo_proveedores.setMinimumSize(QtCore.QSize(0, 40))
        self.label_wp_titulo_proveedores.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_wp_titulo_proveedores.setObjectName("label_wp_titulo_proveedores")
        self.gridLayout.addWidget(self.label_wp_titulo_proveedores, 0, 0, 1, 1)
        self.contenedor = QtWidgets.QFrame(Control_Proveedores)
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.contenedor)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.contenedor_scrollArea = QtWidgets.QScrollArea(self.contenedor)
        self.contenedor_scrollArea.setWidgetResizable(True)
        self.contenedor_scrollArea.setObjectName("contenedor_scrollArea")
        self.contenedor_scroll_area_contenido = QtWidgets.QWidget()
        self.contenedor_scroll_area_contenido.setGeometry(QtCore.QRect(0, 0, 1008, 577))
        self.contenedor_scroll_area_contenido.setObjectName("contenedor_scroll_area_contenido")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.contenedor_scroll_area_contenido)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.contenedor_todoproveedor = QtWidgets.QFrame(self.contenedor_scroll_area_contenido)
        self.contenedor_todoproveedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_todoproveedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_todoproveedor.setObjectName("contenedor_todoproveedor")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.contenedor_todoproveedor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_codigopostal = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_codigopostal.setObjectName("txt_codigopostal")
        self.gridLayout_2.addWidget(self.txt_codigopostal, 10, 1, 1, 2)
        self.txt_colonia = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_colonia.setObjectName("txt_colonia")
        self.gridLayout_2.addWidget(self.txt_colonia, 6, 1, 1, 2)
        self.contenedor_datosrepresentante = QtWidgets.QFrame(self.contenedor_todoproveedor)
        self.contenedor_datosrepresentante.setEnabled(True)
        self.contenedor_datosrepresentante.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_datosrepresentante.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_datosrepresentante.setObjectName("contenedor_datosrepresentante")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.contenedor_datosrepresentante)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txt_nombrerepresentante = QtWidgets.QLineEdit(self.contenedor_datosrepresentante)
        self.txt_nombrerepresentante.setObjectName("txt_nombrerepresentante")
        self.gridLayout_3.addWidget(self.txt_nombrerepresentante, 0, 1, 1, 1)
        self.etiqueta_nombrerepresentante = QtWidgets.QLabel(self.contenedor_datosrepresentante)
        self.etiqueta_nombrerepresentante.setObjectName("etiqueta_nombrerepresentante")
        self.gridLayout_3.addWidget(self.etiqueta_nombrerepresentante, 0, 0, 1, 1)
        self.etiqueta_apellidomaternorepresentante = QtWidgets.QLabel(self.contenedor_datosrepresentante)
        self.etiqueta_apellidomaternorepresentante.setObjectName("etiqueta_apellidomaternorepresentante")
        self.gridLayout_3.addWidget(self.etiqueta_apellidomaternorepresentante, 2, 0, 1, 1)
        self.etiqueta_apellidopaternorepresentante = QtWidgets.QLabel(self.contenedor_datosrepresentante)
        self.etiqueta_apellidopaternorepresentante.setObjectName("etiqueta_apellidopaternorepresentante")
        self.gridLayout_3.addWidget(self.etiqueta_apellidopaternorepresentante, 1, 0, 1, 1)
        self.etiqueta_puestorepresentante = QtWidgets.QLabel(self.contenedor_datosrepresentante)
        self.etiqueta_puestorepresentante.setObjectName("etiqueta_puestorepresentante")
        self.gridLayout_3.addWidget(self.etiqueta_puestorepresentante, 0, 2, 1, 1)
        self.txt_puestorepresentante = QtWidgets.QLineEdit(self.contenedor_datosrepresentante)
        self.txt_puestorepresentante.setObjectName("txt_puestorepresentante")
        self.gridLayout_3.addWidget(self.txt_puestorepresentante, 0, 3, 1, 1)
        self.etiqueta_telefonorepresentante = QtWidgets.QLabel(self.contenedor_datosrepresentante)
        self.etiqueta_telefonorepresentante.setObjectName("etiqueta_telefonorepresentante")
        self.gridLayout_3.addWidget(self.etiqueta_telefonorepresentante, 1, 2, 1, 1)
        self.txt_telefonorepresentante = QtWidgets.QLineEdit(self.contenedor_datosrepresentante)
        self.txt_telefonorepresentante.setObjectName("txt_telefonorepresentante")
        self.gridLayout_3.addWidget(self.txt_telefonorepresentante, 1, 3, 1, 1)
        self.etiqueta_correorepresentante = QtWidgets.QLabel(self.contenedor_datosrepresentante)
        self.etiqueta_correorepresentante.setObjectName("etiqueta_correorepresentante")
        self.gridLayout_3.addWidget(self.etiqueta_correorepresentante, 2, 2, 1, 1)
        self.txt_correorepresentante = QtWidgets.QLineEdit(self.contenedor_datosrepresentante)
        self.txt_correorepresentante.setObjectName("txt_correorepresentante")
        self.gridLayout_3.addWidget(self.txt_correorepresentante, 2, 3, 1, 1)
        self.txt_apellidopaternorepresen = QtWidgets.QLineEdit(self.contenedor_datosrepresentante)
        self.txt_apellidopaternorepresen.setObjectName("txt_apellidopaternorepresen")
        self.gridLayout_3.addWidget(self.txt_apellidopaternorepresen, 1, 1, 1, 1)
        self.txt_apellidomaternorepresen = QtWidgets.QLineEdit(self.contenedor_datosrepresentante)
        self.txt_apellidomaternorepresen.setObjectName("txt_apellidomaternorepresen")
        self.gridLayout_3.addWidget(self.txt_apellidomaternorepresen, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.contenedor_datosrepresentante, 20, 0, 1, 6)
        self.btn_btn_agregarcategoria = QtWidgets.QPushButton(self.contenedor_todoproveedor)
        self.btn_btn_agregarcategoria.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_agregarcategoria.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/agregar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_agregarcategoria.setIcon(icon)
        self.btn_btn_agregarcategoria.setIconSize(QtCore.QSize(20, 20))
        self.btn_btn_agregarcategoria.setObjectName("btn_btn_agregarcategoria")
        self.gridLayout_2.addWidget(self.btn_btn_agregarcategoria, 16, 2, 1, 1)
        self.etiqueta_telefono = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_telefono.setObjectName("etiqueta_telefono")
        self.gridLayout_2.addWidget(self.etiqueta_telefono, 2, 0, 1, 1)
        self.etiqueta_avenidas = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_avenidas.setObjectName("etiqueta_avenidas")
        self.gridLayout_2.addWidget(self.etiqueta_avenidas, 4, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 22, 0, 1, 1)
        self.cajaopciones_categorias = QtWidgets.QComboBox(self.contenedor_todoproveedor)
        self.cajaopciones_categorias.setObjectName("cajaopciones_categorias")
        self.gridLayout_2.addWidget(self.cajaopciones_categorias, 16, 1, 1, 1)
        self.etiqueta_direccionadicional = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_direccionadicional.setObjectName("etiqueta_direccionadicional")
        self.gridLayout_2.addWidget(self.etiqueta_direccionadicional, 18, 0, 1, 1, QtCore.Qt.AlignTop)
        self.etiqueta_colonia = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_colonia.setObjectName("etiqueta_colonia")
        self.gridLayout_2.addWidget(self.etiqueta_colonia, 6, 0, 1, 1)
        self.txtlargo_descripcioncategoria = QtWidgets.QPlainTextEdit(self.contenedor_todoproveedor)
        self.txtlargo_descripcioncategoria.setObjectName("txtlargo_descripcioncategoria")
        self.gridLayout_2.addWidget(self.txtlargo_descripcioncategoria, 19, 1, 1, 5)
        self.txt_correo = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_correo.setObjectName("txt_correo")
        self.gridLayout_2.addWidget(self.txt_correo, 2, 5, 1, 1)
        self.etiqueta_calles = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_calles.setObjectName("etiqueta_calles")
        self.gridLayout_2.addWidget(self.etiqueta_calles, 4, 0, 1, 1)
        self.txt_web = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_web.setObjectName("txt_web")
        self.gridLayout_2.addWidget(self.txt_web, 10, 5, 1, 1)
        self.txt_avenida = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_avenida.setObjectName("txt_avenida")
        self.gridLayout_2.addWidget(self.txt_avenida, 4, 5, 1, 1)
        self.etiqueta_pais = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_pais.setObjectName("etiqueta_pais")
        self.gridLayout_2.addWidget(self.etiqueta_pais, 8, 4, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.etiqueta_tienerepresentante = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_tienerepresentante.setObjectName("etiqueta_tienerepresentante")
        self.gridLayout_6.addWidget(self.etiqueta_tienerepresentante, 0, 1, 1, 1)
        self.btnradio_representantetrue = QtWidgets.QRadioButton(self.contenedor_todoproveedor)
        self.btnradio_representantetrue.setObjectName("btnradio_representantetrue")
        self.gridLayout_6.addWidget(self.btnradio_representantetrue, 0, 2, 1, 1)
        self.btnradio_representantefalse = QtWidgets.QRadioButton(self.contenedor_todoproveedor)
        self.btnradio_representantefalse.setObjectName("btnradio_representantefalse")
        self.gridLayout_6.addWidget(self.btnradio_representantefalse, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 16, 4, 1, 2)
        self.txt_nombre = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_nombre.setObjectName("txt_nombre")
        self.gridLayout_2.addWidget(self.txt_nombre, 0, 1, 1, 2)
        self.txt_pais = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_pais.setObjectName("txt_pais")
        self.gridLayout_2.addWidget(self.txt_pais, 8, 5, 1, 1)
        self.txt_ciudad = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_ciudad.setObjectName("txt_ciudad")
        self.gridLayout_2.addWidget(self.txt_ciudad, 6, 5, 1, 1)
        self.etiqueta_rfc = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_rfc.setObjectName("etiqueta_rfc")
        self.gridLayout_2.addWidget(self.etiqueta_rfc, 0, 4, 1, 1)
        self.etiqueta_codigopostal = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_codigopostal.setObjectName("etiqueta_codigopostal")
        self.gridLayout_2.addWidget(self.etiqueta_codigopostal, 10, 0, 1, 1)
        self.etiqueta_descripcioncategoria = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_descripcioncategoria.setObjectName("etiqueta_descripcioncategoria")
        self.gridLayout_2.addWidget(self.etiqueta_descripcioncategoria, 19, 0, 1, 1, QtCore.Qt.AlignTop)
        self.txt_calles = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_calles.setObjectName("txt_calles")
        self.gridLayout_2.addWidget(self.txt_calles, 4, 1, 1, 2)
        self.btn_btn_limpiardatos = QtWidgets.QPushButton(self.contenedor_todoproveedor)
        self.btn_btn_limpiardatos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_limpiardatos.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/borrador.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_limpiardatos.setIcon(icon1)
        self.btn_btn_limpiardatos.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_limpiardatos.setObjectName("btn_btn_limpiardatos")
        self.gridLayout_2.addWidget(self.btn_btn_limpiardatos, 21, 0, 1, 1)
        self.etiqueta_web = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_web.setObjectName("etiqueta_web")
        self.gridLayout_2.addWidget(self.etiqueta_web, 10, 4, 1, 1)
        self.etiqueta_estado = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_estado.setObjectName("etiqueta_estado")
        self.gridLayout_2.addWidget(self.etiqueta_estado, 8, 0, 1, 1)
        self.txt_estado = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_estado.setObjectName("txt_estado")
        self.gridLayout_2.addWidget(self.txt_estado, 8, 1, 1, 2)
        self.etiqueta_nombre = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_nombre.setObjectName("etiqueta_nombre")
        self.gridLayout_2.addWidget(self.etiqueta_nombre, 0, 0, 1, 1)
        self.etiqueta_categoria = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_categoria.setObjectName("etiqueta_categoria")
        self.gridLayout_2.addWidget(self.etiqueta_categoria, 16, 0, 1, 1)
        self.etiqueta_ciudad = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_ciudad.setObjectName("etiqueta_ciudad")
        self.gridLayout_2.addWidget(self.etiqueta_ciudad, 6, 4, 1, 1)
        self.txt_rfc = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_rfc.setObjectName("txt_rfc")
        self.gridLayout_2.addWidget(self.txt_rfc, 0, 5, 1, 1)
        self.etiqueta_correo = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_correo.setObjectName("etiqueta_correo")
        self.gridLayout_2.addWidget(self.etiqueta_correo, 2, 4, 1, 1)
        self.txtlargo_direccionadicional = QtWidgets.QPlainTextEdit(self.contenedor_todoproveedor)
        self.txtlargo_direccionadicional.setObjectName("txtlargo_direccionadicional")
        self.gridLayout_2.addWidget(self.txtlargo_direccionadicional, 18, 1, 1, 5)
        self.txt_telefono = QtWidgets.QLineEdit(self.contenedor_todoproveedor)
        self.txt_telefono.setObjectName("txt_telefono")
        self.gridLayout_2.addWidget(self.txt_telefono, 2, 1, 1, 2)
        self.etiqueta_moneda = QtWidgets.QLabel(self.contenedor_todoproveedor)
        self.etiqueta_moneda.setObjectName("etiqueta_moneda")
        self.gridLayout_2.addWidget(self.etiqueta_moneda, 17, 0, 1, 1)
        self.cajaopciones_tipomoneda = QtWidgets.QComboBox(self.contenedor_todoproveedor)
        self.cajaopciones_tipomoneda.setMaxVisibleItems(10)
        self.cajaopciones_tipomoneda.setModelColumn(0)
        self.cajaopciones_tipomoneda.setObjectName("cajaopciones_tipomoneda")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.cajaopciones_tipomoneda.addItem("")
        self.gridLayout_2.addWidget(self.cajaopciones_tipomoneda, 17, 1, 1, 2)
        self.gridLayout_7.addWidget(self.contenedor_todoproveedor, 1, 0, 1, 1)
        self.contenedor_tablareproveedores = QtWidgets.QFrame(self.contenedor_scroll_area_contenido)
        self.contenedor_tablareproveedores.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_tablareproveedores.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_tablareproveedores.setObjectName("contenedor_tablareproveedores")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.contenedor_tablareproveedores)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.etiquetaTitulo_proveedor = QtWidgets.QLabel(self.contenedor_tablareproveedores)
        self.etiquetaTitulo_proveedor.setObjectName("etiquetaTitulo_proveedor")
        self.gridLayout_4.addWidget(self.etiquetaTitulo_proveedor, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txt_buscarproveedor = QtWidgets.QLineEdit(self.contenedor_tablareproveedores)
        self.txt_buscarproveedor.setObjectName("txt_buscarproveedor")
        self.gridLayout_5.addWidget(self.txt_buscarproveedor, 0, 0, 1, 1)
        self.btn_btn_buscarproveedor = QtWidgets.QToolButton(self.contenedor_tablareproveedores)
        self.btn_btn_buscarproveedor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_buscarproveedor.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/buscar_persona_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_buscarproveedor.setIcon(icon2)
        self.btn_btn_buscarproveedor.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_buscarproveedor.setObjectName("btn_btn_buscarproveedor")
        self.gridLayout_5.addWidget(self.btn_btn_buscarproveedor, 0, 1, 1, 1)
        self.tabla_proveedores = QtWidgets.QTableView(self.contenedor_tablareproveedores)
        self.tabla_proveedores.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_proveedores.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_proveedores.setObjectName("tabla_proveedores")
        self.tabla_proveedores.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_proveedores.horizontalHeader().setDefaultSectionSize(200)
        self.tabla_proveedores.horizontalHeader().setMinimumSectionSize(150)
        self.tabla_proveedores.horizontalHeader().setStretchLastSection(False)
        self.tabla_proveedores.verticalHeader().setVisible(False)
        self.tabla_proveedores.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.tabla_proveedores, 1, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.contenedor_botones_inferior_derecha = QtWidgets.QWidget(self.contenedor_tablareproveedores)
        self.contenedor_botones_inferior_derecha.setObjectName("contenedor_botones_inferior_derecha")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contenedor_botones_inferior_derecha)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_btn_guardar = QtWidgets.QToolButton(self.contenedor_botones_inferior_derecha)
        self.btn_btn_guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/guardar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_guardar.setIcon(icon3)
        self.btn_btn_guardar.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_guardar.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btn_btn_guardar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_btn_guardar.setAutoRaise(True)
        self.btn_btn_guardar.setArrowType(QtCore.Qt.NoArrow)
        self.btn_btn_guardar.setObjectName("btn_btn_guardar")
        self.horizontalLayout.addWidget(self.btn_btn_guardar)
        self.btn_btn_actualizar = QtWidgets.QPushButton(self.contenedor_botones_inferior_derecha)
        self.btn_btn_actualizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/actualizar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_actualizar.setIcon(icon4)
        self.btn_btn_actualizar.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_actualizar.setObjectName("btn_btn_actualizar")
        self.horizontalLayout.addWidget(self.btn_btn_actualizar)
        self.btn_btn_eliminar = QtWidgets.QToolButton(self.contenedor_botones_inferior_derecha)
        self.btn_btn_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/eliminar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_eliminar.setIcon(icon5)
        self.btn_btn_eliminar.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_eliminar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_btn_eliminar.setObjectName("btn_btn_eliminar")
        self.horizontalLayout.addWidget(self.btn_btn_eliminar)
        self.gridLayout_4.addWidget(self.contenedor_botones_inferior_derecha, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_7.addWidget(self.contenedor_tablareproveedores, 1, 1, 1, 1)
        self.btn_btn_listadeproductoyprecios = QtWidgets.QPushButton(self.contenedor_scroll_area_contenido)
        self.btn_btn_listadeproductoyprecios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_listadeproductoyprecios.setObjectName("btn_btn_listadeproductoyprecios")
        self.gridLayout_7.addWidget(self.btn_btn_listadeproductoyprecios, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.contenedor_scrollArea.setWidget(self.contenedor_scroll_area_contenido)
        self.gridLayout_8.addWidget(self.contenedor_scrollArea, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.contenedor, 1, 0, 1, 1)

        self.retranslateUi(Control_Proveedores)
        QtCore.QMetaObject.connectSlotsByName(Control_Proveedores)
        Control_Proveedores.setTabOrder(self.txt_nombre, self.txt_telefono)
        Control_Proveedores.setTabOrder(self.txt_telefono, self.txt_calles)
        Control_Proveedores.setTabOrder(self.txt_calles, self.txt_colonia)
        Control_Proveedores.setTabOrder(self.txt_colonia, self.txt_estado)
        Control_Proveedores.setTabOrder(self.txt_estado, self.txt_codigopostal)
        Control_Proveedores.setTabOrder(self.txt_codigopostal, self.txt_rfc)
        Control_Proveedores.setTabOrder(self.txt_rfc, self.txt_correo)
        Control_Proveedores.setTabOrder(self.txt_correo, self.txt_avenida)
        Control_Proveedores.setTabOrder(self.txt_avenida, self.txt_ciudad)
        Control_Proveedores.setTabOrder(self.txt_ciudad, self.txt_pais)
        Control_Proveedores.setTabOrder(self.txt_pais, self.txt_web)
        Control_Proveedores.setTabOrder(self.txt_web, self.cajaopciones_categorias)
        Control_Proveedores.setTabOrder(self.cajaopciones_categorias, self.btn_btn_agregarcategoria)
        Control_Proveedores.setTabOrder(self.btn_btn_agregarcategoria, self.btnradio_representantetrue)
        Control_Proveedores.setTabOrder(self.btnradio_representantetrue, self.btnradio_representantefalse)
        Control_Proveedores.setTabOrder(self.btnradio_representantefalse, self.txtlargo_direccionadicional)
        Control_Proveedores.setTabOrder(self.txtlargo_direccionadicional, self.txt_nombrerepresentante)
        Control_Proveedores.setTabOrder(self.txt_nombrerepresentante, self.txt_apellidopaternorepresen)
        Control_Proveedores.setTabOrder(self.txt_apellidopaternorepresen, self.txt_apellidomaternorepresen)
        Control_Proveedores.setTabOrder(self.txt_apellidomaternorepresen, self.txt_puestorepresentante)
        Control_Proveedores.setTabOrder(self.txt_puestorepresentante, self.txt_telefonorepresentante)
        Control_Proveedores.setTabOrder(self.txt_telefonorepresentante, self.txt_correorepresentante)
        Control_Proveedores.setTabOrder(self.txt_correorepresentante, self.txt_buscarproveedor)
        Control_Proveedores.setTabOrder(self.txt_buscarproveedor, self.btn_btn_buscarproveedor)
        Control_Proveedores.setTabOrder(self.btn_btn_buscarproveedor, self.btn_btn_limpiardatos)
        Control_Proveedores.setTabOrder(self.btn_btn_limpiardatos, self.btn_btn_guardar)
        Control_Proveedores.setTabOrder(self.btn_btn_guardar, self.btn_btn_eliminar)
        Control_Proveedores.setTabOrder(self.btn_btn_eliminar, self.txtlargo_descripcioncategoria)

    def retranslateUi(self, Control_Proveedores):
        _translate = QtCore.QCoreApplication.translate
        Control_Proveedores.setWindowTitle(_translate("Control_Proveedores", "Form"))
        self.label_wp_titulo_proveedores.setText(_translate("Control_Proveedores", "REGISTRO DE PROVEEDOR"))
        self.etiqueta_nombrerepresentante.setText(_translate("Control_Proveedores", "Nombre"))
        self.etiqueta_apellidomaternorepresentante.setText(_translate("Control_Proveedores", "Apellido Materno"))
        self.etiqueta_apellidopaternorepresentante.setText(_translate("Control_Proveedores", "Apellido Paterno"))
        self.etiqueta_puestorepresentante.setText(_translate("Control_Proveedores", "Puesto"))
        self.etiqueta_telefonorepresentante.setText(_translate("Control_Proveedores", "Telefono"))
        self.etiqueta_correorepresentante.setText(_translate("Control_Proveedores", "Correo"))
        self.etiqueta_telefono.setText(_translate("Control_Proveedores", "Telefono"))
        self.etiqueta_avenidas.setText(_translate("Control_Proveedores", "Avenida/s"))
        self.etiqueta_direccionadicional.setText(_translate("Control_Proveedores", "Direccion Adiccional"))
        self.etiqueta_colonia.setText(_translate("Control_Proveedores", "Colonia"))
        self.etiqueta_calles.setText(_translate("Control_Proveedores", "Calle/s"))
        self.etiqueta_pais.setText(_translate("Control_Proveedores", "Pais"))
        self.etiqueta_tienerepresentante.setText(_translate("Control_Proveedores", "Tiene representante?"))
        self.btnradio_representantetrue.setText(_translate("Control_Proveedores", "Si"))
        self.btnradio_representantefalse.setText(_translate("Control_Proveedores", "No"))
        self.etiqueta_rfc.setText(_translate("Control_Proveedores", "RFC"))
        self.etiqueta_codigopostal.setText(_translate("Control_Proveedores", "Codigo Postal"))
        self.etiqueta_descripcioncategoria.setText(_translate("Control_Proveedores", "Descripcion Cat."))
        self.etiqueta_web.setText(_translate("Control_Proveedores", "Web"))
        self.etiqueta_estado.setText(_translate("Control_Proveedores", "Estado"))
        self.etiqueta_nombre.setText(_translate("Control_Proveedores", "Nombre"))
        self.etiqueta_categoria.setText(_translate("Control_Proveedores", "Categoria"))
        self.etiqueta_ciudad.setText(_translate("Control_Proveedores", "Ciudad"))
        self.etiqueta_correo.setText(_translate("Control_Proveedores", "Correo"))
        self.etiqueta_moneda.setText(_translate("Control_Proveedores", "Moneda"))
        self.cajaopciones_tipomoneda.setItemText(0, _translate("Control_Proveedores", "MXN: Peso Mexicano."))
        self.cajaopciones_tipomoneda.setItemText(1, _translate("Control_Proveedores", "USD: Dólar estadounidense."))
        self.cajaopciones_tipomoneda.setItemText(2, _translate("Control_Proveedores", "EUR: Euro."))
        self.cajaopciones_tipomoneda.setItemText(3, _translate("Control_Proveedores", "GBP: Libra Esterlina."))
        self.cajaopciones_tipomoneda.setItemText(4, _translate("Control_Proveedores", "JPY: Yen japonés."))
        self.cajaopciones_tipomoneda.setItemText(5, _translate("Control_Proveedores", "CAD: Dólar canadiense."))
        self.cajaopciones_tipomoneda.setItemText(6, _translate("Control_Proveedores", "AUD: Dólar australiano."))
        self.cajaopciones_tipomoneda.setItemText(7, _translate("Control_Proveedores", "CHF: Franco suizo."))
        self.cajaopciones_tipomoneda.setItemText(8, _translate("Control_Proveedores", "CNY: Yuan chino."))
        self.cajaopciones_tipomoneda.setItemText(9, _translate("Control_Proveedores", "BRL: Real brasileño."))
        self.cajaopciones_tipomoneda.setItemText(10, _translate("Control_Proveedores", "ARS: Peso argentino."))
        self.cajaopciones_tipomoneda.setItemText(11, _translate("Control_Proveedores", "CLP: Peso chileno."))
        self.cajaopciones_tipomoneda.setItemText(12, _translate("Control_Proveedores", "COP: Peso colombiano."))
        self.cajaopciones_tipomoneda.setItemText(13, _translate("Control_Proveedores", "PEN: Nuevo sol peruano."))
        self.cajaopciones_tipomoneda.setItemText(14, _translate("Control_Proveedores", "INR: Rupia india."))
        self.cajaopciones_tipomoneda.setItemText(15, _translate("Control_Proveedores", "KRW: Won surcoreano."))
        self.etiquetaTitulo_proveedor.setText(_translate("Control_Proveedores", "Lista de proveedores"))
        self.txt_buscarproveedor.setPlaceholderText(_translate("Control_Proveedores", "Nombre del proveedor"))
        self.btn_btn_guardar.setText(_translate("Control_Proveedores", "GUARDAR"))
        self.btn_btn_actualizar.setText(_translate("Control_Proveedores", "ACTUALIZAR"))
        self.btn_btn_eliminar.setText(_translate("Control_Proveedores", "ELIMINAR"))
        self.btn_btn_listadeproductoyprecios.setText(_translate("Control_Proveedores", "Lista de Productos y Precios"))
import ibootstrap_rc
import iconosSVG_rc
import iconsdvg_rc
