# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\Microsoft\software-punto-de-venta\app\View\UserInterfaceUi\UI_CREAR_ORDEN_DE_COMPRA.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Orden_compra(object):
    def setupUi(self, Orden_compra):
        Orden_compra.setObjectName("Orden_compra")
        Orden_compra.resize(600, 556)
        Orden_compra.setMinimumSize(QtCore.QSize(600, 556))
        Orden_compra.setMaximumSize(QtCore.QSize(600, 556))
        Orden_compra.setStyleSheet("#Orden_compra{\n"
"background-color: #fffefb;\n"
"}\n"
"#contenedor_encabezado{\n"
"background-color: rgb(3, 51, 116);\n"
"height: 30px;\n"
"}\n"
"#label_wc_titulo_ordencompra{\n"
"color: #fffefb;\n"
"font-size: 18px;\n"
"font-weight:bold;\n"
"font-family:\"Arial\";\n"
"}\n"
"[objectName*=\"frame\"]{\n"
"background-color: #fffefb;\n"
"}\n"
"*[objectName*=\"etiqueta_\"]{\n"
"font-family: Arial;\n"
"font-size: 14px;\n"
"font-weight:bold;\n"
"}\n"
"*[objectName*=\"btn_btn_\"]{\n"
"background: #00619a;\n"
"font-size: 14px;\n"
"font-family: Arial;\n"
"font-weight: bold;\n"
"min-height: 25px;\n"
"border: none;\n"
"border-radius: 5px;\n"
"color: #fffefb;\n"
"padding: 3px 5px;\n"
"}\n"
"*[objectName*=\"btn_btn_agregar\"]{\n"
"background-color: #00619a;\n"
"}\n"
"*[objectName*=\"btn_btn_\"]:hover{\n"
"background-color: #59a5f5;\n"
"}\n"
"#btn_btn_agregar:hover{\n"
"background-color: #68a67d;\n"
"}\n"
"#btn_btn_terminar:hover{\n"
"background-color: #68a67d;\n"
"}\n"
"#btn_btn_cerrar{\n"
"background-color: #fffefb;\n"
"min-height:15px;\n"
"max-width:15px;\n"
"}\n"
"#btn_btn_cerrar:pressed{\n"
"background: rgb(222, 221, 218);\n"
"}\n"
"*[objectName*=\"txt_\"]{\n"
"background-color:#F5F5F5;\n"
"color: #1d1c1c;\n"
"border: none;\n"
"border-bottom: 1px solid;\n"
"border-radius: 5px;\n"
"font-size: 12px;\n"
"font-family: Arial;\n"
"}\n"
"*[objectName^=\"txt_\"]::focus{\n"
"border-bottom: 2px solid #00668c;\n"
"}\n"
"*[objectName*=\"numerodecimal_\"]{\n"
"background-color: #F5F5F5;\n"
"color: #1d1c1c;\n"
"border: none;\n"
"border-bottom: 1px solid;\n"
"border-radius: 5px;\n"
"font-size: 14px;\n"
"font-family: Arial;\n"
"}\n"
"*[objectName^=\"numerodecimal_\"]::focus{\n"
"border-bottom: 2px solid #00668c;\n"
"}\n"
"/*TABLA*/\n"
"\n"
"[objectName*=\"tabla_\"] {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Encabezados de la tabla */\n"
"[objectName*=\"tabla_\"] QHeaderView::section {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"    font-family: \"Arial\";\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"/* Encabezado horizontal */\n"
"[objectName*=\"tabla_\"] QHeaderView::horizontal {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Encabezado vertical */\n"
"[objectName*=\"tabla_\"] QHeaderView::vertical {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Orden_compra)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Orden_compra)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.contenedor_encabezado = QtWidgets.QFrame(self.frame)
        self.contenedor_encabezado.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_encabezado.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_encabezado.setObjectName("contenedor_encabezado")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contenedor_encabezado)
        self.horizontalLayout.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_wc_titulo_ordencompra = QtWidgets.QLabel(self.contenedor_encabezado)
        self.label_wc_titulo_ordencompra.setMinimumSize(QtCore.QSize(0, 0))
        self.label_wc_titulo_ordencompra.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_wc_titulo_ordencompra.setObjectName("label_wc_titulo_ordencompra")
        self.horizontalLayout.addWidget(self.label_wc_titulo_ordencompra)
        spacerItem = QtWidgets.QSpacerItem(411, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_btn_cerrar = QtWidgets.QPushButton(self.contenedor_encabezado)
        self.btn_btn_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_cerrar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/x-lg.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_cerrar.setIcon(icon)
        self.btn_btn_cerrar.setObjectName("btn_btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_btn_cerrar)
        self.gridLayout_4.addWidget(self.contenedor_encabezado, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_btn_productosProveedor = QtWidgets.QPushButton(self.frame_4)
        self.btn_btn_productosProveedor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_productosProveedor.setObjectName("btn_btn_productosProveedor")
        self.horizontalLayout_2.addWidget(self.btn_btn_productosProveedor)
        spacerItem1 = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_btn_terminar = QtWidgets.QToolButton(self.frame_4)
        self.btn_btn_terminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_terminar.setObjectName("btn_btn_terminar")
        self.horizontalLayout_2.addWidget(self.btn_btn_terminar)
        self.gridLayout_4.addWidget(self.frame_4, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_buscarproveedor = QtWidgets.QLineEdit(self.frame_2)
        self.txt_buscarproveedor.setObjectName("txt_buscarproveedor")
        self.gridLayout_2.addWidget(self.txt_buscarproveedor, 0, 1, 1, 1)
        self.etiqueta_proveedor = QtWidgets.QLabel(self.frame_2)
        self.etiqueta_proveedor.setTextFormat(QtCore.Qt.AutoText)
        self.etiqueta_proveedor.setObjectName("etiqueta_proveedor")
        self.gridLayout_2.addWidget(self.etiqueta_proveedor, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_3.setHorizontalSpacing(5)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.etiqueta_codigobarras = QtWidgets.QLabel(self.frame_3)
        self.etiqueta_codigobarras.setObjectName("etiqueta_codigobarras")
        self.gridLayout_3.addWidget(self.etiqueta_codigobarras, 0, 0, 1, 1)
        self.txt_buscarproducto = QtWidgets.QLineEdit(self.frame_3)
        self.txt_buscarproducto.setObjectName("txt_buscarproducto")
        self.gridLayout_3.addWidget(self.txt_buscarproducto, 0, 1, 1, 1)
        self.btn_btn_agregar = QtWidgets.QToolButton(self.frame_3)
        self.btn_btn_agregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_agregar.setObjectName("btn_btn_agregar")
        self.gridLayout_3.addWidget(self.btn_btn_agregar, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 4, 0, 1, 1)
        self.tabla_ordencompra = QtWidgets.QTableView(self.frame)
        self.tabla_ordencompra.setObjectName("tabla_ordencompra")
        self.gridLayout_4.addWidget(self.tabla_ordencompra, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Orden_compra)
        QtCore.QMetaObject.connectSlotsByName(Orden_compra)

    def retranslateUi(self, Orden_compra):
        _translate = QtCore.QCoreApplication.translate
        Orden_compra.setWindowTitle(_translate("Orden_compra", "Form"))
        self.label_wc_titulo_ordencompra.setText(_translate("Orden_compra", "orden de compra"))
        self.btn_btn_productosProveedor.setText(_translate("Orden_compra", "Productos del proveedor"))
        self.btn_btn_terminar.setText(_translate("Orden_compra", "Terminar"))
        self.txt_buscarproveedor.setPlaceholderText(_translate("Orden_compra", "Buscar por nombre"))
        self.etiqueta_proveedor.setText(_translate("Orden_compra", "Proveedor"))
        self.etiqueta_codigobarras.setText(_translate("Orden_compra", "Codigo del producto"))
        self.btn_btn_agregar.setText(_translate("Orden_compra", "Agregar"))
import ibootstrap_rc
