# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\Microsoft\software-punto-de-venta\app\View\UserInterfaceUi\UI_CONTROL_EMPLEADOS.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Control_empleados(object):
    def setupUi(self, Control_empleados):
        Control_empleados.setObjectName("Control_empleados")
        Control_empleados.resize(840, 709)
        Control_empleados.setStyleSheet("#Control_empleados{\n"
"background-color: #fffefb;\n"
"}\n"
"#panel_controles{\n"
"margin-bottom:20px;\n"
"}\n"
"[objectName*=\"contenedor\"]{\n"
"background-color: #fffefb;\n"
"}\n"
"#label_we_titulo_empleado{\n"
"color:#1d1c1c;\n"
"background-color: #fffefb;\n"
"font-size: 24px;\n"
"font-weight: bold;\n"
"padding-left: 5px;\n"
"text-transform: uppercase;\n"
"font-family: \"Arial\";\n"
"padding-top: 5px;\n"
"}\n"
"#tabla_listaempleados {\n"
"    border: 1px solid;\n"
"    background: #fffefb;\n"
"}\n"
"*[objectName*=\"etiqueta\"]{\n"
"font-family: Arial;\n"
"margin-left: 5px;\n"
"margin-right: 5px;\n"
"font-size: 16px;\n"
"font-weight:bold;\n"
"text-transform: uppercase;\n"
"}\n"
"*[objectName*=\"txt_\"]{\n"
"background-color: #F5F5F5;\n"
"color:#1d1c1c;\n"
"border: none;\n"
"border-bottom: 1px solid;\n"
"border-radius: 5px;\n"
"font-size: 16px;\n"
"font-family: Arial;\n"
"height: 20px;\n"
"}\n"
"*[objectName^=\"txt_\"]::focus{\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"*[objectName*=\"btn_btn\"]{\n"
"border:none;\n"
"border-radius: 3px;\n"
"background-color: #00619a;\n"
"font-family: Arial;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"text-align: center;\n"
"text-transform: uppercase;\n"
"color: #fffefb;\n"
"padding:2px;\n"
"}\n"
"\n"
"[objectName*=\"btn_btn\"]:hover{\n"
"background-color: #2196F3;\n"
"}\n"
"#btn_btn_eliminar:hover{\n"
"background-color:#EE1D52;\n"
"}\n"
"#btn_btn_agregar:hover{\n"
"background-color: #68a67d;\n"
"}\n"
"#btn_RefrescarTabla{\n"
"border-radius: 2px;\n"
"background: #e0e0e0;\n"
"padding: 5px;\n"
"}\n"
"#btn_RefrescarTabla:hover{\n"
"background: rgb(179, 179, 179);\n"
"}\n"
"#btn_RefrescarTabla:pressed{\n"
"background: #b6ccd8 ;\n"
"}\n"
"[objectName^=\"cajaopciones_\"]{\n"
"border: none;\n"
"border-bottom: 1px solid rgb(29, 28, 28);\n"
"borde-radius: 5px;\n"
"padding: 2px;\n"
"background-color: #f5f4f1;\n"
"borde-radius: 5px;\n"
"font-size: 12px;\n"
"min-width:87px;\n"
"}\n"
"[objectName*=\"cajaopciones_\"]::drop-down{\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: top right;\n"
"padding-right:5px;\n"
"width: 20%;\n"
"border-left-width: 1px;\n"
"borde-radius: 5px;\n"
"background-color: #f5f4f1;\n"
"}\n"
"[objectName*=\"cajaopciones_\"]::down-arrow{\n"
"image: url(:/Icons/Bootstrap/filter-left.svg);\n"
"width: 17%;\n"
"height: 17%;\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}\n"
"/*TABLA*/\n"
"\n"
"[objectName*=\"tabla_\"] {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    background: #fffefb;\n"
"}\n"
"\n"
"/* Encabezados de la tabla */\n"
"[objectName*=\"tabla_\"] QHeaderView::section {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"    font-family: \"Arial\";\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"/* Encabezado horizontal */\n"
"[objectName*=\"tabla_\"] QHeaderView::horizontal {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Encabezado vertical */\n"
"[objectName*=\"tabla_\"] QHeaderView::vertical {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Control_empleados)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_we_titulo_empleado = QtWidgets.QLabel(Control_empleados)
        self.label_we_titulo_empleado.setMinimumSize(QtCore.QSize(0, 40))
        self.label_we_titulo_empleado.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_we_titulo_empleado.setObjectName("label_we_titulo_empleado")
        self.gridLayout.addWidget(self.label_we_titulo_empleado, 0, 0, 1, 1)
        self.contenedor = QtWidgets.QFrame(Control_empleados)
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.contenedor)
        self.gridLayout_5.setContentsMargins(5, 0, 5, 5)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.contenedor_cuerpo = QtWidgets.QWidget(self.contenedor)
        self.contenedor_cuerpo.setMinimumSize(QtCore.QSize(0, 0))
        self.contenedor_cuerpo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.contenedor_cuerpo.setObjectName("contenedor_cuerpo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.contenedor_cuerpo)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.contenedor_botones = QtWidgets.QWidget(self.contenedor_cuerpo)
        self.contenedor_botones.setObjectName("contenedor_botones")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contenedor_botones)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_btn_agregar = QtWidgets.QToolButton(self.contenedor_botones)
        self.btn_btn_agregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/agregar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_agregar.setIcon(icon)
        self.btn_btn_agregar.setIconSize(QtCore.QSize(16, 16))
        self.btn_btn_agregar.setAutoRepeat(False)
        self.btn_btn_agregar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_btn_agregar.setObjectName("btn_btn_agregar")
        self.horizontalLayout.addWidget(self.btn_btn_agregar)
        self.btn_btn_eliminar = QtWidgets.QToolButton(self.contenedor_botones)
        self.btn_btn_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/eliminar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_eliminar.setIcon(icon1)
        self.btn_btn_eliminar.setIconSize(QtCore.QSize(16, 16))
        self.btn_btn_eliminar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_btn_eliminar.setObjectName("btn_btn_eliminar")
        self.horizontalLayout.addWidget(self.btn_btn_eliminar)
        self.btn_btn_editarempleado = QtWidgets.QPushButton(self.contenedor_botones)
        self.btn_btn_editarempleado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/editar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_editarempleado.setIcon(icon2)
        self.btn_btn_editarempleado.setIconSize(QtCore.QSize(19, 19))
        self.btn_btn_editarempleado.setObjectName("btn_btn_editarempleado")
        self.horizontalLayout.addWidget(self.btn_btn_editarempleado)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_RefrescarTabla = QtWidgets.QToolButton(self.contenedor_botones)
        self.btn_RefrescarTabla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_RefrescarTabla.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/IconosSVG/base_datos_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_RefrescarTabla.setIcon(icon3)
        self.btn_RefrescarTabla.setIconSize(QtCore.QSize(16, 16))
        self.btn_RefrescarTabla.setObjectName("btn_RefrescarTabla")
        self.horizontalLayout.addWidget(self.btn_RefrescarTabla, 0, QtCore.Qt.AlignVCenter)
        self.gridLayout_2.addWidget(self.contenedor_botones, 1, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.tabla_listaempleados = QtWidgets.QTableView(self.contenedor_cuerpo)
        self.tabla_listaempleados.setMinimumSize(QtCore.QSize(0, 0))
        self.tabla_listaempleados.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabla_listaempleados.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tabla_listaempleados.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tabla_listaempleados.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_listaempleados.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_listaempleados.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_listaempleados.setShowGrid(True)
        self.tabla_listaempleados.setGridStyle(QtCore.Qt.DashDotLine)
        self.tabla_listaempleados.setObjectName("tabla_listaempleados")
        self.tabla_listaempleados.horizontalHeader().setDefaultSectionSize(200)
        self.tabla_listaempleados.horizontalHeader().setMinimumSectionSize(200)
        self.gridLayout_2.addWidget(self.tabla_listaempleados, 3, 0, 1, 1)
        self.contenedor_cabeceraopcionbusqueda = QtWidgets.QFrame(self.contenedor_cuerpo)
        self.contenedor_cabeceraopcionbusqueda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_cabeceraopcionbusqueda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_cabeceraopcionbusqueda.setObjectName("contenedor_cabeceraopcionbusqueda")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.contenedor_cabeceraopcionbusqueda)
        self.gridLayout_4.setContentsMargins(5, 10, 5, 5)
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_btn_buscar = QtWidgets.QToolButton(self.contenedor_cabeceraopcionbusqueda)
        self.btn_btn_buscar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_btn_buscar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_buscar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/buscar_persona_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_buscar.setIcon(icon4)
        self.btn_btn_buscar.setIconSize(QtCore.QSize(18, 18))
        self.btn_btn_buscar.setObjectName("btn_btn_buscar")
        self.gridLayout_4.addWidget(self.btn_btn_buscar, 1, 3, 1, 1, QtCore.Qt.AlignVCenter)
        self.txt_nombreempleado = QtWidgets.QLineEdit(self.contenedor_cabeceraopcionbusqueda)
        self.txt_nombreempleado.setObjectName("txt_nombreempleado")
        self.gridLayout_4.addWidget(self.txt_nombreempleado, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 4, 1, 1)
        self.txt_idempleado = QtWidgets.QLineEdit(self.contenedor_cabeceraopcionbusqueda)
        self.txt_idempleado.setObjectName("txt_idempleado")
        self.gridLayout_4.addWidget(self.txt_idempleado, 1, 0, 1, 1)
        self.cajaopciones_filtroNombreEmpleado = QtWidgets.QComboBox(self.contenedor_cabeceraopcionbusqueda)
        self.cajaopciones_filtroNombreEmpleado.setObjectName("cajaopciones_filtroNombreEmpleado")
        self.cajaopciones_filtroNombreEmpleado.addItem("")
        self.cajaopciones_filtroNombreEmpleado.addItem("")
        self.gridLayout_4.addWidget(self.cajaopciones_filtroNombreEmpleado, 1, 1, 1, 1)
        self.etiqueta_buscar = QtWidgets.QLabel(self.contenedor_cabeceraopcionbusqueda)
        self.etiqueta_buscar.setObjectName("etiqueta_buscar")
        self.gridLayout_4.addWidget(self.etiqueta_buscar, 0, 0, 1, 5)
        self.gridLayout_2.addWidget(self.contenedor_cabeceraopcionbusqueda, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.contenedor_cuerpo, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.contenedor, 1, 0, 1, 1)

        self.retranslateUi(Control_empleados)
        QtCore.QMetaObject.connectSlotsByName(Control_empleados)

    def retranslateUi(self, Control_empleados):
        _translate = QtCore.QCoreApplication.translate
        Control_empleados.setWindowTitle(_translate("Control_empleados", "Form"))
        self.label_we_titulo_empleado.setText(_translate("Control_empleados", "ADMINISTRACIÓN DE EMPLEADOS"))
        self.btn_btn_agregar.setToolTip(_translate("Control_empleados", "Agregar empleado"))
        self.btn_btn_agregar.setText(_translate("Control_empleados", "Agregar"))
        self.btn_btn_eliminar.setToolTip(_translate("Control_empleados", "Eliminar empleado"))
        self.btn_btn_eliminar.setText(_translate("Control_empleados", "Eliminar"))
        self.btn_btn_editarempleado.setToolTip(_translate("Control_empleados", "Editar empleado"))
        self.btn_btn_editarempleado.setText(_translate("Control_empleados", "EDItar"))
        self.btn_RefrescarTabla.setToolTip(_translate("Control_empleados", "Actualizar tabla"))
        self.btn_btn_buscar.setToolTip(_translate("Control_empleados", "Buscar empleado"))
        self.txt_nombreempleado.setPlaceholderText(_translate("Control_empleados", "Nombre de empleado"))
        self.txt_idempleado.setPlaceholderText(_translate("Control_empleados", "Id del empleado"))
        self.cajaopciones_filtroNombreEmpleado.setItemText(0, _translate("Control_empleados", "IGUAL A"))
        self.cajaopciones_filtroNombreEmpleado.setItemText(1, _translate("Control_empleados", "QUE CONTENGA"))
        self.etiqueta_buscar.setText(_translate("Control_empleados", "Filtros de Busqueda:"))
import ibootstrap_rc
import iconosSVG_rc
