# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\LUIS_ANGEL_VALLEJO\software-punto-de-venta\app\View\UserInterfaceUi\UI_CONTROL_COMPRAS.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_control_compras(object):
    def setupUi(self, control_compras):
        control_compras.setObjectName("control_compras")
        control_compras.resize(1148, 610)
        control_compras.setStyleSheet("#Control_empleados{\n"
"background-color: #fffefb;\n"
"}\n"
"[objectName*=\"contenedor\"]{\n"
"background-color: #fffefb;\n"
"}\n"
"#panel_controles{\n"
"margin-bottom:20px;\n"
"}\n"
"#label_wc_titulo_compras{\n"
"background-color: rgb(3, 51, 116);\n"
"color:#fffefb;\n"
"font-size: 24px;\n"
"font-weight: bold;\n"
"padding-left: 5px;\n"
"text-transform: uppercase;\n"
"}\n"
"#tabla_listaempleados {\n"
"    border: 1px solid;\n"
"    background: #fffefb;\n"
"    max-height: 600px;\n"
"    font-family:  \'Times New Roman\';\n"
"}\n"
"#contenedortabglobal{\n"
"background-color: #fffefb;\n"
"}\n"
"#contenedortab_comprasrealizadas{\n"
"background-color: #fffefb;\n"
"border: 1px solid;\n"
"}\n"
"#contenedortab_compraspendientes{\n"
"background-color: #fffefb;\n"
"border: 1px solid;\n"
"}\n"
"[objectName*=\"etiquetaTitulo\"]{\n"
"font-family: Arial;\n"
"margin-left: 5px;\n"
"margin-right: 5px;\n"
"font-size: 16px;\n"
"font-weight:bold;\n"
"text-transform: uppercase;\n"
"color: #1d1c1c;\n"
"}\n"
"*[objectName*=\"etiqueta_\"]{\n"
"font-family: Arial;\n"
"margin-left: 5px;\n"
"margin-right: 5px;\n"
"font-size: 14px;\n"
"font-weight:bold;\n"
"text-transform: capitalize;\n"
"color: #1d1c1c;\n"
"}\n"
"*[objectName*=\"txt_\"]{\n"
"background-color: #F5F5F5;\n"
"color: #1d1c1c;\n"
"border: none;\n"
"border-bottom: 1px solid;\n"
"border-radius: 5px;\n"
"font-size: 16px;\n"
"font-family: Arial;\n"
"height: 20px;\n"
"}\n"
"#txt_proveedor{\n"
"width: 350px;\n"
"font-family: Arial;\n"
"color: #1d1c1c\n"
"}\n"
"#cajaopciones_proveedor{\n"
"width: 250px;\n"
"max-width: 250px;\n"
"font-family: Arial;\n"
"background-color: #F5F5F5;\n"
"color: #1d1c1c;\n"
"}\n"
"*[objectName^=\"txt_\"]::focus{\n"
"border-bottom: 2px solid #00668c;\n"
"}\n"
"*[objectName*=\"btn_btn\"]{\n"
"border:none;\n"
"border-radius: 5px;\n"
"background-color: #00619a;\n"
"color: #fffefb;\n"
"font-family: Arial;\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"height: 25px;\n"
"margin-left: 5px;\n"
"margin-right: 5px;\n"
"text-align: center;\n"
"text-transform: uppercase;\n"
"}\n"
"#btn_btn_eliminar:hover{\n"
"background-color: #EE1D52;\n"
"}\n"
"#btn_btn_agregar:hover{\n"
"background-color: #68a67d;\n"
"}\n"
"*[objectName*=\"btn_btn\"]:hover{\n"
"background-color: #4d648d;\n"
"}\n"
"/*-----------TABLA--------------*/\n"
"\n"
"\n"
"[objectName*=\"tabla_\"] {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Barra vertical */\n"
"[objectName*=\"tabla_\"] QScrollBar:vertical {\n"
"    border: 1px solid gray;\n"
"    background: #023375;\n"
"    width: 12px;  /* Fijamos el tamaño de la barra vertical */\n"
"    border-radius: 4px;\n"
"    margin: 22px 0 22px 0;\n"
"}\n"
"\n"
"/* Manejador de la barra vertical */\n"
"[objectName*=\"tabla_\"] QScrollBar::handle:vertical {\n"
"    background: #023375;\n"
"    min-height: 20px;  /* Altura mínima del manejador */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Elementos de la flecha de la barra vertical */\n"
"[objectName*=\"tabla_\"] QScrollBar::add-line:vertical,\n"
"[objectName*=\"tabla_\"] QScrollBar::sub-line:vertical {\n"
"    background-color: none;\n"
"}\n"
"\n"
"/* Barra horizontal */\n"
"[objectName*=\"tabla_\"] QScrollBar:horizontal {\n"
"    background: #023375;\n"
"    height: 12px;  /* Fijamos el tamaño de la barra horizontal */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Manejador de la barra horizontal */\n"
"[objectName*=\"tabla_\"] QScrollBar::handle:horizontal {\n"
"    background: #023375;\n"
"    height: 12px;  /* Altura del manejador horizontal */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Encabezados de la tabla */\n"
"[objectName*=\"tabla_\"] QHeaderView::section {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"    font-family: \"Arial\";\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"/* Encabezado horizontal */\n"
"[objectName*=\"tabla_\"] QHeaderView::horizontal {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Encabezado vertical */\n"
"[objectName*=\"tabla_\"] QHeaderView::vertical {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"\n"
"/*-----------FECHA--------------*/\n"
"[objectName^=\"fecha_\"]{\n"
"border: none;\n"
"border-bottom: 1px solid #3b3c3d;\n"
"border-radius: 5px;\n"
"padding: 2px;\n"
"background-color: #f5f4f1;\n"
"font-size: 14px;\n"
"width:150px;\n"
"max-width:150px;\n"
"font-family: Arial;\n"
"color: #1d1c1c;\n"
"\n"
"}\n"
"*[objectName^=\"fecha_\"]::drop-down{\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: top right;\n"
"padding-right:5px;\n"
"width: 20%;\n"
"border-left-width: 1px;\n"
"border-radius: 5px;\n"
"background-color: #F5F5F5;\n"
"}\n"
"*[objectName^=\"fecha_\"]::down-arrow{\n"
"image: url(:/Icons/Bootstrap/calendar2-date.svg);\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}\n"
"*[objectName^=\"fecha_\"]::focus{\n"
"border-bottom: 2px solid #00668c;\n"
"}\n"
"/*----------CAJA OPCIONES---------------*/\n"
"[objectName^=\"cajaopciones_\"]{\n"
"border: none;\n"
"border-bottom: 1px solid rgb(29, 28, 28);\n"
"border-radius: 5px;\n"
"padding: 2px;\n"
"background-color: #F5F5F5;\n"
"border-radius: 5px;\n"
"font-size: 12px;\n"
"width:87px;\n"
"color: #1d1c1c;\n"
"}\n"
"[objectName^=\"cajaopciones_\"]::drop-down{\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: top right;\n"
"padding-right:5px;\n"
"border-left-width: 1px;\n"
"border-radius: 5px;\n"
"background-color:#F5F5F5;\n"
"}\n"
"[objectName^=\"cajaopciones_\"]::down-arrow{\n"
"image: url(:/Icons/Bootstrap/filter-left.svg);\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(control_compras)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_wc_titulo_compras = QtWidgets.QLabel(control_compras)
        self.label_wc_titulo_compras.setMinimumSize(QtCore.QSize(0, 40))
        self.label_wc_titulo_compras.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_wc_titulo_compras.setObjectName("label_wc_titulo_compras")
        self.gridLayout.addWidget(self.label_wc_titulo_compras, 0, 0, 1, 1)
        self.contenedor_principal = QtWidgets.QFrame(control_compras)
        self.contenedor_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_principal.setObjectName("contenedor_principal")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.contenedor_principal)
        self.gridLayout_6.setContentsMargins(5, 0, 5, 5)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.contenedortabglobal = QtWidgets.QTabWidget(self.contenedor_principal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.contenedortabglobal.setFont(font)
        self.contenedortabglobal.setStyleSheet("")
        self.contenedortabglobal.setIconSize(QtCore.QSize(14, 14))
        self.contenedortabglobal.setObjectName("contenedortabglobal")
        self.contenedortab_comprasrealizadas = QtWidgets.QWidget()
        self.contenedortab_comprasrealizadas.setObjectName("contenedortab_comprasrealizadas")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.contenedortab_comprasrealizadas)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget = QtWidgets.QWidget(self.contenedortab_comprasrealizadas)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.contenedor_contenido = QtWidgets.QFrame(self.widget)
        self.contenedor_contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_contenido.setObjectName("contenedor_contenido")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.contenedor_contenido)
        self.gridLayout_4.setContentsMargins(5, 10, 5, 0)
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setVerticalSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.etiqueta_proveedor_2 = QtWidgets.QLabel(self.contenedor_contenido)
        self.etiqueta_proveedor_2.setObjectName("etiqueta_proveedor_2")
        self.gridLayout_4.addWidget(self.etiqueta_proveedor_2, 4, 3, 1, 1)
        self.cajaopciones_proveedor = QtWidgets.QComboBox(self.contenedor_contenido)
        self.cajaopciones_proveedor.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cajaopciones_proveedor.setObjectName("cajaopciones_proveedor")
        self.gridLayout_4.addWidget(self.cajaopciones_proveedor, 6, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 3, 9, 1, 1)
        self.txt_proveedor = QtWidgets.QLineEdit(self.contenedor_contenido)
        self.txt_proveedor.setObjectName("txt_proveedor")
        self.gridLayout_4.addWidget(self.txt_proveedor, 3, 3, 1, 1)
        self.txt_idcompra = QtWidgets.QLineEdit(self.contenedor_contenido)
        self.txt_idcompra.setObjectName("txt_idcompra")
        self.gridLayout_4.addWidget(self.txt_idcompra, 3, 0, 1, 3)
        self.etiquetaTitulo_buscar = QtWidgets.QLabel(self.contenedor_contenido)
        self.etiquetaTitulo_buscar.setObjectName("etiquetaTitulo_buscar")
        self.gridLayout_4.addWidget(self.etiquetaTitulo_buscar, 0, 0, 1, 2)
        self.btn_btn_buscar = QtWidgets.QToolButton(self.contenedor_contenido)
        self.btn_btn_buscar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/buscar_filas_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_buscar.setIcon(icon)
        self.btn_btn_buscar.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_buscar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_btn_buscar.setObjectName("btn_btn_buscar")
        self.gridLayout_4.addWidget(self.btn_btn_buscar, 3, 10, 1, 1)
        self.fecha_fechacompra = QtWidgets.QDateEdit(self.contenedor_contenido)
        self.fecha_fechacompra.setAlignment(QtCore.Qt.AlignCenter)
        self.fecha_fechacompra.setCalendarPopup(True)
        self.fecha_fechacompra.setObjectName("fecha_fechacompra")
        self.gridLayout_4.addWidget(self.fecha_fechacompra, 6, 0, 1, 2)
        self.etiqueta_fechacompra = QtWidgets.QLabel(self.contenedor_contenido)
        self.etiqueta_fechacompra.setObjectName("etiqueta_fechacompra")
        self.gridLayout_4.addWidget(self.etiqueta_fechacompra, 4, 0, 1, 2)
        self.etiqueta_fechalevantamientocompra = QtWidgets.QLabel(self.contenedor_contenido)
        self.etiqueta_fechalevantamientocompra.setObjectName("etiqueta_fechalevantamientocompra")
        self.gridLayout_4.addWidget(self.etiqueta_fechalevantamientocompra, 4, 2, 1, 1)
        self.fecha_levantamientocompra = QtWidgets.QDateEdit(self.contenedor_contenido)
        self.fecha_levantamientocompra.setAlignment(QtCore.Qt.AlignCenter)
        self.fecha_levantamientocompra.setCalendarPopup(True)
        self.fecha_levantamientocompra.setObjectName("fecha_levantamientocompra")
        self.gridLayout_4.addWidget(self.fecha_levantamientocompra, 6, 2, 1, 1)
        self.gridLayout_2.addWidget(self.contenedor_contenido, 0, 0, 1, 1)
        self.tabla_comprasrealizadas = QtWidgets.QTableView(self.widget)
        self.tabla_comprasrealizadas.setObjectName("tabla_comprasrealizadas")
        self.gridLayout_2.addWidget(self.tabla_comprasrealizadas, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/check-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contenedortabglobal.addTab(self.contenedortab_comprasrealizadas, icon1, "")
        self.contenedortab_compraspendientes = QtWidgets.QWidget()
        self.contenedortab_compraspendientes.setObjectName("contenedortab_compraspendientes")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.contenedortab_compraspendientes)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.contenedortab_compraspendientes)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.contenedor_contenidocompras_pendientes = QtWidgets.QFrame(self.widget_2)
        self.contenedor_contenidocompras_pendientes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_contenidocompras_pendientes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_contenidocompras_pendientes.setObjectName("contenedor_contenidocompras_pendientes")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.contenedor_contenidocompras_pendientes)
        self.gridLayout_8.setContentsMargins(5, 10, 5, 0)
        self.gridLayout_8.setHorizontalSpacing(10)
        self.gridLayout_8.setVerticalSpacing(5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.txt_idcompra_2 = QtWidgets.QLineEdit(self.contenedor_contenidocompras_pendientes)
        self.txt_idcompra_2.setObjectName("txt_idcompra_2")
        self.gridLayout_8.addWidget(self.txt_idcompra_2, 3, 0, 1, 2)
        self.txt_proveedor_2 = QtWidgets.QLineEdit(self.contenedor_contenidocompras_pendientes)
        self.txt_proveedor_2.setObjectName("txt_proveedor_2")
        self.gridLayout_8.addWidget(self.txt_proveedor_2, 3, 2, 1, 1)
        self.fecha_fechacompra_2 = QtWidgets.QDateEdit(self.contenedor_contenidocompras_pendientes)
        self.fecha_fechacompra_2.setAlignment(QtCore.Qt.AlignCenter)
        self.fecha_fechacompra_2.setCalendarPopup(True)
        self.fecha_fechacompra_2.setObjectName("fecha_fechacompra_2")
        self.gridLayout_8.addWidget(self.fecha_fechacompra_2, 5, 0, 1, 1)
        self.cajaopciones_proveedor_2 = QtWidgets.QComboBox(self.contenedor_contenidocompras_pendientes)
        self.cajaopciones_proveedor_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cajaopciones_proveedor_2.setObjectName("cajaopciones_proveedor_2")
        self.gridLayout_8.addWidget(self.cajaopciones_proveedor_2, 5, 2, 1, 1)
        self.etiquetaTitulo_buscar_2 = QtWidgets.QLabel(self.contenedor_contenidocompras_pendientes)
        self.etiquetaTitulo_buscar_2.setObjectName("etiquetaTitulo_buscar_2")
        self.gridLayout_8.addWidget(self.etiquetaTitulo_buscar_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 3, 8, 1, 1)
        self.btn_btn_buscar_2 = QtWidgets.QToolButton(self.contenedor_contenidocompras_pendientes)
        self.btn_btn_buscar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_buscar_2.setIcon(icon)
        self.btn_btn_buscar_2.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_buscar_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_btn_buscar_2.setObjectName("btn_btn_buscar_2")
        self.gridLayout_8.addWidget(self.btn_btn_buscar_2, 3, 9, 1, 1)
        self.etiqueta_levantamientocompra = QtWidgets.QLabel(self.contenedor_contenidocompras_pendientes)
        self.etiqueta_levantamientocompra.setObjectName("etiqueta_levantamientocompra")
        self.gridLayout_8.addWidget(self.etiqueta_levantamientocompra, 4, 0, 1, 1)
        self.etiqueta_proveedor = QtWidgets.QLabel(self.contenedor_contenidocompras_pendientes)
        self.etiqueta_proveedor.setObjectName("etiqueta_proveedor")
        self.gridLayout_8.addWidget(self.etiqueta_proveedor, 4, 2, 1, 1)
        self.gridLayout_7.addWidget(self.contenedor_contenidocompras_pendientes, 0, 0, 1, 1)
        self.tabla_compraspendientes = QtWidgets.QTableView(self.widget_2)
        self.tabla_compraspendientes.setObjectName("tabla_compraspendientes")
        self.gridLayout_7.addWidget(self.tabla_compraspendientes, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.widget_2, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/pause-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contenedortabglobal.addTab(self.contenedortab_compraspendientes, icon2, "")
        self.gridLayout_6.addWidget(self.contenedortabglobal, 1, 0, 1, 2)
        self.panel_controles = QtWidgets.QFrame(self.contenedor_principal)
        self.panel_controles.setMinimumSize(QtCore.QSize(0, 0))
        self.panel_controles.setMaximumSize(QtCore.QSize(16777215, 150))
        self.panel_controles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_controles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_controles.setObjectName("panel_controles")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.panel_controles)
        self.gridLayout_3.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.panel_controles)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_btn_agregar = QtWidgets.QToolButton(self.frame_2)
        self.btn_btn_agregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/agregar_documento_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_agregar.setIcon(icon3)
        self.btn_btn_agregar.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_agregar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_btn_agregar.setObjectName("btn_btn_agregar")
        self.horizontalLayout_2.addWidget(self.btn_btn_agregar)
        self.btn_btn_eliminar = QtWidgets.QToolButton(self.frame_2)
        self.btn_btn_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/eliminar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_eliminar.setIcon(icon4)
        self.btn_btn_eliminar.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_eliminar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_btn_eliminar.setObjectName("btn_btn_eliminar")
        self.horizontalLayout_2.addWidget(self.btn_btn_eliminar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_6.addWidget(self.panel_controles, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.contenedor_principal, 1, 0, 1, 1)

        self.retranslateUi(control_compras)
        self.contenedortabglobal.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(control_compras)

    def retranslateUi(self, control_compras):
        _translate = QtCore.QCoreApplication.translate
        control_compras.setWindowTitle(_translate("control_compras", "Form"))
        self.label_wc_titulo_compras.setText(_translate("control_compras", "administración de compras"))
        self.etiqueta_proveedor_2.setText(_translate("control_compras", "Proveedor"))
        self.txt_proveedor.setPlaceholderText(_translate("control_compras", "Quien realizo la compra"))
        self.txt_idcompra.setPlaceholderText(_translate("control_compras", "folio de la compra"))
        self.etiquetaTitulo_buscar.setText(_translate("control_compras", "Buscar por:"))
        self.btn_btn_buscar.setText(_translate("control_compras", "Buscar"))
        self.etiqueta_fechacompra.setText(_translate("control_compras", "Fecha de compra"))
        self.etiqueta_fechalevantamientocompra.setText(_translate("control_compras", "Fecha documento"))
        self.contenedortabglobal.setTabText(self.contenedortabglobal.indexOf(self.contenedortab_comprasrealizadas), _translate("control_compras", "Realizadas"))
        self.txt_idcompra_2.setPlaceholderText(_translate("control_compras", "folio de la compra"))
        self.txt_proveedor_2.setPlaceholderText(_translate("control_compras", "Quien realizo la compra"))
        self.etiquetaTitulo_buscar_2.setText(_translate("control_compras", "Buscar por:"))
        self.btn_btn_buscar_2.setText(_translate("control_compras", "Buscar"))
        self.etiqueta_levantamientocompra.setText(_translate("control_compras", "Fecha documento"))
        self.etiqueta_proveedor.setText(_translate("control_compras", "Proveedor"))
        self.contenedortabglobal.setTabText(self.contenedortabglobal.indexOf(self.contenedortab_compraspendientes), _translate("control_compras", "Pendientes"))
        self.btn_btn_agregar.setText(_translate("control_compras", "Agregar"))
        self.btn_btn_eliminar.setText(_translate("control_compras", "Eliminar"))
import ibootstrap_rc
import iconosSVG_rc
