# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\Microsoft\software-punto-de-venta\app\View\UserInterfaceUi\UI_CONTROL_DEPARTAMENTOS.ui'
#
# Created by: PySide6 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Control_departamentos(object):
    def setupUi(self, Control_departamentos):
        Control_departamentos.setObjectName("Control_departamentos")
        Control_departamentos.resize(878, 565)
        Control_departamentos.setStyleSheet("#Control_departamentos{\n"
"background: #fffefb;\n"
"}\n"
"[objectName*=\"contenedor\"]{\n"
"background: #fffefb;\n"
"}\n"
"#contenedor_encabezado{\n"
"background: #023375;\n"
"}\n"
"#etiquetaTituloEncabezado{\n"
"color: #fffefb;\n"
"font-size:18px;\n"
"font-weight:bold;\n"
"font-family:Arial;\n"
"}\n"
"[objectName*=\"etiqueta_\"]{\n"
"color: #1d1c1c;\n"
"font-size:14px;\n"
"font-weight:bold;\n"
"font-family:Arial;\n"
"}\n"
"#etiqueta_buscardepartamento{\n"
"max-width:25px;\n"
"max-height:25px;\n"
"width:25px;\n"
"height:25px;\n"
"}\n"
"[objectName*=\"etiquetasubtitulo_\"]{\n"
"color: #1d1c1c;\n"
"font-size:15px;\n"
"font-weight:bold;\n"
"font-family:Arial;\n"
"}\n"
"[objectName*=\"btn_btn_\"]{\n"
"color:#fffefb;\n"
"font-size:14px;\n"
"font-family:Arial;\n"
"font-weight:bold;\n"
"background: #023375;\n"
"border:none;\n"
"border-radius: 5px;\n"
"padding-left:5px;\n"
"padding-right: 5px;\n"
"height:25px;\n"
"margin-left: 3px;\n"
"margin-right:3px;\n"
"}\n"
"[objectName*=\"btn_btn_\"]:hover{\n"
"background: #2196F3;\n"
"}\n"
"#btn_btn_eliminar:hover{\n"
"background:#EE1D52;\n"
"}\n"
"[objectName*=\"txt_\"]{\n"
"background: #F5F5F5;\n"
"font-size: 12px;\n"
"border: none;\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid #1d1c1c;\n"
"font-family:Arial;\n"
"}\n"
"[objectName*=\"txt_\"]:focus{\n"
"background: #F5F5F5;\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"[objectName*=\"txtlargo_\"]{\n"
"background: #F5F5F5;\n"
"font-size: 12px;\n"
"border: none;\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid #1d1c1c;\n"
"font-family:Arial;\n"
"height: 100px;\n"
"max-height: 100px;\n"
"}\n"
"[objectName*=\"txtlargo_\"]:focus{\n"
"background: #F5F5F5;\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"QListWidget {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"/* Barra vertical */\n"
"QListWidget::vertical-scrollbar {\n"
"    border: 1px solid gray;\n"
"    background: #023375;\n"
"    width: 10px;  /* Tamaño de la barra vertical */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Manejador de la barra vertical */\n"
"QListWidget::vertical-scrollbar::handle {\n"
"    background: #023375;  /* Color del \"manejador\" */\n"
"    min-height: 20px;  /* Altura mínima del manejador */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Barra horizontal */\n"
"QListWidget::horizontal-scrollbar {\n"
"    background: #023375;\n"
"    height: 10px;  /* Tamaño de la barra horizontal */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Manejador de la barra horizontal */\n"
"QListWidget::horizontal-scrollbar::handle {\n"
"    background: #023375;  /* Color del \"manejador\" */\n"
"    height: 10px;  /* Altura del manejador horizontal */\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.gridLayout_6 = QtWidgets.QGridLayout(Control_departamentos)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(Control_departamentos)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.contenedor_encabezado = QtWidgets.QFrame(self.frame)
        self.contenedor_encabezado.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_encabezado.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_encabezado.setObjectName("contenedor_encabezado")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contenedor_encabezado)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.etiquetaTituloEncabezado = QtWidgets.QLabel(self.contenedor_encabezado)
        self.etiquetaTituloEncabezado.setObjectName("etiquetaTituloEncabezado")
        self.horizontalLayout.addWidget(self.etiquetaTituloEncabezado)
        spacerItem = QtWidgets.QSpacerItem(692, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_cerrar = QtWidgets.QPushButton(self.contenedor_encabezado)
        self.btn_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cerrar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/x-lg.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon)
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_cerrar)
        self.gridLayout.addWidget(self.contenedor_encabezado, 0, 0, 1, 1)
        self.contenedor = QtWidgets.QFrame(self.frame)
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.contenedor)
        self.gridLayout_2.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_btn_eliminar = QtWidgets.QPushButton(self.contenedor)
        self.btn_btn_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/eliminar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_eliminar.setIcon(icon1)
        self.btn_btn_eliminar.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_eliminar.setObjectName("btn_btn_eliminar")
        self.gridLayout_2.addWidget(self.btn_btn_eliminar, 0, 5, 1, 1)
        self.btn_btn_guardar = QtWidgets.QPushButton(self.contenedor)
        self.btn_btn_guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/guardar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_guardar.setIcon(icon2)
        self.btn_btn_guardar.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_guardar.setObjectName("btn_btn_guardar")
        self.gridLayout_2.addWidget(self.btn_btn_guardar, 0, 3, 1, 1)
        self.btn_btn_actualizar = QtWidgets.QPushButton(self.contenedor)
        self.btn_btn_actualizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/actualizar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_actualizar.setIcon(icon3)
        self.btn_btn_actualizar.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_actualizar.setObjectName("btn_btn_actualizar")
        self.gridLayout_2.addWidget(self.btn_btn_actualizar, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.contenedor_formulario = QtWidgets.QFrame(self.contenedor)
        self.contenedor_formulario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_formulario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_formulario.setObjectName("contenedor_formulario")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.contenedor_formulario)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.etiqueta_nombredepartamento = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_nombredepartamento.setObjectName("etiqueta_nombredepartamento")
        self.gridLayout_5.addWidget(self.etiqueta_nombredepartamento, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 2, 1, 1)
        self.etiquetasubtitulo_departamentosexistentes = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiquetasubtitulo_departamentosexistentes.setObjectName("etiquetasubtitulo_departamentosexistentes")
        self.gridLayout_5.addWidget(self.etiquetasubtitulo_departamentosexistentes, 1, 4, 1, 1)
        self.etiquetasubtitulo_puestosasignados = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiquetasubtitulo_puestosasignados.setObjectName("etiquetasubtitulo_puestosasignados")
        self.gridLayout_5.addWidget(self.etiquetasubtitulo_puestosasignados, 1, 5, 1, 1)
        self.etiqueta_descripciondepartamento = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_descripciondepartamento.setObjectName("etiqueta_descripciondepartamento")
        self.gridLayout_5.addWidget(self.etiqueta_descripciondepartamento, 2, 0, 1, 2)
        self.lista_departamentosexistentes = QtWidgets.QListWidget(self.contenedor_formulario)
        self.lista_departamentosexistentes.setObjectName("lista_departamentosexistentes")
        self.gridLayout_5.addWidget(self.lista_departamentosexistentes, 2, 4, 4, 1)
        self.lista_puestosasignados = QtWidgets.QListWidget(self.contenedor_formulario)
        self.lista_puestosasignados.setObjectName("lista_puestosasignados")
        self.gridLayout_5.addWidget(self.lista_puestosasignados, 2, 5, 4, 1)
        self.txtlargo_descripciondepartamento = QtWidgets.QPlainTextEdit(self.contenedor_formulario)
        self.txtlargo_descripciondepartamento.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txtlargo_descripciondepartamento.setObjectName("txtlargo_descripciondepartamento")
        self.gridLayout_5.addWidget(self.txtlargo_descripciondepartamento, 3, 0, 1, 4)
        self.etiquetasubtitulo_sucursalesexistentes = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiquetasubtitulo_sucursalesexistentes.setObjectName("etiquetasubtitulo_sucursalesexistentes")
        self.gridLayout_5.addWidget(self.etiquetasubtitulo_sucursalesexistentes, 4, 0, 1, 1)
        self.etiquetasubtitulo_sucursalesvinculadas = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiquetasubtitulo_sucursalesvinculadas.setWordWrap(True)
        self.etiquetasubtitulo_sucursalesvinculadas.setObjectName("etiquetasubtitulo_sucursalesvinculadas")
        self.gridLayout_5.addWidget(self.etiquetasubtitulo_sucursalesvinculadas, 4, 2, 1, 2)
        self.lista_sucursalesexistentes = QtWidgets.QListWidget(self.contenedor_formulario)
        self.lista_sucursalesexistentes.setObjectName("lista_sucursalesexistentes")
        self.gridLayout_5.addWidget(self.lista_sucursalesexistentes, 5, 0, 1, 1)
        self.contenedor_botonesvincular = QtWidgets.QFrame(self.contenedor_formulario)
        self.contenedor_botonesvincular.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_botonesvincular.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_botonesvincular.setObjectName("contenedor_botonesvincular")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.contenedor_botonesvincular)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_btn_vincular = QtWidgets.QPushButton(self.contenedor_botonesvincular)
        self.btn_btn_vincular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_vincular.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/flecha_derecha_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_vincular.setIcon(icon4)
        self.btn_btn_vincular.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_vincular.setObjectName("btn_btn_vincular")
        self.gridLayout_3.addWidget(self.btn_btn_vincular, 0, 0, 1, 1)
        self.btn_btn_desvincular = QtWidgets.QPushButton(self.contenedor_botonesvincular)
        self.btn_btn_desvincular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_desvincular.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/flecha_izquierda_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_desvincular.setIcon(icon5)
        self.btn_btn_desvincular.setIconSize(QtCore.QSize(24, 24))
        self.btn_btn_desvincular.setObjectName("btn_btn_desvincular")
        self.gridLayout_3.addWidget(self.btn_btn_desvincular, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.contenedor_botonesvincular, 5, 1, 1, 1)
        self.lista_sucursalesvinculadas = QtWidgets.QListWidget(self.contenedor_formulario)
        self.lista_sucursalesvinculadas.setObjectName("lista_sucursalesvinculadas")
        self.gridLayout_5.addWidget(self.lista_sucursalesvinculadas, 5, 2, 1, 2)
        self.txt_nombredepartamento = QtWidgets.QLineEdit(self.contenedor_formulario)
        self.txt_nombredepartamento.setObjectName("txt_nombredepartamento")
        self.gridLayout_5.addWidget(self.txt_nombredepartamento, 1, 0, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txt_buscardepartamento = QtWidgets.QLineEdit(self.contenedor_formulario)
        self.txt_buscardepartamento.setObjectName("txt_buscardepartamento")
        self.gridLayout_4.addWidget(self.txt_buscardepartamento, 0, 1, 1, 1)
        self.etiqueta_buscardepartamento = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_buscardepartamento.setText("")
        self.etiqueta_buscardepartamento.setPixmap(QtGui.QPixmap(":/iconosAzules/Icons/iconos/Azul/buscar_filas_azul.svg"))
        self.etiqueta_buscardepartamento.setScaledContents(True)
        self.etiqueta_buscardepartamento.setAlignment(QtCore.Qt.AlignCenter)
        self.etiqueta_buscardepartamento.setObjectName("etiqueta_buscardepartamento")
        self.gridLayout_4.addWidget(self.etiqueta_buscardepartamento, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 4, 1, 2)
        self.gridLayout_2.addWidget(self.contenedor_formulario, 1, 0, 1, 7)
        self.btn_btn_limpiar = QtWidgets.QPushButton(self.contenedor)
        self.btn_btn_limpiar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_limpiar.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/borrador.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_limpiar.setIcon(icon6)
        self.btn_btn_limpiar.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_limpiar.setObjectName("btn_btn_limpiar")
        self.gridLayout_2.addWidget(self.btn_btn_limpiar, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.contenedor, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Control_departamentos)
        QtCore.QMetaObject.connectSlotsByName(Control_departamentos)
        Control_departamentos.setTabOrder(self.txt_nombredepartamento, self.txtlargo_descripciondepartamento)
        Control_departamentos.setTabOrder(self.txtlargo_descripciondepartamento, self.btn_btn_vincular)
        Control_departamentos.setTabOrder(self.btn_btn_vincular, self.btn_btn_desvincular)
        Control_departamentos.setTabOrder(self.btn_btn_desvincular, self.lista_sucursalesexistentes)
        Control_departamentos.setTabOrder(self.lista_sucursalesexistentes, self.lista_sucursalesvinculadas)
        Control_departamentos.setTabOrder(self.lista_sucursalesvinculadas, self.txt_buscardepartamento)
        Control_departamentos.setTabOrder(self.txt_buscardepartamento, self.lista_departamentosexistentes)
        Control_departamentos.setTabOrder(self.lista_departamentosexistentes, self.lista_puestosasignados)
        Control_departamentos.setTabOrder(self.lista_puestosasignados, self.btn_btn_guardar)
        Control_departamentos.setTabOrder(self.btn_btn_guardar, self.btn_btn_actualizar)
        Control_departamentos.setTabOrder(self.btn_btn_actualizar, self.btn_btn_eliminar)

    def retranslateUi(self, Control_departamentos):
        _translate = QtCore.QCoreApplication.translate
        Control_departamentos.setWindowTitle(_translate("Control_departamentos", "Form"))
        self.etiquetaTituloEncabezado.setText(_translate("Control_departamentos", "Departamentos"))
        self.btn_btn_eliminar.setText(_translate("Control_departamentos", "Eliminar"))
        self.btn_btn_guardar.setText(_translate("Control_departamentos", "Guardar"))
        self.btn_btn_actualizar.setText(_translate("Control_departamentos", "Actualizar"))
        self.etiqueta_nombredepartamento.setText(_translate("Control_departamentos", "Nombre del departamento:"))
        self.etiquetasubtitulo_departamentosexistentes.setText(_translate("Control_departamentos", "Departamentos existentes"))
        self.etiquetasubtitulo_puestosasignados.setText(_translate("Control_departamentos", "Puestos Asignados"))
        self.etiqueta_descripciondepartamento.setText(_translate("Control_departamentos", "Descripcion del departamento:"))
        self.etiquetasubtitulo_sucursalesexistentes.setText(_translate("Control_departamentos", "Sucursales existentes:"))
        self.etiquetasubtitulo_sucursalesvinculadas.setText(_translate("Control_departamentos", "Sucusales vinculadas"))
        self.btn_btn_vincular.setToolTip(_translate("Control_departamentos", "Vincular"))
        self.btn_btn_desvincular.setToolTip(_translate("Control_departamentos", "Desvincular"))
        self.txt_buscardepartamento.setPlaceholderText(_translate("Control_departamentos", " Buscar Departamento"))
import ibootstrap_rc
import iconosSVG_rc
import iconsdvg_rc
