# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ing. Angel Perez\Documents\projects\DesktopPosWithPython\app\View\UserInterfaceUi\UI_REGISTRO_EMPLEADO.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistroAdministrador(object):
    def setupUi(self, RegistroAdministrador):
        RegistroAdministrador.setObjectName("RegistroAdministrador")
        RegistroAdministrador.resize(1214, 673)
        RegistroAdministrador.setStyleSheet("#RegistroAdministrador{\n"
"background: #fffefb;\n"
"}\n"
"#widget_cabecera_ventana{\n"
"    background-color: #0077CC;\n"
"    min-height: 30px;\n"
"}\n"
"[objectName^=\"btc\"]{\n"
"background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 9px;\n"
"    max-width:20px;\n"
"    max-height:20px;\n"
"    min-width:20px;\n"
"    min-height:20px;\n"
"}\n"
"[objectName^=\"btc\"]:hover{\n"
"    background-color: rgb(214, 214, 214);\n"
"}\n"
"#btc_cerrar::hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"#widget_contenedor{\n"
"    background-color: #fffefb;\n"
"}\n"
"#label_fotousuario{\n"
"    min-width:180px;\n"
"    min-height:180px;\n"
"    max-width:180px;\n"
"    max-height:180px;\n"
"    border:solid 2px black;\n"
"    background-color:#F5F5F5;\n"
"}\n"
"[objectName^=\"etiquetaTitulo_\"]{\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}\n"
"[objectName^=\"etiquetasubtitulo_\"]{\n"
"    font-family: Arial;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    max-height:30px;\n"
"    min-height:30px;\n"
"}\n"
"[objectName^=\"etiqueta_\"]{\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"font-weight: bold;\n"
"}\n"
"[objectName^=\"txt_\"]{\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    border:none;\n"
"border-radius: 4px;\n"
"    border-bottom: 1px solid #3b3c3d;\n"
"    background-color: #F5F5F5;\n"
"padding: 2px;\n"
"}\n"
"[objectName^=\"txt_\"]::focus{\n"
"border-bottom: 2px solid #00668c;\n"
"}\n"
"[objectName^=\"decimal_\"]{\n"
"border: none;\n"
"border-bottom: 1px solid #3b3c3d;\n"
"border-radius: 4px;\n"
"background-color: #F5F5F5;\n"
"font-size: 14px;\n"
"padding: 2px;\n"
"}\n"
"[objectName^=\"decimal_\"]::focus{\n"
"border-bottom: 2px solid #00668c;\n"
"}\n"
"[objectName^=\"opcion_\"]{\n"
"font-size: 14px;\n"
"font-family:Arial;\n"
"}\n"
"[objectName^=\"cajaopciones\"]{\n"
"border: none;\n"
"border-bottom: 1px solid #3b3c3d;\n"
"border-top-left-radius: 4px;\n"
"border-top-right-radius: 4px;\n"
"padding: 2px;\n"
"background-color: #F5F5F5;\n"
"font-size: 14px;\n"
"width:87px;\n"
"}\n"
"[objectName^=\"cajaopciones\"]::drop-down{\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: top right;\n"
"padding-right:5px;\n"
"width: 20%;\n"
"border-left-width: 1px;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"background-color: #F5F5F5;\n"
"}\n"
"[objectName^=\"cajaopciones_\"]::down-arrow{\n"
"image: url(:/Icons/Bootstrap/filter-left.svg);\n"
"width: 17%;\n"
"height: 17%;\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}\n"
"[objectName^=\"txtlargo_\"]{\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    max-height: 110px;\n"
"    min-height: 110px;\n"
"border-radius: 4px;\n"
"background-color: #F5F5F5;\n"
"border: 1px solid #787878;\n"
"}\n"
"[objectName^=\"fecha_\"]{\n"
"border: none;\n"
"border-bottom: 1px solid #3b3c3d;\n"
"border-top-left-radius: 4px;\n"
"border-top-right-radius: 4px;\n"
"padding: 2px;\n"
"background-color: #F5F5F5;\n"
"font-size: 14px;\n"
"width:87px;\n"
"}\n"
"[objectName^=\"fceha_\"]::drop-down{\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: top right;\n"
"padding-right:5px;\n"
"width: 20%;\n"
"border-left-width: 1px;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"background-color: #F5F5F5;\n"
"}\n"
"[objectName^=\"fceha_\"]::down-arrow{\n"
"/* Reemplaza con la ruta de tu imagen de flecha */\n"
"image: url(:/Icons/Bootstrap/calendar2-date.svg);\n"
"width: 17%;\n"
"height: 17%;\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}\n"
"[objectName^=\"fecha_\"]::focus{\n"
"border-bottom: 2px solid #00668c;\n"
"}\n"
"\n"
"[objectName^=\"Button\"]{\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight:bold;\n"
"color: #fffefb;\n"
"background: #00619a;\n"
"border:none;\n"
"border-radius:5px;\n"
"height:25px;\n"
"}\n"
"[objectName^=\"Button\"]:hover{\n"
"background: #2196F3;\n"
"}\n"
"#Button_aceptar{\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    min-width: 45px;\n"
"    width: 70px;\n"
"    min-height: 30px;\n"
"    height: 30px;\n"
"    background-color: #00619a;\n"
"}\n"
"#Button_aceptar:hover{\n"
"    background-color: #68a67d;\n"
"}\n"
"#Button_cancelar{\n"
"    border: none;\n"
"    border-radius: 5px;    \n"
"    min-width: 45px;\n"
"    width: 70px;\n"
"    min-height: 30px;\n"
"    height: 30px;\n"
"    background-color: #00619a;    \n"
"}\n"
"#Button_cancelar:hover{\n"
"    background-color: #EE1D52;\n"
"}\n"
"#label_fotousuario{\n"
"    min-height: 100px;\n"
"    min-width: 100px;\n"
"    height: 180px;\n"
"    width: 180px;\n"
"background-color: #F5F5F5;\n"
"}\n"
"[objectName^=\"fecha_\"]{\n"
"border: none;\n"
"border-bottom: 1px solid #3b3c3d;\n"
"border-radius: 5px;\n"
"padding: 2px;\n"
"background-color: #f5f4f1;\n"
"font-size: 12px;\n"
"width:87px;\n"
"}\n"
"*[objectName^=\"fecha_\"]::drop-down{\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: top right;\n"
"padding-right:5px;\n"
"width: 20%;\n"
"border-left-width: 1px;\n"
"border-radius: 5px;\n"
"background-color: #f5f4f1;\n"
"}\n"
"*[objectName^=\"fecha_\"]::down-arrow{\n"
"image: url(:/Icons/Bootstrap/calendar2-date.svg);\n"
"width: 17%;\n"
"height: 17%;\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}\n"
"*[objectName^=\"fecha_\"]::focus{\n"
"border-bottom: 2px solid #00668c;\n"
"}\n"
"[objectName*=\"tiempo_\"]{\n"
"background-color: rgb(245, 244, 241);\n"
"color: rgb(29, 28, 28);\n"
"border: none;\n"
"border-bottom: 1px solid;\n"
"border-radius: 5px;\n"
"font-size: 12px;\n"
"font-family: Arial;\n"
"}\n"
"[objectName^=\"tiempo_\"]::focus{\n"
"border-bottom: 2px solid #00668c;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(RegistroAdministrador)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_contenedor = QtWidgets.QWidget(RegistroAdministrador)
        self.widget_contenedor.setStyleSheet("")
        self.widget_contenedor.setObjectName("widget_contenedor")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_contenedor)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_cabecera_ventana = QtWidgets.QWidget(self.widget_contenedor)
        self.widget_cabecera_ventana.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_cabecera_ventana.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_cabecera_ventana.setStyleSheet("")
        self.widget_cabecera_ventana.setObjectName("widget_cabecera_ventana")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_cabecera_ventana)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget_cabecera_ventana)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btc_minimizar = QtWidgets.QPushButton(self.widget_2)
        self.btc_minimizar.setMinimumSize(QtCore.QSize(20, 20))
        self.btc_minimizar.setMaximumSize(QtCore.QSize(20, 20))
        self.btc_minimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btc_minimizar.setStyleSheet("")
        self.btc_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/arrows-angle-contract.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btc_minimizar.setIcon(icon)
        self.btc_minimizar.setIconSize(QtCore.QSize(20, 15))
        self.btc_minimizar.setObjectName("btc_minimizar")
        self.horizontalLayout.addWidget(self.btc_minimizar)
        self.btc_maximizar = QtWidgets.QPushButton(self.widget_2)
        self.btc_maximizar.setMinimumSize(QtCore.QSize(20, 20))
        self.btc_maximizar.setMaximumSize(QtCore.QSize(20, 20))
        self.btc_maximizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btc_maximizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/arrows-angle-expand.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btc_maximizar.setIcon(icon1)
        self.btc_maximizar.setIconSize(QtCore.QSize(20, 15))
        self.btc_maximizar.setObjectName("btc_maximizar")
        self.horizontalLayout.addWidget(self.btc_maximizar)
        self.btc_cerrar = QtWidgets.QPushButton(self.widget_2)
        self.btc_cerrar.setMinimumSize(QtCore.QSize(20, 20))
        self.btc_cerrar.setMaximumSize(QtCore.QSize(20, 20))
        self.btc_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btc_cerrar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/x-lg.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btc_cerrar.setIcon(icon2)
        self.btc_cerrar.setIconSize(QtCore.QSize(20, 15))
        self.btc_cerrar.setObjectName("btc_cerrar")
        self.horizontalLayout.addWidget(self.btc_cerrar)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.widget_cabecera_ventana)
        self.widget_4 = QtWidgets.QWidget(self.widget_contenedor)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.etiquetaTitulo_agregarpersona = QtWidgets.QLabel(self.widget_4)
        self.etiquetaTitulo_agregarpersona.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.etiquetaTitulo_agregarpersona.setObjectName("etiquetaTitulo_agregarpersona")
        self.gridLayout_4.addWidget(self.etiquetaTitulo_agregarpersona, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.etiqueta_horasalida = QtWidgets.QLabel(self.widget_5)
        self.etiqueta_horasalida.setObjectName("etiqueta_horasalida")
        self.gridLayout_3.addWidget(self.etiqueta_horasalida, 10, 0, 1, 1)
        self.etiqueta_sucursal = QtWidgets.QLabel(self.widget_5)
        self.etiqueta_sucursal.setObjectName("etiqueta_sucursal")
        self.gridLayout_3.addWidget(self.etiqueta_sucursal, 1, 0, 1, 1)
        self.cajaopciones_sucursales = QtWidgets.QComboBox(self.widget_5)
        self.cajaopciones_sucursales.setObjectName("cajaopciones_sucursales")
        self.gridLayout_3.addWidget(self.cajaopciones_sucursales, 2, 0, 1, 1)
        self.tiempo_horaentrada = QtWidgets.QTimeEdit(self.widget_5)
        self.tiempo_horaentrada.setCalendarPopup(True)
        self.tiempo_horaentrada.setObjectName("tiempo_horaentrada")
        self.gridLayout_3.addWidget(self.tiempo_horaentrada, 9, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 203, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 12, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Button_aceptar = QtWidgets.QToolButton(self.widget_5)
        self.Button_aceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_aceptar.setObjectName("Button_aceptar")
        self.gridLayout_2.addWidget(self.Button_aceptar, 0, 0, 1, 1)
        self.Button_cancelar = QtWidgets.QToolButton(self.widget_5)
        self.Button_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_cancelar.setObjectName("Button_cancelar")
        self.gridLayout_2.addWidget(self.Button_cancelar, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 13, 0, 1, 1)
        self.label_fotousuario = QtWidgets.QLabel(self.widget_5)
        self.label_fotousuario.setText("")
        self.label_fotousuario.setObjectName("label_fotousuario")
        self.gridLayout_3.addWidget(self.label_fotousuario, 0, 0, 1, 1)
        self.tiempo_horasalida = QtWidgets.QTimeEdit(self.widget_5)
        self.tiempo_horasalida.setCalendarPopup(True)
        self.tiempo_horasalida.setObjectName("tiempo_horasalida")
        self.gridLayout_3.addWidget(self.tiempo_horasalida, 11, 0, 1, 1)
        self.cajaopciones_puestos = QtWidgets.QComboBox(self.widget_5)
        self.cajaopciones_puestos.setObjectName("cajaopciones_puestos")
        self.gridLayout_3.addWidget(self.cajaopciones_puestos, 7, 0, 1, 1)
        self.etiqueta_horaentrada = QtWidgets.QLabel(self.widget_5)
        self.etiqueta_horaentrada.setObjectName("etiqueta_horaentrada")
        self.gridLayout_3.addWidget(self.etiqueta_horaentrada, 8, 0, 1, 1)
        self.etiqueta_departamento = QtWidgets.QLabel(self.widget_5)
        self.etiqueta_departamento.setObjectName("etiqueta_departamento")
        self.gridLayout_3.addWidget(self.etiqueta_departamento, 4, 0, 1, 1)
        self.etiqueta_puesto = QtWidgets.QLabel(self.widget_5)
        self.etiqueta_puesto.setObjectName("etiqueta_puesto")
        self.gridLayout_3.addWidget(self.etiqueta_puesto, 6, 0, 1, 1)
        self.cajaopciones_departamentos = QtWidgets.QComboBox(self.widget_5)
        self.cajaopciones_departamentos.setObjectName("cajaopciones_departamentos")
        self.gridLayout_3.addWidget(self.cajaopciones_departamentos, 5, 0, 1, 1)
        self.Button_nuevasucursal = QtWidgets.QPushButton(self.widget_5)
        self.Button_nuevasucursal.setObjectName("Button_nuevasucursal")
        self.gridLayout_3.addWidget(self.Button_nuevasucursal, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_5, 1, 2, 1, 1)
        self.widget_diaslaborales = QtWidgets.QWidget(self.widget_4)
        self.widget_diaslaborales.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_diaslaborales.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_diaslaborales.setObjectName("widget_diaslaborales")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_diaslaborales)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.etiquetasubtitulo_diaslaborales = QtWidgets.QLabel(self.widget_diaslaborales)
        self.etiquetasubtitulo_diaslaborales.setObjectName("etiquetasubtitulo_diaslaborales")
        self.gridLayout_10.addWidget(self.etiquetasubtitulo_diaslaborales, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem2, 16, 0, 1, 1)
        self.opcion_jueves = QtWidgets.QCheckBox(self.widget_diaslaborales)
        self.opcion_jueves.setObjectName("opcion_jueves")
        self.gridLayout_10.addWidget(self.opcion_jueves, 5, 0, 1, 1)
        self.fecha_fechacontratacion = QtWidgets.QDateEdit(self.widget_diaslaborales)
        self.fecha_fechacontratacion.setCalendarPopup(True)
        self.fecha_fechacontratacion.setObjectName("fecha_fechacontratacion")
        self.gridLayout_10.addWidget(self.fecha_fechacontratacion, 15, 0, 1, 1)
        self.opcion_lunes = QtWidgets.QCheckBox(self.widget_diaslaborales)
        self.opcion_lunes.setObjectName("opcion_lunes")
        self.gridLayout_10.addWidget(self.opcion_lunes, 2, 0, 1, 1)
        self.opcion_sabado = QtWidgets.QCheckBox(self.widget_diaslaborales)
        self.opcion_sabado.setObjectName("opcion_sabado")
        self.gridLayout_10.addWidget(self.opcion_sabado, 7, 0, 1, 1)
        self.opcion_viernes = QtWidgets.QCheckBox(self.widget_diaslaborales)
        self.opcion_viernes.setObjectName("opcion_viernes")
        self.gridLayout_10.addWidget(self.opcion_viernes, 6, 0, 1, 1)
        self.etiqueta_fechacontratacion = QtWidgets.QLabel(self.widget_diaslaborales)
        self.etiqueta_fechacontratacion.setObjectName("etiqueta_fechacontratacion")
        self.gridLayout_10.addWidget(self.etiqueta_fechacontratacion, 14, 0, 1, 1)
        self.opcion_domingo = QtWidgets.QCheckBox(self.widget_diaslaborales)
        self.opcion_domingo.setObjectName("opcion_domingo")
        self.gridLayout_10.addWidget(self.opcion_domingo, 1, 0, 1, 1)
        self.opcion_martes = QtWidgets.QCheckBox(self.widget_diaslaborales)
        self.opcion_martes.setObjectName("opcion_martes")
        self.gridLayout_10.addWidget(self.opcion_martes, 3, 0, 1, 1)
        self.opcion_miercoles = QtWidgets.QCheckBox(self.widget_diaslaborales)
        self.opcion_miercoles.setObjectName("opcion_miercoles")
        self.gridLayout_10.addWidget(self.opcion_miercoles, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.widget_diaslaborales)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_10.addWidget(self.line, 13, 0, 1, 1)
        self.etiqueta_horaslaborales = QtWidgets.QLabel(self.widget_diaslaborales)
        self.etiqueta_horaslaborales.setObjectName("etiqueta_horaslaborales")
        self.gridLayout_10.addWidget(self.etiqueta_horaslaborales, 8, 0, 1, 1)
        self.decimal_horas_laboralestotales = QtWidgets.QDoubleSpinBox(self.widget_diaslaborales)
        self.decimal_horas_laboralestotales.setMaximum(9999.99)
        self.decimal_horas_laboralestotales.setObjectName("decimal_horas_laboralestotales")
        self.gridLayout_10.addWidget(self.decimal_horas_laboralestotales, 9, 0, 1, 1)
        self.etiqueta_salario = QtWidgets.QLabel(self.widget_diaslaborales)
        self.etiqueta_salario.setObjectName("etiqueta_salario")
        self.gridLayout_10.addWidget(self.etiqueta_salario, 11, 0, 1, 1)
        self.decimal_salario = QtWidgets.QDoubleSpinBox(self.widget_diaslaborales)
        self.decimal_salario.setMaximum(999999999.99)
        self.decimal_salario.setObjectName("decimal_salario")
        self.gridLayout_10.addWidget(self.decimal_salario, 12, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_diaslaborales, 1, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.etiquetasubtitulo_datos_uniciosesion = QtWidgets.QLabel(self.widget_3)
        self.etiquetasubtitulo_datos_uniciosesion.setObjectName("etiquetasubtitulo_datos_uniciosesion")
        self.gridLayout_9.addWidget(self.etiquetasubtitulo_datos_uniciosesion, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 7, 2, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_9.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.etiquetasubtitulo_direccion = QtWidgets.QLabel(self.widget_3)
        self.etiquetasubtitulo_direccion.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.etiquetasubtitulo_direccion.setObjectName("etiquetasubtitulo_direccion")
        self.gridLayout_9.addWidget(self.etiquetasubtitulo_direccion, 4, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_9.addLayout(self.gridLayout_8, 1, 3, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.txt_apellidom = QtWidgets.QLineEdit(self.widget_3)
        self.txt_apellidom.setClearButtonEnabled(False)
        self.txt_apellidom.setObjectName("txt_apellidom")
        self.gridLayout.addWidget(self.txt_apellidom, 0, 4, 1, 1)
        self.txt_nombre = QtWidgets.QLineEdit(self.widget_3)
        self.txt_nombre.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.txt_nombre.setClearButtonEnabled(False)
        self.txt_nombre.setObjectName("txt_nombre")
        self.gridLayout.addWidget(self.txt_nombre, 0, 0, 1, 2)
        self.etiqueta_estado_civil = QtWidgets.QLabel(self.widget_3)
        self.etiqueta_estado_civil.setObjectName("etiqueta_estado_civil")
        self.gridLayout.addWidget(self.etiqueta_estado_civil, 1, 2, 1, 1)
        self.fecha_fechanacimiento = QtWidgets.QDateEdit(self.widget_3)
        self.fecha_fechanacimiento.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fecha_fechanacimiento.setProperty("showGroupSeparator", False)
        self.fecha_fechanacimiento.setCalendarPopup(True)
        self.fecha_fechanacimiento.setObjectName("fecha_fechanacimiento")
        self.gridLayout.addWidget(self.fecha_fechanacimiento, 1, 1, 1, 1)
        self.etiqueta_fecha_nacimiento = QtWidgets.QLabel(self.widget_3)
        self.etiqueta_fecha_nacimiento.setMaximumSize(QtCore.QSize(150, 16777215))
        self.etiqueta_fecha_nacimiento.setObjectName("etiqueta_fecha_nacimiento")
        self.gridLayout.addWidget(self.etiqueta_fecha_nacimiento, 1, 0, 1, 1)
        self.cajaopciones_estadocvil = QtWidgets.QComboBox(self.widget_3)
        self.cajaopciones_estadocvil.setMinimumSize(QtCore.QSize(140, 0))
        self.cajaopciones_estadocvil.setObjectName("cajaopciones_estadocvil")
        self.gridLayout.addWidget(self.cajaopciones_estadocvil, 1, 3, 1, 1)
        self.txt_apellidop = QtWidgets.QLineEdit(self.widget_3)
        self.txt_apellidop.setClearButtonEnabled(False)
        self.txt_apellidop.setObjectName("txt_apellidop")
        self.gridLayout.addWidget(self.txt_apellidop, 0, 2, 1, 2)
        self.txt_curp = QtWidgets.QLineEdit(self.widget_3)
        self.txt_curp.setClearButtonEnabled(False)
        self.txt_curp.setObjectName("txt_curp")
        self.gridLayout.addWidget(self.txt_curp, 1, 4, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 0, 0, 1, 4)
        self.txtlargo_direccion_completa = QtWidgets.QPlainTextEdit(self.widget_3)
        self.txtlargo_direccion_completa.setStyleSheet("")
        self.txtlargo_direccion_completa.setObjectName("txtlargo_direccion_completa")
        self.gridLayout_9.addWidget(self.txtlargo_direccion_completa, 5, 0, 1, 4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 9, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txt_usuario_iniciosesion = QtWidgets.QLineEdit(self.widget_3)
        self.txt_usuario_iniciosesion.setClearButtonEnabled(False)
        self.txt_usuario_iniciosesion.setObjectName("txt_usuario_iniciosesion")
        self.gridLayout_5.addWidget(self.txt_usuario_iniciosesion, 0, 0, 1, 1)
        self.txt_contrasenia_usuario_iniciosesion = QtWidgets.QLineEdit(self.widget_3)
        self.txt_contrasenia_usuario_iniciosesion.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_contrasenia_usuario_iniciosesion.setClearButtonEnabled(False)
        self.txt_contrasenia_usuario_iniciosesion.setObjectName("txt_contrasenia_usuario_iniciosesion")
        self.gridLayout_5.addWidget(self.txt_contrasenia_usuario_iniciosesion, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_5, 7, 0, 2, 1)
        self.line_3 = QtWidgets.QFrame(self.widget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_9.addWidget(self.line_3, 3, 0, 1, 4)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.etiquetasubtitulo_descripcionpuesto = QtWidgets.QLabel(self.widget_3)
        self.etiquetasubtitulo_descripcionpuesto.setObjectName("etiquetasubtitulo_descripcionpuesto")
        self.gridLayout_6.addWidget(self.etiquetasubtitulo_descripcionpuesto, 4, 0, 1, 7)
        self.txt_rfc = QtWidgets.QLineEdit(self.widget_3)
        self.txt_rfc.setClearButtonEnabled(False)
        self.txt_rfc.setObjectName("txt_rfc")
        self.gridLayout_6.addWidget(self.txt_rfc, 0, 0, 1, 2)
        self.txtlargo_descripcion_puesto = QtWidgets.QPlainTextEdit(self.widget_3)
        self.txtlargo_descripcion_puesto.setObjectName("txtlargo_descripcion_puesto")
        self.gridLayout_6.addWidget(self.txtlargo_descripcion_puesto, 9, 0, 1, 7)
        self.txt_nexterior = QtWidgets.QLineEdit(self.widget_3)
        self.txt_nexterior.setObjectName("txt_nexterior")
        self.gridLayout_6.addWidget(self.txt_nexterior, 2, 4, 1, 1)
        self.txt_ninterior = QtWidgets.QLineEdit(self.widget_3)
        self.txt_ninterior.setObjectName("txt_ninterior")
        self.gridLayout_6.addWidget(self.txt_ninterior, 2, 5, 1, 1)
        self.txt_numerosegurosicial = QtWidgets.QLineEdit(self.widget_3)
        self.txt_numerosegurosicial.setClearButtonEnabled(False)
        self.txt_numerosegurosicial.setObjectName("txt_numerosegurosicial")
        self.gridLayout_6.addWidget(self.txt_numerosegurosicial, 0, 4, 1, 1)
        self.txt_ciudad = QtWidgets.QLineEdit(self.widget_3)
        self.txt_ciudad.setClearButtonEnabled(False)
        self.txt_ciudad.setObjectName("txt_ciudad")
        self.gridLayout_6.addWidget(self.txt_ciudad, 0, 5, 1, 1)
        self.txt_correoelectronico = QtWidgets.QLineEdit(self.widget_3)
        self.txt_correoelectronico.setClearButtonEnabled(False)
        self.txt_correoelectronico.setObjectName("txt_correoelectronico")
        self.gridLayout_6.addWidget(self.txt_correoelectronico, 0, 2, 1, 2)
        self.txt_avenidas = QtWidgets.QLineEdit(self.widget_3)
        self.txt_avenidas.setObjectName("txt_avenidas")
        self.gridLayout_6.addWidget(self.txt_avenidas, 1, 2, 1, 2)
        self.txt_colonia = QtWidgets.QLineEdit(self.widget_3)
        self.txt_colonia.setObjectName("txt_colonia")
        self.gridLayout_6.addWidget(self.txt_colonia, 1, 1, 1, 1)
        self.txt_codigopostal = QtWidgets.QLineEdit(self.widget_3)
        self.txt_codigopostal.setClearButtonEnabled(False)
        self.txt_codigopostal.setObjectName("txt_codigopostal")
        self.gridLayout_6.addWidget(self.txt_codigopostal, 2, 0, 1, 1)
        self.txt_estado = QtWidgets.QLineEdit(self.widget_3)
        self.txt_estado.setClearButtonEnabled(False)
        self.txt_estado.setObjectName("txt_estado")
        self.gridLayout_6.addWidget(self.txt_estado, 0, 6, 1, 1)
        self.txt_pais = QtWidgets.QLineEdit(self.widget_3)
        self.txt_pais.setClearButtonEnabled(False)
        self.txt_pais.setObjectName("txt_pais")
        self.gridLayout_6.addWidget(self.txt_pais, 1, 0, 1, 1)
        self.txt_calles = QtWidgets.QLineEdit(self.widget_3)
        self.txt_calles.setObjectName("txt_calles")
        self.gridLayout_6.addWidget(self.txt_calles, 1, 4, 1, 2)
        self.txt_numerotelefono = QtWidgets.QLineEdit(self.widget_3)
        self.txt_numerotelefono.setClearButtonEnabled(False)
        self.txt_numerotelefono.setObjectName("txt_numerotelefono")
        self.gridLayout_6.addWidget(self.txt_numerotelefono, 1, 6, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 3, 0, 1, 7)
        self.gridLayout_9.addLayout(self.gridLayout_6, 2, 0, 1, 4)
        self.etiqueta_rol_usuario = QtWidgets.QLabel(self.widget_3)
        self.etiqueta_rol_usuario.setObjectName("etiqueta_rol_usuario")
        self.gridLayout_9.addWidget(self.etiqueta_rol_usuario, 7, 1, 1, 1)
        self.cajaopciones_rol_usuario = QtWidgets.QComboBox(self.widget_3)
        self.cajaopciones_rol_usuario.setObjectName("cajaopciones_rol_usuario")
        self.gridLayout_9.addWidget(self.cajaopciones_rol_usuario, 8, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_3, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget_contenedor)

        self.retranslateUi(RegistroAdministrador)
        QtCore.QMetaObject.connectSlotsByName(RegistroAdministrador)
        RegistroAdministrador.setTabOrder(self.txt_nombre, self.txt_apellidop)
        RegistroAdministrador.setTabOrder(self.txt_apellidop, self.txt_apellidom)
        RegistroAdministrador.setTabOrder(self.txt_apellidom, self.fecha_fechanacimiento)
        RegistroAdministrador.setTabOrder(self.fecha_fechanacimiento, self.cajaopciones_estadocvil)
        RegistroAdministrador.setTabOrder(self.cajaopciones_estadocvil, self.txt_curp)
        RegistroAdministrador.setTabOrder(self.txt_curp, self.txt_rfc)
        RegistroAdministrador.setTabOrder(self.txt_rfc, self.txt_correoelectronico)
        RegistroAdministrador.setTabOrder(self.txt_correoelectronico, self.txt_numerosegurosicial)
        RegistroAdministrador.setTabOrder(self.txt_numerosegurosicial, self.txt_ciudad)
        RegistroAdministrador.setTabOrder(self.txt_ciudad, self.txt_estado)
        RegistroAdministrador.setTabOrder(self.txt_estado, self.txt_pais)
        RegistroAdministrador.setTabOrder(self.txt_pais, self.txt_colonia)
        RegistroAdministrador.setTabOrder(self.txt_colonia, self.txt_avenidas)
        RegistroAdministrador.setTabOrder(self.txt_avenidas, self.txt_calles)
        RegistroAdministrador.setTabOrder(self.txt_calles, self.txt_numerotelefono)
        RegistroAdministrador.setTabOrder(self.txt_numerotelefono, self.txt_codigopostal)
        RegistroAdministrador.setTabOrder(self.txt_codigopostal, self.txt_nexterior)
        RegistroAdministrador.setTabOrder(self.txt_nexterior, self.txt_ninterior)
        RegistroAdministrador.setTabOrder(self.txt_ninterior, self.txtlargo_descripcion_puesto)
        RegistroAdministrador.setTabOrder(self.txtlargo_descripcion_puesto, self.txtlargo_direccion_completa)
        RegistroAdministrador.setTabOrder(self.txtlargo_direccion_completa, self.txt_usuario_iniciosesion)
        RegistroAdministrador.setTabOrder(self.txt_usuario_iniciosesion, self.txt_contrasenia_usuario_iniciosesion)
        RegistroAdministrador.setTabOrder(self.txt_contrasenia_usuario_iniciosesion, self.cajaopciones_rol_usuario)
        RegistroAdministrador.setTabOrder(self.cajaopciones_rol_usuario, self.opcion_domingo)
        RegistroAdministrador.setTabOrder(self.opcion_domingo, self.opcion_lunes)
        RegistroAdministrador.setTabOrder(self.opcion_lunes, self.opcion_martes)
        RegistroAdministrador.setTabOrder(self.opcion_martes, self.opcion_miercoles)
        RegistroAdministrador.setTabOrder(self.opcion_miercoles, self.opcion_jueves)
        RegistroAdministrador.setTabOrder(self.opcion_jueves, self.opcion_viernes)
        RegistroAdministrador.setTabOrder(self.opcion_viernes, self.opcion_sabado)
        RegistroAdministrador.setTabOrder(self.opcion_sabado, self.decimal_horas_laboralestotales)
        RegistroAdministrador.setTabOrder(self.decimal_horas_laboralestotales, self.decimal_salario)
        RegistroAdministrador.setTabOrder(self.decimal_salario, self.fecha_fechacontratacion)
        RegistroAdministrador.setTabOrder(self.fecha_fechacontratacion, self.cajaopciones_sucursales)
        RegistroAdministrador.setTabOrder(self.cajaopciones_sucursales, self.Button_nuevasucursal)
        RegistroAdministrador.setTabOrder(self.Button_nuevasucursal, self.cajaopciones_departamentos)
        RegistroAdministrador.setTabOrder(self.cajaopciones_departamentos, self.cajaopciones_puestos)
        RegistroAdministrador.setTabOrder(self.cajaopciones_puestos, self.tiempo_horaentrada)
        RegistroAdministrador.setTabOrder(self.tiempo_horaentrada, self.tiempo_horasalida)
        RegistroAdministrador.setTabOrder(self.tiempo_horasalida, self.Button_aceptar)
        RegistroAdministrador.setTabOrder(self.Button_aceptar, self.Button_cancelar)
        RegistroAdministrador.setTabOrder(self.Button_cancelar, self.btc_cerrar)
        RegistroAdministrador.setTabOrder(self.btc_cerrar, self.btc_minimizar)
        RegistroAdministrador.setTabOrder(self.btc_minimizar, self.btc_maximizar)

    def retranslateUi(self, RegistroAdministrador):
        _translate = QtCore.QCoreApplication.translate
        RegistroAdministrador.setWindowTitle(_translate("RegistroAdministrador", "Form"))
        self.etiquetaTitulo_agregarpersona.setText(_translate("RegistroAdministrador", "REGISTRO DE PERSONAL"))
        self.etiqueta_horasalida.setText(_translate("RegistroAdministrador", "Hora salida"))
        self.etiqueta_sucursal.setText(_translate("RegistroAdministrador", "Sucursal"))
        self.Button_aceptar.setText(_translate("RegistroAdministrador", "Aceptar"))
        self.Button_cancelar.setText(_translate("RegistroAdministrador", "Cancelar"))
        self.etiqueta_horaentrada.setText(_translate("RegistroAdministrador", "Hora entrada"))
        self.etiqueta_departamento.setText(_translate("RegistroAdministrador", "Departamento"))
        self.etiqueta_puesto.setText(_translate("RegistroAdministrador", "Puesto"))
        self.Button_nuevasucursal.setText(_translate("RegistroAdministrador", "Nueva Sucursal"))
        self.etiquetasubtitulo_diaslaborales.setText(_translate("RegistroAdministrador", "Dias Laborales"))
        self.opcion_jueves.setText(_translate("RegistroAdministrador", "Jueves"))
        self.opcion_lunes.setText(_translate("RegistroAdministrador", "Lunes"))
        self.opcion_sabado.setText(_translate("RegistroAdministrador", "Sabado"))
        self.opcion_viernes.setText(_translate("RegistroAdministrador", "Viernes"))
        self.etiqueta_fechacontratacion.setText(_translate("RegistroAdministrador", "Fecha de contratación:"))
        self.opcion_domingo.setText(_translate("RegistroAdministrador", "Domingo"))
        self.opcion_martes.setText(_translate("RegistroAdministrador", "Martes"))
        self.opcion_miercoles.setText(_translate("RegistroAdministrador", "Miercoles"))
        self.etiqueta_horaslaborales.setText(_translate("RegistroAdministrador", "T. Horas laborales:"))
        self.decimal_horas_laboralestotales.setSuffix(_translate("RegistroAdministrador", " Horas"))
        self.etiqueta_salario.setText(_translate("RegistroAdministrador", "Salario:"))
        self.decimal_salario.setPrefix(_translate("RegistroAdministrador", "$ "))
        self.decimal_salario.setSuffix(_translate("RegistroAdministrador", " pesos"))
        self.etiquetasubtitulo_datos_uniciosesion.setText(_translate("RegistroAdministrador", "Datos de inicio de sesión"))
        self.etiquetasubtitulo_direccion.setText(_translate("RegistroAdministrador", "Dirección exacta"))
        self.txt_apellidom.setPlaceholderText(_translate("RegistroAdministrador", "Apellido Materno"))
        self.txt_nombre.setPlaceholderText(_translate("RegistroAdministrador", "Nombre"))
        self.etiqueta_estado_civil.setText(_translate("RegistroAdministrador", "Estado civil:"))
        self.etiqueta_fecha_nacimiento.setText(_translate("RegistroAdministrador", "Fecha de nacimiento:"))
        self.txt_apellidop.setPlaceholderText(_translate("RegistroAdministrador", "Apellido Paterno"))
        self.txt_curp.setPlaceholderText(_translate("RegistroAdministrador", "Curp"))
        self.txtlargo_direccion_completa.setPlaceholderText(_translate("RegistroAdministrador", "Dirección completa y datos de referencia."))
        self.txt_usuario_iniciosesion.setPlaceholderText(_translate("RegistroAdministrador", "Usuario de inicio de sesión"))
        self.txt_contrasenia_usuario_iniciosesion.setPlaceholderText(_translate("RegistroAdministrador", "Usuario de inicio de sesión"))
        self.etiquetasubtitulo_descripcionpuesto.setText(_translate("RegistroAdministrador", "Descripción del puesto"))
        self.txt_rfc.setPlaceholderText(_translate("RegistroAdministrador", "Rfc"))
        self.txtlargo_descripcion_puesto.setPlaceholderText(_translate("RegistroAdministrador", "Ingresa la descripción del puesto"))
        self.txt_nexterior.setPlaceholderText(_translate("RegistroAdministrador", "N-Exterior"))
        self.txt_ninterior.setPlaceholderText(_translate("RegistroAdministrador", "N-Interior"))
        self.txt_numerosegurosicial.setPlaceholderText(_translate("RegistroAdministrador", "Número seguro social"))
        self.txt_ciudad.setPlaceholderText(_translate("RegistroAdministrador", "Ciudad"))
        self.txt_correoelectronico.setPlaceholderText(_translate("RegistroAdministrador", "Correo electronico"))
        self.txt_avenidas.setPlaceholderText(_translate("RegistroAdministrador", "Avenida/s"))
        self.txt_colonia.setPlaceholderText(_translate("RegistroAdministrador", "Colonia"))
        self.txt_codigopostal.setPlaceholderText(_translate("RegistroAdministrador", "Codigo Postal"))
        self.txt_estado.setPlaceholderText(_translate("RegistroAdministrador", "Estado"))
        self.txt_pais.setPlaceholderText(_translate("RegistroAdministrador", "Pais"))
        self.txt_calles.setPlaceholderText(_translate("RegistroAdministrador", "Calle/s"))
        self.txt_numerotelefono.setPlaceholderText(_translate("RegistroAdministrador", "Número de telefono"))
        self.etiqueta_rol_usuario.setText(_translate("RegistroAdministrador", "Rol del usuario:"))
import ibootstrap_rc
import iconos_rc
import iconsdvg_rc
import img_rc
