# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\Microsoft\software-punto-de-venta\app\View\UserInterfaceUi\UI_SELECCIONAR_PRODUCTOS_DEL_VENDEDOR.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Seleccion_Productos_Proveedor(object):
    def setupUi(self, Seleccion_Productos_Proveedor):
        Seleccion_Productos_Proveedor.setObjectName("Seleccion_Productos_Proveedor")
        Seleccion_Productos_Proveedor.resize(885, 467)
        Seleccion_Productos_Proveedor.setStyleSheet("#contenedor_encabezado{\n"
"background: #023375;\n"
"max-height: 25px;\n"
"}\n"
"#etiqueta_encabezado_productosProveedor{\n"
"color: #fffefb;\n"
"font-size: 18px;\n"
"font-weight:bold;\n"
"font-family:\"Arial\";\n"
"}\n"
"[objectName*=\"etiqueta_\"]{\n"
"font-size:14px;\n"
"font-family: Arial;\n"
"font-weight:bold;\n"
"color: #1d1c1c;\n"
"}\n"
"[objectName*=\"txt_\"]{\n"
"background: #F5F5F5;\n"
"border:none;\n"
"border-radius: 5px;\n"
"color: #1d1c1c;\n"
"font-size: 14px;\n"
"border-bottom: 1px solid #787878;\n"
"}\n"
"[objectName*=\"txt_\"]:focus{\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"[objectName*=\"btn_\"]{\n"
"background: #00619a;\n"
"font-size: 14px;\n"
"font-family: Arial;\n"
"font-weight: bold;\n"
"min-height: 25px;\n"
"border: none;\n"
"border-radius: 5px;\n"
"color: #fffefb;\n"
"padding: 3px 5px;\n"
"}\n"
"[objectName*=\"btn_aceptar\"]:hover{\n"
"background: #68a67d;\n"
"}\n"
"[objectName*=\"btn_aceptar\"]:pressed{\n"
"background: #578B69;\n"
"}\n"
"#btn_cerrar{\n"
"background: #fffefb;\n"
"min-height:15px;\n"
"min-width:15px;\n"
"}\n"
"#btn_cerrar:pressed{\n"
"background: rgb(222, 221, 218);\n"
"}\n"
"\n"
"\n"
"#btn_RefrescarTabla{\n"
"border-radius: 2px;\n"
"background: #e0e0e0;\n"
"padding: 5px;\n"
"}\n"
"#btn_RefrescarTabla:hover{\n"
"background: rgb(179, 179, 179);\n"
"}\n"
"#btn_RefrescarTabla:pressed{\n"
"background: #b6ccd8 ;\n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"/* Encabezados de la tabla */\n"
"[objectName*=\"tabla_\"] QHeaderView::section {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"    font-family: \"Arial\";\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"/* Encabezado horizontal */\n"
"[objectName*=\"tabla_\"] QHeaderView::horizontal {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Encabezado vertical */\n"
"[objectName*=\"tabla_\"] QHeaderView::vertical {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"#tabla_productosProveedor{\n"
"min-height: 300px;\n"
"}\n"
"#tabla_productosParaOrden{\n"
"min-height: 300px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Seleccion_Productos_Proveedor)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.contenedor_encabezado = QtWidgets.QFrame(Seleccion_Productos_Proveedor)
        self.contenedor_encabezado.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_encabezado.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_encabezado.setObjectName("contenedor_encabezado")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contenedor_encabezado)
        self.horizontalLayout.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.etiqueta_encabezado_productosProveedor = QtWidgets.QLabel(self.contenedor_encabezado)
        self.etiqueta_encabezado_productosProveedor.setObjectName("etiqueta_encabezado_productosProveedor")
        self.horizontalLayout.addWidget(self.etiqueta_encabezado_productosProveedor)
        spacerItem = QtWidgets.QSpacerItem(743, 4, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_cerrar = QtWidgets.QPushButton(self.contenedor_encabezado)
        self.btn_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cerrar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/x-lg.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon)
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_cerrar)
        self.gridLayout.addWidget(self.contenedor_encabezado, 0, 0, 1, 1)
        self.contenedor_cuerpo = QtWidgets.QFrame(Seleccion_Productos_Proveedor)
        self.contenedor_cuerpo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_cuerpo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_cuerpo.setObjectName("contenedor_cuerpo")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.contenedor_cuerpo)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.contenedor_opciones_superiores = QtWidgets.QFrame(self.contenedor_cuerpo)
        self.contenedor_opciones_superiores.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_opciones_superiores.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_opciones_superiores.setObjectName("contenedor_opciones_superiores")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.contenedor_opciones_superiores)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.etiqueta_nombredelproveedor = QtWidgets.QLabel(self.contenedor_opciones_superiores)
        self.etiqueta_nombredelproveedor.setObjectName("etiqueta_nombredelproveedor")
        self.gridLayout_2.addWidget(self.etiqueta_nombredelproveedor, 0, 0, 1, 1)
        self.btn_aceptar = QtWidgets.QPushButton(self.contenedor_opciones_superiores)
        self.btn_aceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.gridLayout_2.addWidget(self.btn_aceptar, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_nombredelproducto = QtWidgets.QLineEdit(self.contenedor_opciones_superiores)
        self.txt_nombredelproducto.setClearButtonEnabled(True)
        self.txt_nombredelproducto.setObjectName("txt_nombredelproducto")
        self.horizontalLayout_2.addWidget(self.txt_nombredelproducto)
        self.txt_codigodelproducto = QtWidgets.QLineEdit(self.contenedor_opciones_superiores)
        self.txt_codigodelproducto.setClearButtonEnabled(True)
        self.txt_codigodelproducto.setObjectName("txt_codigodelproducto")
        self.horizontalLayout_2.addWidget(self.txt_codigodelproducto)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.contenedor_opciones_superiores, 0, 0, 1, 1)
        self.contenedor_area = QtWidgets.QScrollArea(self.contenedor_cuerpo)
        self.contenedor_area.setWidgetResizable(True)
        self.contenedor_area.setObjectName("contenedor_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 849, 709))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.etiqueta_tablaproductosproveedor = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.etiqueta_tablaproductosproveedor.setObjectName("etiqueta_tablaproductosproveedor")
        self.gridLayout_3.addWidget(self.etiqueta_tablaproductosproveedor, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(619, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.btn_RefrescarTabla = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_RefrescarTabla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_RefrescarTabla.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/base_datos_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_RefrescarTabla.setIcon(icon1)
        self.btn_RefrescarTabla.setObjectName("btn_RefrescarTabla")
        self.gridLayout_3.addWidget(self.btn_RefrescarTabla, 0, 2, 1, 1)
        self.tabla_productosProveedor = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tabla_productosProveedor.setObjectName("tabla_productosProveedor")
        self.gridLayout_3.addWidget(self.tabla_productosProveedor, 1, 0, 1, 3)
        self.etiqueta_tablaproductosparaorden = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.etiqueta_tablaproductosparaorden.setObjectName("etiqueta_tablaproductosparaorden")
        self.gridLayout_3.addWidget(self.etiqueta_tablaproductosparaorden, 4, 0, 1, 3)
        self.tabla_productosParaOrden = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tabla_productosParaOrden.setObjectName("tabla_productosParaOrden")
        self.gridLayout_3.addWidget(self.tabla_productosParaOrden, 5, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 3, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 2, 0, 1, 3)
        self.contenedor_area.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.contenedor_area, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.contenedor_cuerpo, 1, 0, 1, 1)

        self.retranslateUi(Seleccion_Productos_Proveedor)
        QtCore.QMetaObject.connectSlotsByName(Seleccion_Productos_Proveedor)

    def retranslateUi(self, Seleccion_Productos_Proveedor):
        _translate = QtCore.QCoreApplication.translate
        Seleccion_Productos_Proveedor.setWindowTitle(_translate("Seleccion_Productos_Proveedor", "Form"))
        self.etiqueta_encabezado_productosProveedor.setText(_translate("Seleccion_Productos_Proveedor", "Productos"))
        self.etiqueta_nombredelproveedor.setText(_translate("Seleccion_Productos_Proveedor", "Nombre del proveedor: "))
        self.btn_aceptar.setToolTip(_translate("Seleccion_Productos_Proveedor", "Terminar la selección"))
        self.btn_aceptar.setText(_translate("Seleccion_Productos_Proveedor", "Aceptar"))
        self.txt_nombredelproducto.setPlaceholderText(_translate("Seleccion_Productos_Proveedor", "Escribe el nombre del producto"))
        self.txt_codigodelproducto.setPlaceholderText(_translate("Seleccion_Productos_Proveedor", "escribe el codigo del producto"))
        self.etiqueta_tablaproductosproveedor.setText(_translate("Seleccion_Productos_Proveedor", "Productos del proveedor"))
        self.btn_RefrescarTabla.setToolTip(_translate("Seleccion_Productos_Proveedor", "Refrescar tabla productos proveedor"))
        self.etiqueta_tablaproductosparaorden.setText(_translate("Seleccion_Productos_Proveedor", "Productos para orden de compra"))
import ibootstrap_rc
import iconsdvg_rc
