# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\LUIS_ANGEL_VALLEJO\DesktopPosWithPython\app\View\UserInterfaceUi\UI_SISTEMA_PRINCIPAL.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Principal_sistema(object):
    def setupUi(self, Principal_sistema):
        Principal_sistema.setObjectName("Principal_sistema")
        Principal_sistema.resize(1125, 974)
        Principal_sistema.setStyleSheet("#Principal_sistema{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"#label_logoempresa{\n"
"image: url(:/Icons/IconosSVG/logo_devrous.png);\n"
"min-width:80px;\n"
"margin-top: 2px;\n"
"}\n"
"#w_cuerpo_contenido{\n"
"background: #fffefb;\n"
"}\n"
"[objectName^=\"btc\"]{\n"
"background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 9px;\n"
"    min-width:35px;\n"
"    min-height:25px;\n"
"}\n"
"[objectName^=\"btc\"]:hover{\n"
"    background-color: rgb(214, 214, 214);\n"
"}\n"
"#w_encabezado{\n"
"background-color:#cccbc8;\n"
"height:30px;\n"
"min-height: 30px;\n"
"max-height: 30px;\n"
"}\n"
"[objectName^=\"w_\"]{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"[objectName^=\"p_\"]{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"#w_cuerpo_menu{\n"
"min-width:40px;\n"
"max-width:70px;\n"
"background-color: rgb(204, 203, 200);\n"
"}\n"
"#label_fotousuario{\n"
"image: url(:/Icons/SVG/DrawKit(1).svg);\n"
"max-height:40px;\n"
"min-height:40px;\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"}\n"
"[objectName^=\"btn\"]{\n"
"background-color: transparent;\n"
"border: none;\n"
"max-height:35px;\n"
"min-height:35px;\n"
"qproperty-iconSize: 35px 35px;\n"
"}\n"
"[objectName^=\"p_\"]{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"#label_wp_fotousuario{\n"
"background-color:#71c4ef;\n"
"border:  1px solid #cccbc8;\n"
"}\n"
"#label_wp_fotousuario{\n"
"min-width: 100px;\n"
"max-width: 100px;\n"
"min-height: 100px;\n"
"max-height: 100px;\n"
"}\n"
"[objectName^=\"label_wp\"]{\n"
"font-family: Arial;\n"
"color: #1d1c1c;\n"
"font-size:12px;\n"
"}\n"
"#label_wp_nombreusuario{\n"
"font-size:20px;\n"
"font-weight:bold;\n"
"}\n"
"#label_wp_puestousuario{\n"
"font-size:16px;\n"
"}\n"
"#label_wp_telefonoempleado{\n"
"font-size:14px;\n"
"font-weight:bold;\n"
"color: #3b3c3d;\n"
"}\n"
"#w_datos_empleado{\n"
"background-color:#f5f4f1;\n"
"border-radius: 10px;\n"
"}\n"
"#btn_ver_datosempleado{\n"
"qproperty-iconSize: 20px 20px;\n"
"}")
        self.gridLayout_18 = QtWidgets.QGridLayout(Principal_sistema)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.w_contenedor = QtWidgets.QWidget(Principal_sistema)
        self.w_contenedor.setObjectName("w_contenedor")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.w_contenedor)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_encabezado = QtWidgets.QWidget(self.w_contenedor)
        self.w_encabezado.setObjectName("w_encabezado")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.w_encabezado)
        self.gridLayout_2.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btc_minimizar_2 = QtWidgets.QPushButton(self.w_encabezado)
        self.btc_minimizar_2.setMinimumSize(QtCore.QSize(35, 25))
        self.btc_minimizar_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btc_minimizar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btc_minimizar_2.setStyleSheet("")
        self.btc_minimizar_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/arrows-angle-contract.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btc_minimizar_2.setIcon(icon)
        self.btc_minimizar_2.setIconSize(QtCore.QSize(20, 15))
        self.btc_minimizar_2.setObjectName("btc_minimizar_2")
        self.gridLayout_2.addWidget(self.btc_minimizar_2, 0, 2, 1, 1)
        self.btc_cerrar_2 = QtWidgets.QPushButton(self.w_encabezado)
        self.btc_cerrar_2.setMinimumSize(QtCore.QSize(35, 25))
        self.btc_cerrar_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btc_cerrar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btc_cerrar_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/x-lg.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btc_cerrar_2.setIcon(icon1)
        self.btc_cerrar_2.setIconSize(QtCore.QSize(20, 15))
        self.btc_cerrar_2.setObjectName("btc_cerrar_2")
        self.gridLayout_2.addWidget(self.btc_cerrar_2, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.label_logoempresa = QtWidgets.QLabel(self.w_encabezado)
        self.label_logoempresa.setText("")
        self.label_logoempresa.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logoempresa.setObjectName("label_logoempresa")
        self.gridLayout_2.addWidget(self.label_logoempresa, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.w_encabezado)
        self.w_cuerpo = QtWidgets.QWidget(self.w_contenedor)
        self.w_cuerpo.setObjectName("w_cuerpo")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.w_cuerpo)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.w_cuerpo_menu = QtWidgets.QWidget(self.w_cuerpo)
        self.w_cuerpo_menu.setObjectName("w_cuerpo_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.w_cuerpo_menu)
        self.verticalLayout_2.setContentsMargins(3, 10, 3, 3)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_fotousuario = QtWidgets.QLabel(self.w_cuerpo_menu)
        self.label_fotousuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_fotousuario.setText("")
        self.label_fotousuario.setScaledContents(False)
        self.label_fotousuario.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fotousuario.setObjectName("label_fotousuario")
        self.verticalLayout_2.addWidget(self.label_fotousuario)
        self.btn_proceso_venta = QtWidgets.QToolButton(self.w_cuerpo_menu)
        self.btn_proceso_venta.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_proceso_venta.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_proceso_venta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_proceso_venta.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/ventas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_proceso_venta.setIcon(icon2)
        self.btn_proceso_venta.setObjectName("btn_proceso_venta")
        self.verticalLayout_2.addWidget(self.btn_proceso_venta)
        self.btn_ventas = QtWidgets.QToolButton(self.w_cuerpo_menu)
        self.btn_ventas.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_ventas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ventas.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/operacion_ventas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ventas.setIcon(icon3)
        self.btn_ventas.setObjectName("btn_ventas")
        self.verticalLayout_2.addWidget(self.btn_ventas)
        self.btn_compras = QtWidgets.QToolButton(self.w_cuerpo_menu)
        self.btn_compras.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_compras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_compras.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/compras.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_compras.setIcon(icon4)
        self.btn_compras.setObjectName("btn_compras")
        self.verticalLayout_2.addWidget(self.btn_compras)
        self.btn_empleados = QtWidgets.QToolButton(self.w_cuerpo_menu)
        self.btn_empleados.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_empleados.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_empleados.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/empleados.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_empleados.setIcon(icon5)
        self.btn_empleados.setObjectName("btn_empleados")
        self.verticalLayout_2.addWidget(self.btn_empleados)
        self.btn_proveedores = QtWidgets.QToolButton(self.w_cuerpo_menu)
        self.btn_proveedores.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_proveedores.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_proveedores.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/vendedores.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_proveedores.setIcon(icon6)
        self.btn_proveedores.setObjectName("btn_proveedores")
        self.verticalLayout_2.addWidget(self.btn_proveedores)
        self.btn_clientes = QtWidgets.QToolButton(self.w_cuerpo_menu)
        self.btn_clientes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clientes.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/clientes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_clientes.setIcon(icon7)
        self.btn_clientes.setObjectName("btn_clientes")
        self.verticalLayout_2.addWidget(self.btn_clientes)
        self.btn_productos = QtWidgets.QToolButton(self.w_cuerpo_menu)
        self.btn_productos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/productos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_productos.setIcon(icon8)
        self.btn_productos.setIconSize(QtCore.QSize(35, 35))
        self.btn_productos.setObjectName("btn_productos")
        self.verticalLayout_2.addWidget(self.btn_productos)
        self.btn_mas_opciones = QtWidgets.QToolButton(self.w_cuerpo_menu)
        self.btn_mas_opciones.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_mas_opciones.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/plus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_mas_opciones.setIcon(icon9)
        self.btn_mas_opciones.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btn_mas_opciones.setObjectName("btn_mas_opciones")
        self.verticalLayout_2.addWidget(self.btn_mas_opciones)
        spacerItem1 = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_3.addWidget(self.w_cuerpo_menu, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.w_cuerpo_contenido = QtWidgets.QStackedWidget(self.w_cuerpo)
        self.w_cuerpo_contenido.setStyleSheet("")
        self.w_cuerpo_contenido.setObjectName("w_cuerpo_contenido")
        self.p_inicial = QtWidgets.QWidget()
        self.p_inicial.setObjectName("p_inicial")
        self.gridLayout = QtWidgets.QGridLayout(self.p_inicial)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.p_inicial)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setStyleSheet("image: url(:/Icons/IconosSVG/logo_devrous.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_19.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 1)
        self.w_cuerpo_contenido.addWidget(self.p_inicial)
        self.gridLayout_3.addWidget(self.w_cuerpo_contenido, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.w_cuerpo)
        self.gridLayout_18.addWidget(self.w_contenedor, 0, 0, 1, 1)

        self.retranslateUi(Principal_sistema)
        self.w_cuerpo_contenido.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Principal_sistema)

    def retranslateUi(self, Principal_sistema):
        _translate = QtCore.QCoreApplication.translate
        Principal_sistema.setWindowTitle(_translate("Principal_sistema", "Form"))
        self.btc_minimizar_2.setToolTip(_translate("Principal_sistema", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Minimizar</span></p></body></html>"))
        self.btc_cerrar_2.setToolTip(_translate("Principal_sistema", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Cerrar</span></p></body></html>"))
        self.label_fotousuario.setToolTip(_translate("Principal_sistema", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Perfil</span></p></body></html>"))
        self.btn_proceso_venta.setToolTip(_translate("Principal_sistema", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Venta</span></p></body></html>"))
        self.btn_ventas.setToolTip(_translate("Principal_sistema", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Ventas</span></p></body></html>"))
        self.btn_compras.setToolTip(_translate("Principal_sistema", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Compras</span></p></body></html>"))
        self.btn_empleados.setToolTip(_translate("Principal_sistema", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Empleados</span></p></body></html>"))
        self.btn_proveedores.setToolTip(_translate("Principal_sistema", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Proveedores</span></p></body></html>"))
        self.btn_clientes.setToolTip(_translate("Principal_sistema", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Clientes</span></p></body></html>"))
        self.btn_productos.setToolTip(_translate("Principal_sistema", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Productos</span></p></body></html>"))
        self.btn_productos.setText(_translate("Principal_sistema", "..."))
        self.btn_mas_opciones.setToolTip(_translate("Principal_sistema", "Más Opciones"))
import ibootstrap_rc
import iconos_rc
import iconsdvg_rc
import img_rc
