# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hackl/Documentos/projects/software-punto-de-venta/app/View/UserInterfaceUi/PRODUCTOS_PROVEEDORES.ui'
#
# Created by: PySide6 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_contenedor_productos_proveedores(object):
    def setupUi(self, contenedor_productos_proveedores):
        contenedor_productos_proveedores.setObjectName("contenedor_productos_proveedores")
        contenedor_productos_proveedores.resize(1020, 468)
        contenedor_productos_proveedores.setStyleSheet("#contenedor_encabezado{\n"
"background: #023375;\n"
"}\n"
"#etiqueta_encabezado_productosProveedor{\n"
"color: #fffefb;\n"
"font-size: 18px;\n"
"font-weight:bold;\n"
"font-family:\"Arial\";\n"
"}\n"
"[objectName*=\"contenedor\"]{\n"
"background: #fffefb;\n"
"}\n"
"[objectName*=\"etiqueta_\"]{\n"
"font-size:14px;\n"
"font-family: Arial;\n"
"font-weight:bold;\n"
"color: #1d1c1c;\n"
"}\n"
"[objectName*=\"txt_\"]{\n"
"background: #F5F5F5;\n"
"border:none;\n"
"border-radius: 5px;\n"
"color: #1d1c1c;\n"
"font-size: 14px;\n"
"border-bottom: 1px solid #787878;\n"
"}\n"
"[objectName*=\"txt_\"]:focus{\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"[objectName*=\"btn_producto_del_proveedor\"]{\n"
"background: #00619a;\n"
"font-size: 14px;\n"
"font-family: Arial;\n"
"font-weight: bold;\n"
"min-height: 25px;\n"
"border: none;\n"
"border-radius: 5px;\n"
"color: #fffefb;\n"
"padding: 3px 5px;\n"
"}\n"
"[objectName*=\"btn_producto_del_proveedor\"]:hover{\n"
"background: #2196F3;\n"
"}\n"
"[objectName*=\"btn_producto_del_proveedor\"]:pressed{\n"
"background: #1B80D0;\n"
"}\n"
"[objectName*=\"btn_producto_del_proveedor_eliminar\"]:hover{\n"
"background: #ee1d52;\n"
"}\n"
"[objectName*=\"btn_producto_del_proveedor_eliminar\"]:pressed{\n"
"background: #B13636;\n"
"}\n"
"[objectName*=\"btn_producto_del_proveedor_agregar\"]:hover{\n"
"background: #68a67d;\n"
"}\n"
"[objectName*=\"btn_producto_del_proveedor_agregar\"]:pressed{\n"
"background: #578B69;\n"
"}\n"
"#btn_producto_del_proveedor_cerrar{\n"
"background: #fffefb;\n"
"min-height:15px;\n"
"max-width:15px;\n"
"}\n"
"#btn_producto_del_proveedor_cerrar:pressed{\n"
"background: rgb(222, 221, 218);\n"
"}\n"
"#btn_RefrescarTabla{\n"
"border-radius: 2px;\n"
"background: #e0e0e0;\n"
"padding: 5px;\n"
"}\n"
"#btn_RefrescarTabla:hover{\n"
"background: rgb(179, 179, 179);\n"
"}\n"
"#btn_RefrescarTabla:pressed{\n"
"background: #b6ccd8 ;\n"
"}\n"
"#btn_RefrescarTablaProductos{\n"
"border-radius: 2px;\n"
"background: #e0e0e0;\n"
"padding: 5px;\n"
"}\n"
"#btn_RefrescarTablaProductos:hover{\n"
"background: rgb(179, 179, 179);\n"
"}\n"
"#btn_RefrescarTablaProductos:pressed{\n"
"background: #b6ccd8 ;\n"
"}\n"
"[objectName^=\"cajaopciones_\"]{\n"
"border: none;\n"
"border-bottom: 1px solid rgb(29, 28, 28);\n"
"borde-radius: 5px;\n"
"padding: 2px;\n"
"background-color: #f5f4f1;\n"
"borde-radius: 5px;\n"
"font-size: 14px;\n"
"min-width:120px;\n"
"}\n"
"[objectName^=\"cajaopciones_\"]::drop-down{\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: top right;\n"
"padding-right:5px;\n"
"width: 20%;\n"
"border-left-width: 1px;\n"
"borde-radius: 5px;\n"
"background-color: #f5f4f1;\n"
"}\n"
"[objectName^=\"cajaopciones_\"]::down-arrow{\n"
"image: url(:/Icons/Bootstrap/filter-left.svg);\n"
"width: 17%;\n"
"height: 17%;\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}\n"
"[objectName*=\"tabla_\"] {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"/* Encabezados de la tabla */\n"
"[objectName*=\"tabla_\"] QHeaderView::section {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"    font-family: \"Arial\";\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"/* Encabezado horizontal */\n"
"[objectName*=\"tabla_\"] QHeaderView::horizontal {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Encabezado vertical */\n"
"[objectName*=\"tabla_\"] QHeaderView::vertical {\n"
"    background-color: #023375;\n"
"    color: white;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(contenedor_productos_proveedores)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contenedor_encabezado = QtWidgets.QFrame(contenedor_productos_proveedores)
        self.contenedor_encabezado.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_encabezado.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_encabezado.setObjectName("contenedor_encabezado")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.contenedor_encabezado)
        self.horizontalLayout_3.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.etiqueta_encabezado_productosProveedor = QtWidgets.QLabel(self.contenedor_encabezado)
        self.etiqueta_encabezado_productosProveedor.setObjectName("etiqueta_encabezado_productosProveedor")
        self.horizontalLayout_3.addWidget(self.etiqueta_encabezado_productosProveedor)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_producto_del_proveedor_cerrar = QtWidgets.QPushButton(self.contenedor_encabezado)
        self.btn_producto_del_proveedor_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_producto_del_proveedor_cerrar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/x-lg.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_producto_del_proveedor_cerrar.setIcon(icon)
        self.btn_producto_del_proveedor_cerrar.setObjectName("btn_producto_del_proveedor_cerrar")
        self.horizontalLayout_3.addWidget(self.btn_producto_del_proveedor_cerrar)
        self.verticalLayout.addWidget(self.contenedor_encabezado)
        self.contenedor_scrollarea = QtWidgets.QScrollArea(contenedor_productos_proveedores)
        self.contenedor_scrollarea.setWidgetResizable(True)
        self.contenedor_scrollarea.setObjectName("contenedor_scrollarea")
        self.contenedor_contenido_scrollarea = QtWidgets.QWidget()
        self.contenedor_contenido_scrollarea.setGeometry(QtCore.QRect(0, 0, 1018, 438))
        self.contenedor_contenido_scrollarea.setObjectName("contenedor_contenido_scrollarea")
        self.gridLayout = QtWidgets.QGridLayout(self.contenedor_contenido_scrollarea)
        self.gridLayout.setObjectName("gridLayout")
        self.etiqueta_nombre_del_proveedor = QtWidgets.QLabel(self.contenedor_contenido_scrollarea)
        self.etiqueta_nombre_del_proveedor.setText("")
        self.etiqueta_nombre_del_proveedor.setObjectName("etiqueta_nombre_del_proveedor")
        self.gridLayout.addWidget(self.etiqueta_nombre_del_proveedor, 0, 0, 1, 1)
        self.contenedor_tabs = QtWidgets.QTabWidget(self.contenedor_contenido_scrollarea)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.contenedor_tabs.setFont(font)
        self.contenedor_tabs.setObjectName("contenedor_tabs")
        self.contenedor_tab_productos_de_proveedor = QtWidgets.QWidget()
        self.contenedor_tab_productos_de_proveedor.setObjectName("contenedor_tab_productos_de_proveedor")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.contenedor_tab_productos_de_proveedor)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.contenedor_productos_proveedor = QtWidgets.QFrame(self.contenedor_tab_productos_de_proveedor)
        self.contenedor_productos_proveedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_productos_proveedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_productos_proveedor.setObjectName("contenedor_productos_proveedor")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.contenedor_productos_proveedor)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.contenedor_botones_superior = QtWidgets.QFrame(self.contenedor_productos_proveedor)
        self.contenedor_botones_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_botones_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_botones_superior.setObjectName("contenedor_botones_superior")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.contenedor_botones_superior)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_producto_del_proveedor_editar = QtWidgets.QPushButton(self.contenedor_botones_superior)
        self.btn_producto_del_proveedor_editar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/editar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_producto_del_proveedor_editar.setIcon(icon1)
        self.btn_producto_del_proveedor_editar.setObjectName("btn_producto_del_proveedor_editar")
        self.gridLayout_4.addWidget(self.btn_producto_del_proveedor_editar, 1, 3, 1, 1, QtCore.Qt.AlignRight)
        self.btn_RefrescarTabla = QtWidgets.QPushButton(self.contenedor_botones_superior)
        self.btn_RefrescarTabla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_RefrescarTabla.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/IconosSVG/base_datos_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_RefrescarTabla.setIcon(icon2)
        self.btn_RefrescarTabla.setObjectName("btn_RefrescarTabla")
        self.gridLayout_4.addWidget(self.btn_RefrescarTabla, 1, 1, 1, 1)
        self.btn_producto_del_proveedor_eliminar = QtWidgets.QPushButton(self.contenedor_botones_superior)
        self.btn_producto_del_proveedor_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/cerrar_blanco.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_producto_del_proveedor_eliminar.setIcon(icon3)
        self.btn_producto_del_proveedor_eliminar.setObjectName("btn_producto_del_proveedor_eliminar")
        self.gridLayout_4.addWidget(self.btn_producto_del_proveedor_eliminar, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.contenedor_botones_superior, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.etiqueta_nombre_producto = QtWidgets.QLabel(self.contenedor_productos_proveedor)
        self.etiqueta_nombre_producto.setObjectName("etiqueta_nombre_producto")
        self.horizontalLayout.addWidget(self.etiqueta_nombre_producto)
        self.cajaopciones_filtro_nombre = QtWidgets.QComboBox(self.contenedor_productos_proveedor)
        self.cajaopciones_filtro_nombre.setObjectName("cajaopciones_filtro_nombre")
        self.cajaopciones_filtro_nombre.addItem("")
        self.cajaopciones_filtro_nombre.addItem("")
        self.horizontalLayout.addWidget(self.cajaopciones_filtro_nombre)
        self.txt_nombre_producto = QtWidgets.QLineEdit(self.contenedor_productos_proveedor)
        self.txt_nombre_producto.setClearButtonEnabled(True)
        self.txt_nombre_producto.setObjectName("txt_nombre_producto")
        self.horizontalLayout.addWidget(self.txt_nombre_producto)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabla_productos_del_proveedor = QtWidgets.QTableView(self.contenedor_productos_proveedor)
        self.tabla_productos_del_proveedor.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_productos_del_proveedor.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_productos_del_proveedor.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_productos_del_proveedor.setObjectName("tabla_productos_del_proveedor")
        self.tabla_productos_del_proveedor.horizontalHeader().setDefaultSectionSize(200)
        self.tabla_productos_del_proveedor.horizontalHeader().setMinimumSectionSize(150)
        self.tabla_productos_del_proveedor.horizontalHeader().setStretchLastSection(True)
        self.tabla_productos_del_proveedor.verticalHeader().setVisible(False)
        self.tabla_productos_del_proveedor.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.tabla_productos_del_proveedor, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.contenedor_productos_proveedor, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/box-seam.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contenedor_tabs.addTab(self.contenedor_tab_productos_de_proveedor, icon4, "")
        self.contenedor_tab_productos_de_sistema = QtWidgets.QWidget()
        self.contenedor_tab_productos_de_sistema.setObjectName("contenedor_tab_productos_de_sistema")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.contenedor_tab_productos_de_sistema)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.contenedor_botones_superior_productos_del_sistema = QtWidgets.QFrame(self.contenedor_tab_productos_de_sistema)
        self.contenedor_botones_superior_productos_del_sistema.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_botones_superior_productos_del_sistema.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_botones_superior_productos_del_sistema.setObjectName("contenedor_botones_superior_productos_del_sistema")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.contenedor_botones_superior_productos_del_sistema)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(577, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 0, 1, 1)
        self.btn_producto_del_proveedor_para_agregar = QtWidgets.QPushButton(self.contenedor_botones_superior_productos_del_sistema)
        self.btn_producto_del_proveedor_para_agregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconosBlancos/Icons/iconos/Blanco/vincular.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_producto_del_proveedor_para_agregar.setIcon(icon5)
        self.btn_producto_del_proveedor_para_agregar.setObjectName("btn_producto_del_proveedor_para_agregar")
        self.gridLayout_7.addWidget(self.btn_producto_del_proveedor_para_agregar, 0, 2, 1, 1)
        self.btn_RefrescarTablaProductos = QtWidgets.QPushButton(self.contenedor_botones_superior_productos_del_sistema)
        self.btn_RefrescarTablaProductos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_RefrescarTablaProductos.setText("")
        self.btn_RefrescarTablaProductos.setIcon(icon2)
        self.btn_RefrescarTablaProductos.setObjectName("btn_RefrescarTablaProductos")
        self.gridLayout_7.addWidget(self.btn_RefrescarTablaProductos, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.contenedor_botones_superior_productos_del_sistema, 0, 0, 1, 2)
        self.contenedor_contenido_tab_productos_del_sistema = QtWidgets.QFrame(self.contenedor_tab_productos_de_sistema)
        self.contenedor_contenido_tab_productos_del_sistema.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_contenido_tab_productos_del_sistema.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_contenido_tab_productos_del_sistema.setObjectName("contenedor_contenido_tab_productos_del_sistema")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.contenedor_contenido_tab_productos_del_sistema)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.etiqueta_nombreproducto_del_sistema = QtWidgets.QLabel(self.contenedor_contenido_tab_productos_del_sistema)
        self.etiqueta_nombreproducto_del_sistema.setObjectName("etiqueta_nombreproducto_del_sistema")
        self.horizontalLayout_2.addWidget(self.etiqueta_nombreproducto_del_sistema)
        self.cajaopciones_filtro_nombre_productos_del_sistema = QtWidgets.QComboBox(self.contenedor_contenido_tab_productos_del_sistema)
        self.cajaopciones_filtro_nombre_productos_del_sistema.setObjectName("cajaopciones_filtro_nombre_productos_del_sistema")
        self.cajaopciones_filtro_nombre_productos_del_sistema.addItem("")
        self.cajaopciones_filtro_nombre_productos_del_sistema.addItem("")
        self.horizontalLayout_2.addWidget(self.cajaopciones_filtro_nombre_productos_del_sistema)
        self.txt_nombre_productodelsistema = QtWidgets.QLineEdit(self.contenedor_contenido_tab_productos_del_sistema)
        self.txt_nombre_productodelsistema.setClearButtonEnabled(True)
        self.txt_nombre_productodelsistema.setObjectName("txt_nombre_productodelsistema")
        self.horizontalLayout_2.addWidget(self.txt_nombre_productodelsistema)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabla_productos_del_sistema = QtWidgets.QTableView(self.contenedor_contenido_tab_productos_del_sistema)
        self.tabla_productos_del_sistema.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_productos_del_sistema.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_productos_del_sistema.setGridStyle(QtCore.Qt.DashLine)
        self.tabla_productos_del_sistema.setObjectName("tabla_productos_del_sistema")
        self.tabla_productos_del_sistema.horizontalHeader().setDefaultSectionSize(200)
        self.tabla_productos_del_sistema.horizontalHeader().setMinimumSectionSize(150)
        self.tabla_productos_del_sistema.horizontalHeader().setStretchLastSection(True)
        self.tabla_productos_del_sistema.verticalHeader().setVisible(False)
        self.gridLayout_8.addWidget(self.tabla_productos_del_sistema, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.contenedor_contenido_tab_productos_del_sistema, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.contenedor_tab_productos_de_sistema)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.etiqueta_producto_agregarAProveedor = QtWidgets.QLabel(self.frame)
        self.etiqueta_producto_agregarAProveedor.setObjectName("etiqueta_producto_agregarAProveedor")
        self.gridLayout_6.addWidget(self.etiqueta_producto_agregarAProveedor, 0, 0, 1, 1)
        self.tabla_Productos_A_VincularProveedor = QtWidgets.QTableView(self.frame)
        self.tabla_Productos_A_VincularProveedor.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_Productos_A_VincularProveedor.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_Productos_A_VincularProveedor.setObjectName("tabla_Productos_A_VincularProveedor")
        self.tabla_Productos_A_VincularProveedor.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.tabla_Productos_A_VincularProveedor, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame, 1, 1, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/boxes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contenedor_tabs.addTab(self.contenedor_tab_productos_de_sistema, icon6, "")
        self.gridLayout.addWidget(self.contenedor_tabs, 1, 0, 1, 1)
        self.contenedor_scrollarea.setWidget(self.contenedor_contenido_scrollarea)
        self.verticalLayout.addWidget(self.contenedor_scrollarea)

        self.retranslateUi(contenedor_productos_proveedores)
        self.contenedor_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(contenedor_productos_proveedores)

    def retranslateUi(self, contenedor_productos_proveedores):
        _translate = QtCore.QCoreApplication.translate
        contenedor_productos_proveedores.setWindowTitle(_translate("contenedor_productos_proveedores", "Form"))
        self.etiqueta_encabezado_productosProveedor.setText(_translate("contenedor_productos_proveedores", "PRODUCTOS DEL PROVEEDOR"))
        self.btn_producto_del_proveedor_editar.setText(_translate("contenedor_productos_proveedores", "Manejar Precio"))
        self.btn_RefrescarTabla.setToolTip(_translate("contenedor_productos_proveedores", "Refrescar tabla"))
        self.btn_producto_del_proveedor_eliminar.setText(_translate("contenedor_productos_proveedores", "Quitar"))
        self.etiqueta_nombre_producto.setText(_translate("contenedor_productos_proveedores", "Buscar Producto"))
        self.cajaopciones_filtro_nombre.setItemText(0, _translate("contenedor_productos_proveedores", "Igual A"))
        self.cajaopciones_filtro_nombre.setItemText(1, _translate("contenedor_productos_proveedores", "Que Contenga"))
        self.txt_nombre_producto.setPlaceholderText(_translate("contenedor_productos_proveedores", "Nombre del Producto"))
        self.contenedor_tabs.setTabText(self.contenedor_tabs.indexOf(self.contenedor_tab_productos_de_proveedor), _translate("contenedor_productos_proveedores", "Productos del Proveedor"))
        self.btn_producto_del_proveedor_para_agregar.setText(_translate("contenedor_productos_proveedores", "Vincular al proveedor"))
        self.btn_RefrescarTablaProductos.setToolTip(_translate("contenedor_productos_proveedores", "Refrescar tabla"))
        self.etiqueta_nombreproducto_del_sistema.setText(_translate("contenedor_productos_proveedores", "Nombre del Producto:"))
        self.cajaopciones_filtro_nombre_productos_del_sistema.setItemText(0, _translate("contenedor_productos_proveedores", "Es Igual"))
        self.cajaopciones_filtro_nombre_productos_del_sistema.setItemText(1, _translate("contenedor_productos_proveedores", "Que Contenga"))
        self.txt_nombre_productodelsistema.setPlaceholderText(_translate("contenedor_productos_proveedores", "Nombre del Producto"))
        self.etiqueta_producto_agregarAProveedor.setText(_translate("contenedor_productos_proveedores", "Productos a vincular con el proveedor"))
        self.contenedor_tabs.setTabText(self.contenedor_tabs.indexOf(self.contenedor_tab_productos_de_sistema), _translate("contenedor_productos_proveedores", "Productos del Sistema"))
from ...Source import ibootstrap_rc
from ...Source import iconosSVG_rc
