# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ADMINISTRAR_PUESTOS.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formulario_puestos(object):
    def setupUi(self, Formulario_puestos):
        Formulario_puestos.setObjectName("Formulario_puestos")
        Formulario_puestos.resize(878, 569)
        Formulario_puestos.setMinimumSize(QtCore.QSize(0, 0))
        Formulario_puestos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Formulario_puestos.setStyleSheet("#Formulario_puestos{\n"
"background: #fffefb;\n"
"}\n"
"[objectName*=\"contenedor\"]{\n"
"background: #fffefb;\n"
"}\n"
"[objectName*=\"etiquetaTitulo_\"]{\n"
"font-size: 18px;\n"
"font-weight:bold;\n"
"font-family:Arial;\n"
"color: #1d1c1c;\n"
"}\n"
"[objectName*=\"etiqueta_\"]{\n"
"font-size: 14px;\n"
"font-weight:bold;\n"
"font-family:Arial;\n"
"color: #1d1c1c;\n"
"}\n"
"[objectName*=\"etiquetasubtitulo_\"]{\n"
"font-size: 15px;\n"
"font-weight:bold;\n"
"font-family:Arial;\n"
"color: #1d1c1c;\n"
"}\n"
"[objectName*=\"txt_\"]{\n"
"font-size: 14px;\n"
"font-family:Arial;\n"
"color: #1d1c1c;\n"
"background: #F5F5F5;\n"
"border:none;\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid #1d1c1c;\n"
"}\n"
"[objectName*=\"txt_\"]:focus{\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"[objectName*=\"txtlargo_\"]{\n"
"font-size: 14px;\n"
"font-family:Arial;\n"
"color: #1d1c1c;\n"
"background: #F5F5F5;\n"
"border:none;\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid #1d1c1c;\n"
"max-height: 100px;\n"
"}\n"
"[objectName*=\"txtlargo_\"]:focus{\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"[objectName*=\"cajaopcion_\"]{\n"
"font-size: 14px;\n"
"font-weight:bold;\n"
"font-family:Arial;\n"
"color: #1d1c1c;\n"
"}\n"
"[objectName^=\"decimal_\"]{\n"
"border: none;\n"
"border-bottom: 1px solid #3b3c3d;\n"
"border-radius: 4px;\n"
"background-color: #F5F5F5;\n"
"font-size: 14px;\n"
"padding: 2px;\n"
"}\n"
"[objectName^=\"decimal_\"]::focus{\n"
"border-bottom: 2px solid #00668c;\n"
"}\n"
"[objectName^=\"tiempo_\"]{\n"
"border: none;\n"
"border-bottom: 1px solid #3b3c3d;\n"
"border-radius: 4px;\n"
"background-color: #F5F5F5;\n"
"font-size: 14px;\n"
"padding: 2px;\n"
"}\n"
"[objectName^=\"tiempo_\"]::focus{\n"
"border-bottom: 2px solid #00668c;\n"
"}\n"
"[objectName^=\"btn_btn_\"]{\n"
"background: #00619a;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color: #fffefb;\n"
"border: none;\n"
"border-radius:5px;\n"
"min-height: 25px;\n"
"padding-right:10px;\n"
"padding-left:10px;\n"
"}\n"
"[objectName^=\"btn_btn_\"]:hover{\n"
"background: #2196F3;\n"
"}\n"
"#btn_btn_agregar:hover{\n"
"background: #68a67d;\n"
"}\n"
"#btn_btn_eliminar:hover{\n"
"background: #EE1D52;\n"
"}\n"
"[objectName*=\"tabla_\"] QScrollBar:vertical {\n"
"    border: 1px solid gray;\n"
"    background: #023375;\n"
"    width: 5px;\n"
"border-radius:2px;\n"
"    margin: 22px 0 22px 0; \n"
"}\n"
"#QListWidget{\n"
"min-weight: 80px;\n"
"}\n"
"[objectName*=\"tabla_\"] QScrollBar::handle:vertical {\n"
"    background: #023375;  /* Color del \"manejador\" */\n"
"    min-height: 20px;  /* Altura mínima del manejador */\n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] QScrollBar::add-line:vertical,\n"
"[objectName*=\"tabla_\"] QScrollBar::sub-line:vertical {\n"
"background-color:none;\n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] QScrollBar::handle:horizontal {\n"
"    background: #023375;  /* Color del \"manejador\" horizontal */\n"
"    height: 5px;  /* Altura de la barra horizontal */\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] QScrollBar:horizontal {\n"
"    background: #023375;\n"
"    height: 5px;  /* Altura de la barra */\n"
"    border-radius: 2px;\n"
"}\n"
"[objectName*=\"tabla_\"] QHeaderView::section {\n"
"    background-color: #023375;  /* Color de fondo de los encabezados */\n"
"    color: white;  /* Color del texto */\n"
"    padding: 5px;  /* Espaciado interno */\n"
"    border: 1px solid gray;  /* Borde de los encabezados */\n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] QHeaderView::horizontal {\n"
"    background-color: #023375;  /* Color de fondo de los encabezados horizontales */\n"
"    color: white;  /* Color del texto */\n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] QHeaderView::vertical {\n"
"    background-color: #023375;  /* Color de fondo de los encabezados verticales */\n"
"    color: white;  /* Color del texto */\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Formulario_puestos)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.contenedor = QtWidgets.QFrame(Formulario_puestos)
        self.contenedor.setStyleSheet("")
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.contenedor)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.etiquetaTitulo_administrarpuestos = QtWidgets.QLabel(self.contenedor)
        self.etiquetaTitulo_administrarpuestos.setObjectName("etiquetaTitulo_administrarpuestos")
        self.gridLayout_6.addWidget(self.etiquetaTitulo_administrarpuestos, 0, 0, 1, 1)
        self.contenedor_formulario = QtWidgets.QFrame(self.contenedor)
        self.contenedor_formulario.setStyleSheet("")
        self.contenedor_formulario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_formulario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_formulario.setObjectName("contenedor_formulario")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.contenedor_formulario)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_btn_eliminar = QtWidgets.QPushButton(self.contenedor_formulario)
        self.btn_btn_eliminar.setObjectName("btn_btn_eliminar")
        self.gridLayout_3.addWidget(self.btn_btn_eliminar, 11, 3, 1, 1)
        self.btn_btn_agregar = QtWidgets.QPushButton(self.contenedor_formulario)
        self.btn_btn_agregar.setObjectName("btn_btn_agregar")
        self.gridLayout_3.addWidget(self.btn_btn_agregar, 11, 4, 1, 1)
        self.txtlargo_descripcionpuesto = QtWidgets.QPlainTextEdit(self.contenedor_formulario)
        self.txtlargo_descripcionpuesto.setObjectName("txtlargo_descripcionpuesto")
        self.gridLayout_3.addWidget(self.txtlargo_descripcionpuesto, 6, 0, 1, 5)
        self.etiqueta_diaslaborales = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_diaslaborales.setObjectName("etiqueta_diaslaborales")
        self.gridLayout_3.addWidget(self.etiqueta_diaslaborales, 8, 0, 1, 5)
        self.line = QtWidgets.QFrame(self.contenedor_formulario)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 7, 0, 1, 5)
        self.etiqueta_salario = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_salario.setObjectName("etiqueta_salario")
        self.gridLayout_3.addWidget(self.etiqueta_salario, 1, 0, 1, 2)
        self.etiqueta_nombrepuesto = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_nombrepuesto.setObjectName("etiqueta_nombrepuesto")
        self.gridLayout_3.addWidget(self.etiqueta_nombrepuesto, 0, 0, 1, 2)
        self.etiqueta_horas_laborales = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_horas_laborales.setObjectName("etiqueta_horas_laborales")
        self.gridLayout_3.addWidget(self.etiqueta_horas_laborales, 2, 0, 1, 2)
        self.etiqueta_horaentrada = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_horaentrada.setObjectName("etiqueta_horaentrada")
        self.gridLayout_3.addWidget(self.etiqueta_horaentrada, 3, 0, 1, 2)
        self.etiqueta_horasalida = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_horasalida.setObjectName("etiqueta_horasalida")
        self.gridLayout_3.addWidget(self.etiqueta_horasalida, 4, 0, 1, 2)
        self.btn_btn_limpiar = QtWidgets.QPushButton(self.contenedor_formulario)
        self.btn_btn_limpiar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_limpiar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/borrador.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_limpiar.setIcon(icon)
        self.btn_btn_limpiar.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_limpiar.setObjectName("btn_btn_limpiar")
        self.gridLayout_3.addWidget(self.btn_btn_limpiar, 11, 1, 1, 1)
        self.tiempo_horasalida = QtWidgets.QTimeEdit(self.contenedor_formulario)
        self.tiempo_horasalida.setCalendarPopup(True)
        self.tiempo_horasalida.setObjectName("tiempo_horasalida")
        self.gridLayout_3.addWidget(self.tiempo_horasalida, 4, 2, 1, 3)
        self.txt_nombrepuesto = QtWidgets.QLineEdit(self.contenedor_formulario)
        self.txt_nombrepuesto.setObjectName("txt_nombrepuesto")
        self.gridLayout_3.addWidget(self.txt_nombrepuesto, 0, 2, 1, 3)
        self.tiempo_horaentrada = QtWidgets.QTimeEdit(self.contenedor_formulario)
        self.tiempo_horaentrada.setCalendarPopup(True)
        self.tiempo_horaentrada.setObjectName("tiempo_horaentrada")
        self.gridLayout_3.addWidget(self.tiempo_horaentrada, 3, 2, 1, 3)
        self.decimal_salario = QtWidgets.QDoubleSpinBox(self.contenedor_formulario)
        self.decimal_salario.setMaximum(1e+31)
        self.decimal_salario.setObjectName("decimal_salario")
        self.gridLayout_3.addWidget(self.decimal_salario, 1, 2, 1, 3)
        self.decimal_horaslaborales = QtWidgets.QDoubleSpinBox(self.contenedor_formulario)
        self.decimal_horaslaborales.setMaximum(1e+31)
        self.decimal_horaslaborales.setObjectName("decimal_horaslaborales")
        self.gridLayout_3.addWidget(self.decimal_horaslaborales, 2, 2, 1, 3)
        self.btn_btn_actualizar = QtWidgets.QPushButton(self.contenedor_formulario)
        self.btn_btn_actualizar.setObjectName("btn_btn_actualizar")
        self.gridLayout_3.addWidget(self.btn_btn_actualizar, 11, 2, 1, 1)
        self.contenedor_diaslaborales = QtWidgets.QFrame(self.contenedor_formulario)
        self.contenedor_diaslaborales.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_diaslaborales.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_diaslaborales.setObjectName("contenedor_diaslaborales")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.contenedor_diaslaborales)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cajaopcion_martes = QtWidgets.QCheckBox(self.contenedor_diaslaborales)
        self.cajaopcion_martes.setObjectName("cajaopcion_martes")
        self.gridLayout_5.addWidget(self.cajaopcion_martes, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 4, 0, 1, 1)
        self.cajaopcion_lunes = QtWidgets.QCheckBox(self.contenedor_diaslaborales)
        self.cajaopcion_lunes.setObjectName("cajaopcion_lunes")
        self.gridLayout_5.addWidget(self.cajaopcion_lunes, 0, 0, 1, 1)
        self.cajaopcion_miercoles = QtWidgets.QCheckBox(self.contenedor_diaslaborales)
        self.cajaopcion_miercoles.setObjectName("cajaopcion_miercoles")
        self.gridLayout_5.addWidget(self.cajaopcion_miercoles, 2, 0, 1, 1)
        self.cajaopcion_jueves = QtWidgets.QCheckBox(self.contenedor_diaslaborales)
        self.cajaopcion_jueves.setObjectName("cajaopcion_jueves")
        self.gridLayout_5.addWidget(self.cajaopcion_jueves, 0, 1, 1, 1)
        self.cajaopcion_viernes = QtWidgets.QCheckBox(self.contenedor_diaslaborales)
        self.cajaopcion_viernes.setObjectName("cajaopcion_viernes")
        self.gridLayout_5.addWidget(self.cajaopcion_viernes, 1, 1, 1, 1)
        self.cajaopcion_sabado = QtWidgets.QCheckBox(self.contenedor_diaslaborales)
        self.cajaopcion_sabado.setObjectName("cajaopcion_sabado")
        self.gridLayout_5.addWidget(self.cajaopcion_sabado, 2, 1, 1, 1)
        self.cajaopcion_domingo = QtWidgets.QCheckBox(self.contenedor_diaslaborales)
        self.cajaopcion_domingo.setObjectName("cajaopcion_domingo")
        self.gridLayout_5.addWidget(self.cajaopcion_domingo, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.contenedor_diaslaborales, 9, 0, 1, 5)
        self.etiqueta_descripcion = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_descripcion.setObjectName("etiqueta_descripcion")
        self.gridLayout_3.addWidget(self.etiqueta_descripcion, 5, 0, 1, 2)
        self.gridLayout_6.addWidget(self.contenedor_formulario, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.contenedor)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.etiquetasubtitulo_departamentosexistentes = QtWidgets.QLabel(self.frame)
        self.etiquetasubtitulo_departamentosexistentes.setWordWrap(True)
        self.etiquetasubtitulo_departamentosexistentes.setObjectName("etiquetasubtitulo_departamentosexistentes")
        self.gridLayout_2.addWidget(self.etiquetasubtitulo_departamentosexistentes, 2, 0, 1, 1)
        self.etiquetasubtitulo_departamentosvinculadas = QtWidgets.QLabel(self.frame)
        self.etiquetasubtitulo_departamentosvinculadas.setWordWrap(True)
        self.etiquetasubtitulo_departamentosvinculadas.setObjectName("etiquetasubtitulo_departamentosvinculadas")
        self.gridLayout_2.addWidget(self.etiquetasubtitulo_departamentosvinculadas, 2, 2, 1, 2)
        self.lista_departamentosexistentes = QtWidgets.QListWidget(self.frame)
        self.lista_departamentosexistentes.setObjectName("lista_departamentosexistentes")
        self.gridLayout_2.addWidget(self.lista_departamentosexistentes, 3, 0, 1, 1)
        self.contenedor_botonesvincular = QtWidgets.QFrame(self.frame)
        self.contenedor_botonesvincular.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_botonesvincular.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_botonesvincular.setObjectName("contenedor_botonesvincular")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.contenedor_botonesvincular)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_btn_vincular = QtWidgets.QPushButton(self.contenedor_botonesvincular)
        self.btn_btn_vincular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_vincular.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/arrow-right-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_vincular.setIcon(icon1)
        self.btn_btn_vincular.setObjectName("btn_btn_vincular")
        self.gridLayout_4.addWidget(self.btn_btn_vincular, 0, 0, 1, 1)
        self.btn_btn_desvincular = QtWidgets.QPushButton(self.contenedor_botonesvincular)
        self.btn_btn_desvincular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_desvincular.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/arrow-left-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_desvincular.setIcon(icon2)
        self.btn_btn_desvincular.setObjectName("btn_btn_desvincular")
        self.gridLayout_4.addWidget(self.btn_btn_desvincular, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.contenedor_botonesvincular, 3, 1, 1, 1)
        self.lista_departamentosvinculadas = QtWidgets.QListWidget(self.frame)
        self.lista_departamentosvinculadas.setObjectName("lista_departamentosvinculadas")
        self.gridLayout_2.addWidget(self.lista_departamentosvinculadas, 3, 2, 1, 2)
        self.tabla_listapuestos = QtWidgets.QTableView(self.frame)
        self.tabla_listapuestos.setObjectName("tabla_listapuestos")
        self.gridLayout_2.addWidget(self.tabla_listapuestos, 1, 0, 1, 4)
        self.btn_btn_buscarpuesto = QtWidgets.QPushButton(self.frame)
        self.btn_btn_buscarpuesto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_buscarpuesto.setObjectName("btn_btn_buscarpuesto")
        self.gridLayout_2.addWidget(self.btn_btn_buscarpuesto, 0, 3, 1, 1)
        self.txt_buscarpuesto = QtWidgets.QLineEdit(self.frame)
        self.txt_buscarpuesto.setObjectName("txt_buscarpuesto")
        self.gridLayout_2.addWidget(self.txt_buscarpuesto, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.contenedor, 0, 0, 1, 1)

        self.retranslateUi(Formulario_puestos)
        QtCore.QMetaObject.connectSlotsByName(Formulario_puestos)

    def retranslateUi(self, Formulario_puestos):
        _translate = QtCore.QCoreApplication.translate
        Formulario_puestos.setWindowTitle(_translate("Formulario_puestos", "Form"))
        self.etiquetaTitulo_administrarpuestos.setText(_translate("Formulario_puestos", "Administrar puestos"))
        self.btn_btn_eliminar.setText(_translate("Formulario_puestos", "Eliminar"))
        self.btn_btn_agregar.setText(_translate("Formulario_puestos", "Agregar"))
        self.etiqueta_diaslaborales.setText(_translate("Formulario_puestos", "Dias laborales:"))
        self.etiqueta_salario.setText(_translate("Formulario_puestos", "Salario:"))
        self.etiqueta_nombrepuesto.setText(_translate("Formulario_puestos", "Nombre:"))
        self.etiqueta_horas_laborales.setText(_translate("Formulario_puestos", "Horas laborales:"))
        self.etiqueta_horaentrada.setText(_translate("Formulario_puestos", "Hora entrada"))
        self.etiqueta_horasalida.setText(_translate("Formulario_puestos", "Hora salida"))
        self.txt_nombrepuesto.setPlaceholderText(_translate("Formulario_puestos", "Nombre"))
        self.btn_btn_actualizar.setText(_translate("Formulario_puestos", "Actualizar"))
        self.cajaopcion_martes.setText(_translate("Formulario_puestos", "Martes"))
        self.cajaopcion_lunes.setText(_translate("Formulario_puestos", "Lunes"))
        self.cajaopcion_miercoles.setText(_translate("Formulario_puestos", "Miercoles"))
        self.cajaopcion_jueves.setText(_translate("Formulario_puestos", "Jueves"))
        self.cajaopcion_viernes.setText(_translate("Formulario_puestos", "Viernes"))
        self.cajaopcion_sabado.setText(_translate("Formulario_puestos", "Sabado"))
        self.cajaopcion_domingo.setText(_translate("Formulario_puestos", "Domingo"))
        self.etiqueta_descripcion.setText(_translate("Formulario_puestos", "Descripción del puesto"))
        self.etiquetasubtitulo_departamentosexistentes.setText(_translate("Formulario_puestos", "Departamentos"))
        self.etiquetasubtitulo_departamentosvinculadas.setText(_translate("Formulario_puestos", "Dep.  Asignado"))
        self.btn_btn_vincular.setToolTip(_translate("Formulario_puestos", "Vincular"))
        self.btn_btn_desvincular.setToolTip(_translate("Formulario_puestos", "Desvincular"))
        self.btn_btn_buscarpuesto.setText(_translate("Formulario_puestos", "Buscar"))
        self.txt_buscarpuesto.setPlaceholderText(_translate("Formulario_puestos", "Nombre del puesto"))
from ...Source import ibootstrap_rc
from ...Source import iconsdvg_rc
