# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\Microsoft\software-punto-de-venta\app\View\UserInterfaceUi\UI_BIENVENIDA.ui'
#
# Created by: PySide6 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Bienvenida(object):
    def setupUi(self, Bienvenida):
        Bienvenida.setObjectName("Bienvenida")
        Bienvenida.resize(450, 250)
        Bienvenida.setMinimumSize(QtCore.QSize(450, 250))
        Bienvenida.setMaximumSize(QtCore.QSize(450, 250))
        Bienvenida.setStyleSheet("#Bienvenida{\n"
"background-color: #fffefb;\n"
"}\n"
"#contenedor{\n"
"background-color: #fffefb;\n"
"border-radius: 20px;\n"
"}\n"
"#etiqueta_titulo{\n"
"font-family: Arial;\n"
"font-weight:bold;\n"
"font-size: 18px;\n"
"}\n"
"")
        self.contenedor = QtWidgets.QWidget(Bienvenida)
        self.contenedor.setGeometry(QtCore.QRect(38, 20, 371, 211))
        self.contenedor.setStyleSheet("#btn_btn_registrar{\n"
"background-color: rgb(0, 97, 154);\n"
"border-radius: 5px;\n"
"color:#fffefb;\n"
"}\n"
"#btn_btn_registrar:hover{\n"
"background-color:#68a67d;\n"
"}\n"
"#btn_btn_registrar:pressed{\n"
"background-color:#fffefb;\n"
"color:#1d1c1c;\n"
"}")
        self.contenedor.setObjectName("contenedor")
        self.etiqueta_imagen = QtWidgets.QLabel(self.contenedor)
        self.etiqueta_imagen.setGeometry(QtCore.QRect(80, 30, 191, 131))
        self.etiqueta_imagen.setStyleSheet("")
        self.etiqueta_imagen.setText("")
        self.etiqueta_imagen.setPixmap(QtGui.QPixmap(":/Icons/IconosSVG/ilustracion_hombre_con_computadora.png"))
        self.etiqueta_imagen.setScaledContents(True)
        self.etiqueta_imagen.setObjectName("etiqueta_imagen")
        self.etiqueta_titulo = QtWidgets.QLabel(self.contenedor)
        self.etiqueta_titulo.setGeometry(QtCore.QRect(20, 0, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.etiqueta_titulo.setFont(font)
        self.etiqueta_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.etiqueta_titulo.setObjectName("etiqueta_titulo")
        self.btn_btn_registrar = QtWidgets.QPushButton(self.contenedor)
        self.btn_btn_registrar.setGeometry(QtCore.QRect(78, 160, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_btn_registrar.setFont(font)
        self.btn_btn_registrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_registrar.setStyleSheet("")
        self.btn_btn_registrar.setObjectName("btn_btn_registrar")
        self.label = QtWidgets.QLabel(self.contenedor)
        self.label.setGeometry(QtCore.QRect(240, 40, 91, 31))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Icons/IconosSVG/logo_devrous.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.etiqueta_imagen.raise_()
        self.btn_btn_registrar.raise_()
        self.etiqueta_titulo.raise_()
        self.label.raise_()

        self.retranslateUi(Bienvenida)
        QtCore.QMetaObject.connectSlotsByName(Bienvenida)

    def retranslateUi(self, Bienvenida):
        _translate = QtCore.QCoreApplication.translate
        Bienvenida.setWindowTitle(_translate("Bienvenida", "Form"))
        self.etiqueta_titulo.setText(_translate("Bienvenida", "Bienvenido a tu sistema de negocios"))
        self.btn_btn_registrar.setText(_translate("Bienvenida", "Comencemos a Trabajar"))
from ...Source import ibootstrap_rc
from ...Source import iconsdvg_rc
