# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_CONTROL_ROLES.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Control_Roles_Permisos(object):
    def setupUi(self, Control_Roles_Permisos):
        Control_Roles_Permisos.setObjectName("Control_Roles_Permisos")
        Control_Roles_Permisos.resize(600, 450)
        Control_Roles_Permisos.setMinimumSize(QtCore.QSize(600, 450))
        Control_Roles_Permisos.setMaximumSize(QtCore.QSize(600, 450))
        Control_Roles_Permisos.setStyleSheet("#Control_Roles_Permisos{\n"
"background: #fffefb;\n"
"}\n"
"#contenedor{\n"
"background: #fffefb;\n"
"}\n"
"[objectName*=\"etiquetaTitulo_\"]{\n"
"font-size:18px;\n"
"color: #1d1c1c;\n"
"font-weight: bold;\n"
"font-family:Arial;\n"
"}\n"
"[objectName*=\"etiqueta_\"]{\n"
"font-size:14px;\n"
"color: #1d1c1c;\n"
"font-weight: bold;\n"
"font-family:Arial;\n"
"}\n"
"[objectName*=\"txt_\"]{\n"
"font-size:14px;\n"
"color: #1d1c1c;\n"
"font-family:Arial;\n"
"background: #F5F5F5;\n"
"border-radius:5px;\n"
"border: none;\n"
"border-bottom: 1px solid #1d1c1c;\n"
"min-width: 300px;\n"
"}\n"
"[objectName*=\"btn_btn_\"]{\n"
"font-size:14px;\n"
"color: #fffefb;\n"
"font-family:Arial;\n"
"font-weight: bold;\n"
"background: #00619a;\n"
"border-radius:5px;\n"
"height: 25px;\n"
"border: none;\n"
"padding-left: 10px;\n"
"padding-right:10px;\n"
"}\n"
"[objectName*=\"txt_\"]:focus{\n"
"border: none;\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"[objectName*=\"btn_btn_\"]:hover{\n"
"background: #2196F3;\n"
"}\n"
"[objectName*=\"tabla_\"] QScrollBar:vertical {\n"
"    border: 1px solid gray;\n"
"    background: #023375;\n"
"    width: 5px;\n"
"border-radius:2px;\n"
"    margin: 22px 0 22px 0; \n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] QScrollBar::handle:vertical {\n"
"    background: #023375;  /* Color del \"manejador\" */\n"
"    min-height: 20px;  /* Altura mínima del manejador */\n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] QScrollBar::add-line:vertical,\n"
"[objectName*=\"tabla_\"] QScrollBar::sub-line:vertical {\n"
"background-color:none;\n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] QScrollBar::handle:horizontal {\n"
"    background: #023375;  /* Color del \"manejador\" horizontal */\n"
"    height: 5px;  /* Altura de la barra horizontal */\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] QScrollBar:horizontal {\n"
"    background: #023375;\n"
"    height: 5px;  /* Altura de la barra */\n"
"    border-radius: 2px;\n"
"}\n"
"[objectName*=\"tabla_\"] QHeaderView::section {\n"
"    background-color: #023375;  /* Color de fondo de los encabezados */\n"
"    color: white;  /* Color del texto */\n"
"    padding: 5px;  /* Espaciado interno */\n"
"    border: 1px solid gray;  /* Borde de los encabezados */\n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] QHeaderView::horizontal {\n"
"    background-color: #023375;  /* Color de fondo de los encabezados horizontales */\n"
"    color: white;  /* Color del texto */\n"
"}\n"
"\n"
"[objectName*=\"tabla_\"] QHeaderView::vertical {\n"
"    background-color: #023375;  /* Color de fondo de los encabezados verticales */\n"
"    color: white;  /* Color del texto */\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Control_Roles_Permisos)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.contenedor = QtWidgets.QFrame(Control_Roles_Permisos)
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.contenedor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.etiquetaTitulo_Roles = QtWidgets.QLabel(self.contenedor)
        self.etiquetaTitulo_Roles.setObjectName("etiquetaTitulo_Roles")
        self.gridLayout_2.addWidget(self.etiquetaTitulo_Roles, 0, 0, 1, 1)
        self.contenedor_tabla = QtWidgets.QFrame(self.contenedor)
        self.contenedor_tabla.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_tabla.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_tabla.setObjectName("contenedor_tabla")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.contenedor_tabla)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_btn_buscar = QtWidgets.QPushButton(self.contenedor_tabla)
        self.btn_btn_buscar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_buscar.setObjectName("btn_btn_buscar")
        self.gridLayout_3.addWidget(self.btn_btn_buscar, 0, 3, 1, 1)
        self.txt_nombrerol = QtWidgets.QLineEdit(self.contenedor_tabla)
        self.txt_nombrerol.setObjectName("txt_nombrerol")
        self.gridLayout_3.addWidget(self.txt_nombrerol, 1, 0, 1, 2)
        self.tabla_listapermisosroles = QtWidgets.QTableWidget(self.contenedor_tabla)
        self.tabla_listapermisosroles.setObjectName("tabla_listapermisosroles")
        self.tabla_listapermisosroles.setColumnCount(0)
        self.tabla_listapermisosroles.setRowCount(0)
        self.gridLayout_3.addWidget(self.tabla_listapermisosroles, 2, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 2)
        self.etiqueta_buscar = QtWidgets.QLabel(self.contenedor_tabla)
        self.etiqueta_buscar.setObjectName("etiqueta_buscar")
        self.gridLayout_3.addWidget(self.etiqueta_buscar, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.contenedor_tabla, 1, 0, 1, 1)
        self.btn_btn_nuevorol = QtWidgets.QPushButton(self.contenedor)
        self.btn_btn_nuevorol.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_nuevorol.setObjectName("btn_btn_nuevorol")
        self.gridLayout_2.addWidget(self.btn_btn_nuevorol, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout.addWidget(self.contenedor, 0, 0, 1, 1)

        self.retranslateUi(Control_Roles_Permisos)
        QtCore.QMetaObject.connectSlotsByName(Control_Roles_Permisos)

    def retranslateUi(self, Control_Roles_Permisos):
        _translate = QtCore.QCoreApplication.translate
        Control_Roles_Permisos.setWindowTitle(_translate("Control_Roles_Permisos", "Form"))
        self.etiquetaTitulo_Roles.setText(_translate("Control_Roles_Permisos", "Roles y permisos"))
        self.btn_btn_buscar.setText(_translate("Control_Roles_Permisos", "Buscar"))
        self.txt_nombrerol.setPlaceholderText(_translate("Control_Roles_Permisos", "Nombre del rol"))
        self.etiqueta_buscar.setText(_translate("Control_Roles_Permisos", "Buscar:"))
        self.btn_btn_nuevorol.setText(_translate("Control_Roles_Permisos", "Crear un nuevo Rol"))
