# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_CONTROL_DEPARTAMENTOS.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Control_departamentos(object):
    def setupUi(self, Control_departamentos):
        Control_departamentos.setObjectName("Control_departamentos")
        Control_departamentos.resize(878, 565)
        Control_departamentos.setStyleSheet("#Control_departamentos{\n"
"background: #fffefb;\n"
"}\n"
"[objectName*=\"contenedor\"]{\n"
"background: #fffefb;\n"
"}\n"
"#etiquetaTitulo{\n"
"color: #1d1c1c;\n"
"font-size:20px;\n"
"font-weight:bold;\n"
"font-family:Arial;\n"
"}\n"
"[objectName*=\"etiqueta_\"]{\n"
"color: #1d1c1c;\n"
"font-size:14px;\n"
"font-weight:bold;\n"
"font-family:Arial;\n"
"}\n"
"[objectName*=\"etiquetasubtitulo_\"]{\n"
"color: #1d1c1c;\n"
"font-size:15px;\n"
"font-weight:bold;\n"
"font-family:Arial;\n"
"}\n"
"[objectName*=\"btn_btn_\"]{\n"
"color:#fffefb;\n"
"font-size:14px;\n"
"font-family:Arial;\n"
"font-weight:bold;\n"
"background: #023375;\n"
"border:none;\n"
"border-radius: 5px;\n"
"padding-left:5px;\n"
"padding-right: 5px;\n"
"height:25px;\n"
"margin-left: 3px;\n"
"margin-right:3px;\n"
"}\n"
"[objectName*=\"btn_btn_\"]:hover{\n"
"background: #2196F3;\n"
"}\n"
"#btn_btn_eliminar:hover{\n"
"background:#EE1D52;\n"
"}\n"
"[objectName*=\"txt_\"]{\n"
"background: #F5F5F5;\n"
"font-size: 12px;\n"
"border: none;\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid #1d1c1c;\n"
"font-family:Arial;\n"
"}\n"
"[objectName*=\"txt_\"]:focus{\n"
"background: #F5F5F5;\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"[objectName*=\"txtlargo_\"]{\n"
"background: #F5F5F5;\n"
"font-size: 12px;\n"
"border: none;\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid #1d1c1c;\n"
"font-family:Arial;\n"
"height: 100px;\n"
"max-height: 100px;\n"
"}\n"
"[objectName*=\"txtlargo_\"]:focus{\n"
"background: #F5F5F5;\n"
"border-bottom: 2px solid #023375;\n"
"}\n"
"QListWidget {\n"
"    background-color: #fffefb;  /* Color de fondo del QListWidget */\n"
"    border: 1px solid gray;  /* Borde del QListWidget */\n"
"    border-radius: 2px;  /* Bordes redondeados */\n"
"    padding: 5px;  /* Espaciado interno */\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    background-color: #fffefb;  /* Color de fondo de los elementos */\n"
"    color: #1d1c1c;  /* Color del texto */\n"
"    padding: 5px;  /* Espaciado interno de los elementos */\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #0056a6;  /* Color de fondo al seleccionar un elemento */\n"
"    color: white;  /* Color del texto del elemento seleccionado */\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid gray;\n"
"    background: #023375;\n"
"    width: 5px;\n"
"    border-radius: 2px;\n"
"    margin: 22px 0; \n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #023375;  /* Color del \"manejador\" */\n"
"    min-height: 20px;  /* Altura mínima del manejador */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
" border: 1px solid gray;\n"
"    background: #023375;\n"
"    height: 5px;  /* Altura de la barra */\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #023375;  /* Color del \"manejador\" horizontal */\n"
"    height: 5px;  /* Altura de la barra horizontal */\n"
"    border-radius:3px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Control_departamentos)
        self.gridLayout.setObjectName("gridLayout")
        self.contenedor = QtWidgets.QFrame(Control_departamentos)
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.contenedor)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_btn_guardar = QtWidgets.QPushButton(self.contenedor)
        self.btn_btn_guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_guardar.setObjectName("btn_btn_guardar")
        self.gridLayout_2.addWidget(self.btn_btn_guardar, 0, 2, 1, 1)
        self.btn_btn_eliminar = QtWidgets.QPushButton(self.contenedor)
        self.btn_btn_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_eliminar.setObjectName("btn_btn_eliminar")
        self.gridLayout_2.addWidget(self.btn_btn_eliminar, 0, 4, 1, 1)
        self.btn_btn_actualizar = QtWidgets.QPushButton(self.contenedor)
        self.btn_btn_actualizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_actualizar.setObjectName("btn_btn_actualizar")
        self.gridLayout_2.addWidget(self.btn_btn_actualizar, 0, 3, 1, 1)
        self.etiquetaTitulo = QtWidgets.QLabel(self.contenedor)
        self.etiquetaTitulo.setObjectName("etiquetaTitulo")
        self.gridLayout_2.addWidget(self.etiquetaTitulo, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.contenedor_formulario = QtWidgets.QFrame(self.contenedor)
        self.contenedor_formulario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_formulario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_formulario.setObjectName("contenedor_formulario")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.contenedor_formulario)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lista_departamentosexistentes = QtWidgets.QListWidget(self.contenedor_formulario)
        self.lista_departamentosexistentes.setObjectName("lista_departamentosexistentes")
        self.gridLayout_4.addWidget(self.lista_departamentosexistentes, 3, 5, 5, 3)
        self.txtlargo_descripciondepartamento = QtWidgets.QPlainTextEdit(self.contenedor_formulario)
        self.txtlargo_descripciondepartamento.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txtlargo_descripciondepartamento.setObjectName("txtlargo_descripciondepartamento")
        self.gridLayout_4.addWidget(self.txtlargo_descripciondepartamento, 5, 0, 1, 4)
        self.etiquetasubtitulo_sucursalesexistentes = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiquetasubtitulo_sucursalesexistentes.setObjectName("etiquetasubtitulo_sucursalesexistentes")
        self.gridLayout_4.addWidget(self.etiquetasubtitulo_sucursalesexistentes, 6, 0, 1, 1)
        self.etiqueta_nombredepartamento = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_nombredepartamento.setObjectName("etiqueta_nombredepartamento")
        self.gridLayout_4.addWidget(self.etiqueta_nombredepartamento, 1, 0, 1, 1)
        self.lista_sucursalesexistentes = QtWidgets.QListWidget(self.contenedor_formulario)
        self.lista_sucursalesexistentes.setObjectName("lista_sucursalesexistentes")
        self.gridLayout_4.addWidget(self.lista_sucursalesexistentes, 7, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 2, 1, 1)
        self.btn_btn_limpiar = QtWidgets.QPushButton(self.contenedor_formulario)
        self.btn_btn_limpiar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_limpiar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/IconosSVG/borrador.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_limpiar.setIcon(icon)
        self.btn_btn_limpiar.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_limpiar.setObjectName("btn_btn_limpiar")
        self.gridLayout_4.addWidget(self.btn_btn_limpiar, 1, 3, 1, 1)
        self.etiquetasubtitulo_sucursalesvinculadas = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiquetasubtitulo_sucursalesvinculadas.setWordWrap(True)
        self.etiquetasubtitulo_sucursalesvinculadas.setObjectName("etiquetasubtitulo_sucursalesvinculadas")
        self.gridLayout_4.addWidget(self.etiquetasubtitulo_sucursalesvinculadas, 6, 2, 1, 2)
        self.lista_sucursalesvinculadas = QtWidgets.QListWidget(self.contenedor_formulario)
        self.lista_sucursalesvinculadas.setObjectName("lista_sucursalesvinculadas")
        self.gridLayout_4.addWidget(self.lista_sucursalesvinculadas, 7, 2, 1, 2)
        self.contenedor_botonesvincular = QtWidgets.QFrame(self.contenedor_formulario)
        self.contenedor_botonesvincular.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_botonesvincular.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_botonesvincular.setObjectName("contenedor_botonesvincular")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.contenedor_botonesvincular)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_btn_vincular = QtWidgets.QPushButton(self.contenedor_botonesvincular)
        self.btn_btn_vincular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_vincular.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/arrow-right-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_vincular.setIcon(icon1)
        self.btn_btn_vincular.setObjectName("btn_btn_vincular")
        self.gridLayout_3.addWidget(self.btn_btn_vincular, 0, 0, 1, 1)
        self.btn_btn_desvincular = QtWidgets.QPushButton(self.contenedor_botonesvincular)
        self.btn_btn_desvincular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_desvincular.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Bootstrap/arrow-left-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_desvincular.setIcon(icon2)
        self.btn_btn_desvincular.setObjectName("btn_btn_desvincular")
        self.gridLayout_3.addWidget(self.btn_btn_desvincular, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.contenedor_botonesvincular, 7, 1, 1, 1)
        self.lista_puestosasignados = QtWidgets.QListWidget(self.contenedor_formulario)
        self.lista_puestosasignados.setObjectName("lista_puestosasignados")
        self.gridLayout_4.addWidget(self.lista_puestosasignados, 3, 8, 5, 1)
        self.txt_nombredepartamento = QtWidgets.QLineEdit(self.contenedor_formulario)
        self.txt_nombredepartamento.setObjectName("txt_nombredepartamento")
        self.gridLayout_4.addWidget(self.txt_nombredepartamento, 2, 0, 1, 3)
        self.etiquetasubtitulo_puestosasignados = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiquetasubtitulo_puestosasignados.setObjectName("etiquetasubtitulo_puestosasignados")
        self.gridLayout_4.addWidget(self.etiquetasubtitulo_puestosasignados, 2, 8, 1, 1)
        self.etiquetasubtitulo_departamentosexistentes = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiquetasubtitulo_departamentosexistentes.setObjectName("etiquetasubtitulo_departamentosexistentes")
        self.gridLayout_4.addWidget(self.etiquetasubtitulo_departamentosexistentes, 2, 5, 1, 1)
        self.txt_buscardepartamento = QtWidgets.QLineEdit(self.contenedor_formulario)
        self.txt_buscardepartamento.setObjectName("txt_buscardepartamento")
        self.gridLayout_4.addWidget(self.txt_buscardepartamento, 1, 5, 1, 4)
        self.etiqueta_descripciondepartamento = QtWidgets.QLabel(self.contenedor_formulario)
        self.etiqueta_descripciondepartamento.setObjectName("etiqueta_descripciondepartamento")
        self.gridLayout_4.addWidget(self.etiqueta_descripciondepartamento, 4, 0, 1, 4)
        self.gridLayout_2.addWidget(self.contenedor_formulario, 1, 0, 1, 6)
        self.gridLayout.addWidget(self.contenedor, 0, 0, 1, 1)

        self.retranslateUi(Control_departamentos)
        QtCore.QMetaObject.connectSlotsByName(Control_departamentos)
        Control_departamentos.setTabOrder(self.txt_nombredepartamento, self.txtlargo_descripciondepartamento)
        Control_departamentos.setTabOrder(self.txtlargo_descripciondepartamento, self.btn_btn_vincular)
        Control_departamentos.setTabOrder(self.btn_btn_vincular, self.btn_btn_desvincular)
        Control_departamentos.setTabOrder(self.btn_btn_desvincular, self.lista_sucursalesexistentes)
        Control_departamentos.setTabOrder(self.lista_sucursalesexistentes, self.lista_sucursalesvinculadas)
        Control_departamentos.setTabOrder(self.lista_sucursalesvinculadas, self.btn_btn_limpiar)
        Control_departamentos.setTabOrder(self.btn_btn_limpiar, self.txt_buscardepartamento)
        Control_departamentos.setTabOrder(self.txt_buscardepartamento, self.lista_departamentosexistentes)
        Control_departamentos.setTabOrder(self.lista_departamentosexistentes, self.lista_puestosasignados)
        Control_departamentos.setTabOrder(self.lista_puestosasignados, self.btn_btn_guardar)
        Control_departamentos.setTabOrder(self.btn_btn_guardar, self.btn_btn_actualizar)
        Control_departamentos.setTabOrder(self.btn_btn_actualizar, self.btn_btn_eliminar)

    def retranslateUi(self, Control_departamentos):
        _translate = QtCore.QCoreApplication.translate
        Control_departamentos.setWindowTitle(_translate("Control_departamentos", "Form"))
        self.btn_btn_guardar.setText(_translate("Control_departamentos", "Guardar"))
        self.btn_btn_eliminar.setText(_translate("Control_departamentos", "Eliminar"))
        self.btn_btn_actualizar.setText(_translate("Control_departamentos", "Actualizar"))
        self.etiquetaTitulo.setText(_translate("Control_departamentos", "Departamentos"))
        self.etiquetasubtitulo_sucursalesexistentes.setText(_translate("Control_departamentos", "Sucursales existentes:"))
        self.etiqueta_nombredepartamento.setText(_translate("Control_departamentos", "Nombre del departamento:"))
        self.etiquetasubtitulo_sucursalesvinculadas.setText(_translate("Control_departamentos", "Sucusales vinculadas"))
        self.btn_btn_vincular.setToolTip(_translate("Control_departamentos", "Vincular"))
        self.btn_btn_desvincular.setToolTip(_translate("Control_departamentos", "Desvincular"))
        self.etiquetasubtitulo_puestosasignados.setText(_translate("Control_departamentos", "Puestos Asignados"))
        self.etiquetasubtitulo_departamentosexistentes.setText(_translate("Control_departamentos", "Departamentos existentes"))
        self.txt_buscardepartamento.setPlaceholderText(_translate("Control_departamentos", " Buscar Departamento"))
        self.etiqueta_descripciondepartamento.setText(_translate("Control_departamentos", "Descripcion del departamento:"))
from ...Source import ibootstrap_rc
from ...Source import iconsdvg_rc
