# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\Microsoft\software-punto-de-venta\app\View\UserInterfaceUi\UI_VENTANA_SALUDO_INGRESO.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bienvenida(object):
    def setupUi(self, Bienvenida):
        Bienvenida.setObjectName("Bienvenida")
        Bienvenida.resize(412, 416)
        Bienvenida.setStyleSheet("#contenedor{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}\n"
"#btn_entrar{\n"
"background-color: #00668c;\n"
"border-top-left-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"color: #fffefb;\n"
"font-weight:bold;\n"
"font-size: 14px;\n"
"}\n"
"#btn_entrar:hover{\n"
"background-color: rgb(0, 122, 167);\n"
"}\n"
"#btn_entrar:pressed{\n"
"    background-color: rgb(0, 86, 118);\n"
"}")
        self.contenedor = QtWidgets.QFrame(Bienvenida)
        self.contenedor.setGeometry(QtCore.QRect(20, 10, 371, 391))
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.etiquetaBuendia = QtWidgets.QLabel(self.contenedor)
        self.etiquetaBuendia.setEnabled(False)
        self.etiquetaBuendia.setGeometry(QtCore.QRect(10, 40, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Albertus Extra Bold")
        font.setPointSize(24)
        self.etiquetaBuendia.setFont(font)
        self.etiquetaBuendia.setAlignment(QtCore.Qt.AlignCenter)
        self.etiquetaBuendia.setObjectName("etiquetaBuendia")
        self.etiquetaNombreUsuario = QtWidgets.QLabel(self.contenedor)
        self.etiquetaNombreUsuario.setGeometry(QtCore.QRect(10, 100, 351, 151))
        font = QtGui.QFont()
        font.setFamily("Antique Olive Compact")
        font.setPointSize(25)
        self.etiquetaNombreUsuario.setFont(font)
        self.etiquetaNombreUsuario.setAlignment(QtCore.Qt.AlignCenter)
        self.etiquetaNombreUsuario.setWordWrap(True)
        self.etiquetaNombreUsuario.setObjectName("etiquetaNombreUsuario")
        self.etiquetaEslogan = QtWidgets.QLabel(self.contenedor)
        self.etiquetaEslogan.setGeometry(QtCore.QRect(10, 330, 351, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        self.etiquetaEslogan.setFont(font)
        self.etiquetaEslogan.setAlignment(QtCore.Qt.AlignCenter)
        self.etiquetaEslogan.setWordWrap(True)
        self.etiquetaEslogan.setObjectName("etiquetaEslogan")
        self.btn_entrar = QtWidgets.QPushButton(self.contenedor)
        self.btn_entrar.setGeometry(QtCore.QRect(150, 290, 75, 23))
        self.btn_entrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_entrar.setObjectName("btn_entrar")

        self.retranslateUi(Bienvenida)
        QtCore.QMetaObject.connectSlotsByName(Bienvenida)

    def retranslateUi(self, Bienvenida):
        _translate = QtCore.QCoreApplication.translate
        Bienvenida.setWindowTitle(_translate("Bienvenida", "Form"))
        self.etiquetaBuendia.setText(_translate("Bienvenida", "Excelente Mañana"))
        self.etiquetaNombreUsuario.setText(_translate("Bienvenida", "Luis Angel Vallejo Perez"))
        self.etiquetaEslogan.setText(_translate("Bienvenida", "Los grandes vendedores no venden, hacen que la gente quiera comprar."))
        self.btn_entrar.setText(_translate("Bienvenida", "Entrar"))
